
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventWaitlist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model EventWaitlist
 * 
 */
export type EventWaitlistModel = runtime.Types.Result.DefaultSelection<Prisma.$EventWaitlistPayload>

export type AggregateEventWaitlist = {
  _count: EventWaitlistCountAggregateOutputType | null
  _avg: EventWaitlistAvgAggregateOutputType | null
  _sum: EventWaitlistSumAggregateOutputType | null
  _min: EventWaitlistMinAggregateOutputType | null
  _max: EventWaitlistMaxAggregateOutputType | null
}

export type EventWaitlistAvgAggregateOutputType = {
  quantity: number | null
}

export type EventWaitlistSumAggregateOutputType = {
  quantity: number | null
}

export type EventWaitlistMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  userId: string | null
  email: string | null
  quantity: number | null
  notified: boolean | null
  createdAt: Date | null
}

export type EventWaitlistMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  userId: string | null
  email: string | null
  quantity: number | null
  notified: boolean | null
  createdAt: Date | null
}

export type EventWaitlistCountAggregateOutputType = {
  id: number
  eventId: number
  userId: number
  email: number
  quantity: number
  notified: number
  createdAt: number
  _all: number
}


export type EventWaitlistAvgAggregateInputType = {
  quantity?: true
}

export type EventWaitlistSumAggregateInputType = {
  quantity?: true
}

export type EventWaitlistMinAggregateInputType = {
  id?: true
  eventId?: true
  userId?: true
  email?: true
  quantity?: true
  notified?: true
  createdAt?: true
}

export type EventWaitlistMaxAggregateInputType = {
  id?: true
  eventId?: true
  userId?: true
  email?: true
  quantity?: true
  notified?: true
  createdAt?: true
}

export type EventWaitlistCountAggregateInputType = {
  id?: true
  eventId?: true
  userId?: true
  email?: true
  quantity?: true
  notified?: true
  createdAt?: true
  _all?: true
}

export type EventWaitlistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventWaitlist to aggregate.
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventWaitlists to fetch.
   */
  orderBy?: Prisma.EventWaitlistOrderByWithRelationInput | Prisma.EventWaitlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventWaitlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventWaitlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventWaitlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventWaitlists
  **/
  _count?: true | EventWaitlistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EventWaitlistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EventWaitlistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventWaitlistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventWaitlistMaxAggregateInputType
}

export type GetEventWaitlistAggregateType<T extends EventWaitlistAggregateArgs> = {
      [P in keyof T & keyof AggregateEventWaitlist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventWaitlist[P]>
    : Prisma.GetScalarType<T[P], AggregateEventWaitlist[P]>
}




export type EventWaitlistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventWaitlistWhereInput
  orderBy?: Prisma.EventWaitlistOrderByWithAggregationInput | Prisma.EventWaitlistOrderByWithAggregationInput[]
  by: Prisma.EventWaitlistScalarFieldEnum[] | Prisma.EventWaitlistScalarFieldEnum
  having?: Prisma.EventWaitlistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventWaitlistCountAggregateInputType | true
  _avg?: EventWaitlistAvgAggregateInputType
  _sum?: EventWaitlistSumAggregateInputType
  _min?: EventWaitlistMinAggregateInputType
  _max?: EventWaitlistMaxAggregateInputType
}

export type EventWaitlistGroupByOutputType = {
  id: string
  eventId: string
  userId: string
  email: string
  quantity: number
  notified: boolean
  createdAt: Date
  _count: EventWaitlistCountAggregateOutputType | null
  _avg: EventWaitlistAvgAggregateOutputType | null
  _sum: EventWaitlistSumAggregateOutputType | null
  _min: EventWaitlistMinAggregateOutputType | null
  _max: EventWaitlistMaxAggregateOutputType | null
}

type GetEventWaitlistGroupByPayload<T extends EventWaitlistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventWaitlistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventWaitlistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventWaitlistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventWaitlistGroupByOutputType[P]>
      }
    >
  >



export type EventWaitlistWhereInput = {
  AND?: Prisma.EventWaitlistWhereInput | Prisma.EventWaitlistWhereInput[]
  OR?: Prisma.EventWaitlistWhereInput[]
  NOT?: Prisma.EventWaitlistWhereInput | Prisma.EventWaitlistWhereInput[]
  id?: Prisma.StringFilter<"EventWaitlist"> | string
  eventId?: Prisma.StringFilter<"EventWaitlist"> | string
  userId?: Prisma.StringFilter<"EventWaitlist"> | string
  email?: Prisma.StringFilter<"EventWaitlist"> | string
  quantity?: Prisma.IntFilter<"EventWaitlist"> | number
  notified?: Prisma.BoolFilter<"EventWaitlist"> | boolean
  createdAt?: Prisma.DateTimeFilter<"EventWaitlist"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}

export type EventWaitlistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  notified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
}

export type EventWaitlistWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  eventId_userId?: Prisma.EventWaitlistEventIdUserIdCompoundUniqueInput
  AND?: Prisma.EventWaitlistWhereInput | Prisma.EventWaitlistWhereInput[]
  OR?: Prisma.EventWaitlistWhereInput[]
  NOT?: Prisma.EventWaitlistWhereInput | Prisma.EventWaitlistWhereInput[]
  eventId?: Prisma.StringFilter<"EventWaitlist"> | string
  userId?: Prisma.StringFilter<"EventWaitlist"> | string
  email?: Prisma.StringFilter<"EventWaitlist"> | string
  quantity?: Prisma.IntFilter<"EventWaitlist"> | number
  notified?: Prisma.BoolFilter<"EventWaitlist"> | boolean
  createdAt?: Prisma.DateTimeFilter<"EventWaitlist"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}, "id" | "eventId_userId">

export type EventWaitlistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  notified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.EventWaitlistCountOrderByAggregateInput
  _avg?: Prisma.EventWaitlistAvgOrderByAggregateInput
  _max?: Prisma.EventWaitlistMaxOrderByAggregateInput
  _min?: Prisma.EventWaitlistMinOrderByAggregateInput
  _sum?: Prisma.EventWaitlistSumOrderByAggregateInput
}

export type EventWaitlistScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventWaitlistScalarWhereWithAggregatesInput | Prisma.EventWaitlistScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventWaitlistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventWaitlistScalarWhereWithAggregatesInput | Prisma.EventWaitlistScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventWaitlist"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventWaitlist"> | string
  userId?: Prisma.StringWithAggregatesFilter<"EventWaitlist"> | string
  email?: Prisma.StringWithAggregatesFilter<"EventWaitlist"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"EventWaitlist"> | number
  notified?: Prisma.BoolWithAggregatesFilter<"EventWaitlist"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventWaitlist"> | Date | string
}

export type EventWaitlistCreateInput = {
  id?: string
  userId: string
  email: string
  quantity?: number
  notified?: boolean
  createdAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutWaitlistInput
}

export type EventWaitlistUncheckedCreateInput = {
  id?: string
  eventId: string
  userId: string
  email: string
  quantity?: number
  notified?: boolean
  createdAt?: Date | string
}

export type EventWaitlistUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutWaitlistNestedInput
}

export type EventWaitlistUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventWaitlistCreateManyInput = {
  id?: string
  eventId: string
  userId: string
  email: string
  quantity?: number
  notified?: boolean
  createdAt?: Date | string
}

export type EventWaitlistUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventWaitlistUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventWaitlistListRelationFilter = {
  every?: Prisma.EventWaitlistWhereInput
  some?: Prisma.EventWaitlistWhereInput
  none?: Prisma.EventWaitlistWhereInput
}

export type EventWaitlistOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventWaitlistEventIdUserIdCompoundUniqueInput = {
  eventId: string
  userId: string
}

export type EventWaitlistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  notified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EventWaitlistAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type EventWaitlistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  notified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EventWaitlistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  notified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EventWaitlistSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type EventWaitlistCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventWaitlistCreateWithoutEventInput, Prisma.EventWaitlistUncheckedCreateWithoutEventInput> | Prisma.EventWaitlistCreateWithoutEventInput[] | Prisma.EventWaitlistUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventWaitlistCreateOrConnectWithoutEventInput | Prisma.EventWaitlistCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventWaitlistCreateManyEventInputEnvelope
  connect?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
}

export type EventWaitlistUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventWaitlistCreateWithoutEventInput, Prisma.EventWaitlistUncheckedCreateWithoutEventInput> | Prisma.EventWaitlistCreateWithoutEventInput[] | Prisma.EventWaitlistUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventWaitlistCreateOrConnectWithoutEventInput | Prisma.EventWaitlistCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventWaitlistCreateManyEventInputEnvelope
  connect?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
}

export type EventWaitlistUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventWaitlistCreateWithoutEventInput, Prisma.EventWaitlistUncheckedCreateWithoutEventInput> | Prisma.EventWaitlistCreateWithoutEventInput[] | Prisma.EventWaitlistUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventWaitlistCreateOrConnectWithoutEventInput | Prisma.EventWaitlistCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventWaitlistUpsertWithWhereUniqueWithoutEventInput | Prisma.EventWaitlistUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventWaitlistCreateManyEventInputEnvelope
  set?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  disconnect?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  delete?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  connect?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  update?: Prisma.EventWaitlistUpdateWithWhereUniqueWithoutEventInput | Prisma.EventWaitlistUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventWaitlistUpdateManyWithWhereWithoutEventInput | Prisma.EventWaitlistUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventWaitlistScalarWhereInput | Prisma.EventWaitlistScalarWhereInput[]
}

export type EventWaitlistUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventWaitlistCreateWithoutEventInput, Prisma.EventWaitlistUncheckedCreateWithoutEventInput> | Prisma.EventWaitlistCreateWithoutEventInput[] | Prisma.EventWaitlistUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventWaitlistCreateOrConnectWithoutEventInput | Prisma.EventWaitlistCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventWaitlistUpsertWithWhereUniqueWithoutEventInput | Prisma.EventWaitlistUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventWaitlistCreateManyEventInputEnvelope
  set?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  disconnect?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  delete?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  connect?: Prisma.EventWaitlistWhereUniqueInput | Prisma.EventWaitlistWhereUniqueInput[]
  update?: Prisma.EventWaitlistUpdateWithWhereUniqueWithoutEventInput | Prisma.EventWaitlistUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventWaitlistUpdateManyWithWhereWithoutEventInput | Prisma.EventWaitlistUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventWaitlistScalarWhereInput | Prisma.EventWaitlistScalarWhereInput[]
}

export type EventWaitlistCreateWithoutEventInput = {
  id?: string
  userId: string
  email: string
  quantity?: number
  notified?: boolean
  createdAt?: Date | string
}

export type EventWaitlistUncheckedCreateWithoutEventInput = {
  id?: string
  userId: string
  email: string
  quantity?: number
  notified?: boolean
  createdAt?: Date | string
}

export type EventWaitlistCreateOrConnectWithoutEventInput = {
  where: Prisma.EventWaitlistWhereUniqueInput
  create: Prisma.XOR<Prisma.EventWaitlistCreateWithoutEventInput, Prisma.EventWaitlistUncheckedCreateWithoutEventInput>
}

export type EventWaitlistCreateManyEventInputEnvelope = {
  data: Prisma.EventWaitlistCreateManyEventInput | Prisma.EventWaitlistCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventWaitlistUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventWaitlistWhereUniqueInput
  update: Prisma.XOR<Prisma.EventWaitlistUpdateWithoutEventInput, Prisma.EventWaitlistUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventWaitlistCreateWithoutEventInput, Prisma.EventWaitlistUncheckedCreateWithoutEventInput>
}

export type EventWaitlistUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventWaitlistWhereUniqueInput
  data: Prisma.XOR<Prisma.EventWaitlistUpdateWithoutEventInput, Prisma.EventWaitlistUncheckedUpdateWithoutEventInput>
}

export type EventWaitlistUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventWaitlistScalarWhereInput
  data: Prisma.XOR<Prisma.EventWaitlistUpdateManyMutationInput, Prisma.EventWaitlistUncheckedUpdateManyWithoutEventInput>
}

export type EventWaitlistScalarWhereInput = {
  AND?: Prisma.EventWaitlistScalarWhereInput | Prisma.EventWaitlistScalarWhereInput[]
  OR?: Prisma.EventWaitlistScalarWhereInput[]
  NOT?: Prisma.EventWaitlistScalarWhereInput | Prisma.EventWaitlistScalarWhereInput[]
  id?: Prisma.StringFilter<"EventWaitlist"> | string
  eventId?: Prisma.StringFilter<"EventWaitlist"> | string
  userId?: Prisma.StringFilter<"EventWaitlist"> | string
  email?: Prisma.StringFilter<"EventWaitlist"> | string
  quantity?: Prisma.IntFilter<"EventWaitlist"> | number
  notified?: Prisma.BoolFilter<"EventWaitlist"> | boolean
  createdAt?: Prisma.DateTimeFilter<"EventWaitlist"> | Date | string
}

export type EventWaitlistCreateManyEventInput = {
  id?: string
  userId: string
  email: string
  quantity?: number
  notified?: boolean
  createdAt?: Date | string
}

export type EventWaitlistUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventWaitlistUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventWaitlistUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  notified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EventWaitlistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  userId?: boolean
  email?: boolean
  quantity?: boolean
  notified?: boolean
  createdAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventWaitlist"]>

export type EventWaitlistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  userId?: boolean
  email?: boolean
  quantity?: boolean
  notified?: boolean
  createdAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventWaitlist"]>

export type EventWaitlistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  userId?: boolean
  email?: boolean
  quantity?: boolean
  notified?: boolean
  createdAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventWaitlist"]>

export type EventWaitlistSelectScalar = {
  id?: boolean
  eventId?: boolean
  userId?: boolean
  email?: boolean
  quantity?: boolean
  notified?: boolean
  createdAt?: boolean
}

export type EventWaitlistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "userId" | "email" | "quantity" | "notified" | "createdAt", ExtArgs["result"]["eventWaitlist"]>
export type EventWaitlistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventWaitlistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventWaitlistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}

export type $EventWaitlistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventWaitlist"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    userId: string
    email: string
    quantity: number
    notified: boolean
    createdAt: Date
  }, ExtArgs["result"]["eventWaitlist"]>
  composites: {}
}

export type EventWaitlistGetPayload<S extends boolean | null | undefined | EventWaitlistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload, S>

export type EventWaitlistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventWaitlistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventWaitlistCountAggregateInputType | true
  }

export interface EventWaitlistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventWaitlist'], meta: { name: 'EventWaitlist' } }
  /**
   * Find zero or one EventWaitlist that matches the filter.
   * @param {EventWaitlistFindUniqueArgs} args - Arguments to find a EventWaitlist
   * @example
   * // Get one EventWaitlist
   * const eventWaitlist = await prisma.eventWaitlist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventWaitlistFindUniqueArgs>(args: Prisma.SelectSubset<T, EventWaitlistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventWaitlist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventWaitlistFindUniqueOrThrowArgs} args - Arguments to find a EventWaitlist
   * @example
   * // Get one EventWaitlist
   * const eventWaitlist = await prisma.eventWaitlist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventWaitlistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventWaitlistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventWaitlist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistFindFirstArgs} args - Arguments to find a EventWaitlist
   * @example
   * // Get one EventWaitlist
   * const eventWaitlist = await prisma.eventWaitlist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventWaitlistFindFirstArgs>(args?: Prisma.SelectSubset<T, EventWaitlistFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventWaitlist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistFindFirstOrThrowArgs} args - Arguments to find a EventWaitlist
   * @example
   * // Get one EventWaitlist
   * const eventWaitlist = await prisma.eventWaitlist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventWaitlistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventWaitlistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventWaitlists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventWaitlists
   * const eventWaitlists = await prisma.eventWaitlist.findMany()
   * 
   * // Get first 10 EventWaitlists
   * const eventWaitlists = await prisma.eventWaitlist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventWaitlistWithIdOnly = await prisma.eventWaitlist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventWaitlistFindManyArgs>(args?: Prisma.SelectSubset<T, EventWaitlistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventWaitlist.
   * @param {EventWaitlistCreateArgs} args - Arguments to create a EventWaitlist.
   * @example
   * // Create one EventWaitlist
   * const EventWaitlist = await prisma.eventWaitlist.create({
   *   data: {
   *     // ... data to create a EventWaitlist
   *   }
   * })
   * 
   */
  create<T extends EventWaitlistCreateArgs>(args: Prisma.SelectSubset<T, EventWaitlistCreateArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventWaitlists.
   * @param {EventWaitlistCreateManyArgs} args - Arguments to create many EventWaitlists.
   * @example
   * // Create many EventWaitlists
   * const eventWaitlist = await prisma.eventWaitlist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventWaitlistCreateManyArgs>(args?: Prisma.SelectSubset<T, EventWaitlistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventWaitlists and returns the data saved in the database.
   * @param {EventWaitlistCreateManyAndReturnArgs} args - Arguments to create many EventWaitlists.
   * @example
   * // Create many EventWaitlists
   * const eventWaitlist = await prisma.eventWaitlist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventWaitlists and only return the `id`
   * const eventWaitlistWithIdOnly = await prisma.eventWaitlist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventWaitlistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventWaitlistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventWaitlist.
   * @param {EventWaitlistDeleteArgs} args - Arguments to delete one EventWaitlist.
   * @example
   * // Delete one EventWaitlist
   * const EventWaitlist = await prisma.eventWaitlist.delete({
   *   where: {
   *     // ... filter to delete one EventWaitlist
   *   }
   * })
   * 
   */
  delete<T extends EventWaitlistDeleteArgs>(args: Prisma.SelectSubset<T, EventWaitlistDeleteArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventWaitlist.
   * @param {EventWaitlistUpdateArgs} args - Arguments to update one EventWaitlist.
   * @example
   * // Update one EventWaitlist
   * const eventWaitlist = await prisma.eventWaitlist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventWaitlistUpdateArgs>(args: Prisma.SelectSubset<T, EventWaitlistUpdateArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventWaitlists.
   * @param {EventWaitlistDeleteManyArgs} args - Arguments to filter EventWaitlists to delete.
   * @example
   * // Delete a few EventWaitlists
   * const { count } = await prisma.eventWaitlist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventWaitlistDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventWaitlistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventWaitlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventWaitlists
   * const eventWaitlist = await prisma.eventWaitlist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventWaitlistUpdateManyArgs>(args: Prisma.SelectSubset<T, EventWaitlistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventWaitlists and returns the data updated in the database.
   * @param {EventWaitlistUpdateManyAndReturnArgs} args - Arguments to update many EventWaitlists.
   * @example
   * // Update many EventWaitlists
   * const eventWaitlist = await prisma.eventWaitlist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventWaitlists and only return the `id`
   * const eventWaitlistWithIdOnly = await prisma.eventWaitlist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventWaitlistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventWaitlistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventWaitlist.
   * @param {EventWaitlistUpsertArgs} args - Arguments to update or create a EventWaitlist.
   * @example
   * // Update or create a EventWaitlist
   * const eventWaitlist = await prisma.eventWaitlist.upsert({
   *   create: {
   *     // ... data to create a EventWaitlist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventWaitlist we want to update
   *   }
   * })
   */
  upsert<T extends EventWaitlistUpsertArgs>(args: Prisma.SelectSubset<T, EventWaitlistUpsertArgs<ExtArgs>>): Prisma.Prisma__EventWaitlistClient<runtime.Types.Result.GetResult<Prisma.$EventWaitlistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventWaitlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistCountArgs} args - Arguments to filter EventWaitlists to count.
   * @example
   * // Count the number of EventWaitlists
   * const count = await prisma.eventWaitlist.count({
   *   where: {
   *     // ... the filter for the EventWaitlists we want to count
   *   }
   * })
  **/
  count<T extends EventWaitlistCountArgs>(
    args?: Prisma.Subset<T, EventWaitlistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventWaitlistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventWaitlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventWaitlistAggregateArgs>(args: Prisma.Subset<T, EventWaitlistAggregateArgs>): Prisma.PrismaPromise<GetEventWaitlistAggregateType<T>>

  /**
   * Group by EventWaitlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventWaitlistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventWaitlistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventWaitlistGroupByArgs['orderBy'] }
      : { orderBy?: EventWaitlistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventWaitlistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventWaitlistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventWaitlist model
 */
readonly fields: EventWaitlistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventWaitlist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventWaitlistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventWaitlist model
 */
export interface EventWaitlistFieldRefs {
  readonly id: Prisma.FieldRef<"EventWaitlist", 'String'>
  readonly eventId: Prisma.FieldRef<"EventWaitlist", 'String'>
  readonly userId: Prisma.FieldRef<"EventWaitlist", 'String'>
  readonly email: Prisma.FieldRef<"EventWaitlist", 'String'>
  readonly quantity: Prisma.FieldRef<"EventWaitlist", 'Int'>
  readonly notified: Prisma.FieldRef<"EventWaitlist", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"EventWaitlist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventWaitlist findUnique
 */
export type EventWaitlistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * Filter, which EventWaitlist to fetch.
   */
  where: Prisma.EventWaitlistWhereUniqueInput
}

/**
 * EventWaitlist findUniqueOrThrow
 */
export type EventWaitlistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * Filter, which EventWaitlist to fetch.
   */
  where: Prisma.EventWaitlistWhereUniqueInput
}

/**
 * EventWaitlist findFirst
 */
export type EventWaitlistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * Filter, which EventWaitlist to fetch.
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventWaitlists to fetch.
   */
  orderBy?: Prisma.EventWaitlistOrderByWithRelationInput | Prisma.EventWaitlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventWaitlists.
   */
  cursor?: Prisma.EventWaitlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventWaitlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventWaitlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventWaitlists.
   */
  distinct?: Prisma.EventWaitlistScalarFieldEnum | Prisma.EventWaitlistScalarFieldEnum[]
}

/**
 * EventWaitlist findFirstOrThrow
 */
export type EventWaitlistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * Filter, which EventWaitlist to fetch.
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventWaitlists to fetch.
   */
  orderBy?: Prisma.EventWaitlistOrderByWithRelationInput | Prisma.EventWaitlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventWaitlists.
   */
  cursor?: Prisma.EventWaitlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventWaitlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventWaitlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventWaitlists.
   */
  distinct?: Prisma.EventWaitlistScalarFieldEnum | Prisma.EventWaitlistScalarFieldEnum[]
}

/**
 * EventWaitlist findMany
 */
export type EventWaitlistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * Filter, which EventWaitlists to fetch.
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventWaitlists to fetch.
   */
  orderBy?: Prisma.EventWaitlistOrderByWithRelationInput | Prisma.EventWaitlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventWaitlists.
   */
  cursor?: Prisma.EventWaitlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventWaitlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventWaitlists.
   */
  skip?: number
  distinct?: Prisma.EventWaitlistScalarFieldEnum | Prisma.EventWaitlistScalarFieldEnum[]
}

/**
 * EventWaitlist create
 */
export type EventWaitlistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * The data needed to create a EventWaitlist.
   */
  data: Prisma.XOR<Prisma.EventWaitlistCreateInput, Prisma.EventWaitlistUncheckedCreateInput>
}

/**
 * EventWaitlist createMany
 */
export type EventWaitlistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventWaitlists.
   */
  data: Prisma.EventWaitlistCreateManyInput | Prisma.EventWaitlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventWaitlist createManyAndReturn
 */
export type EventWaitlistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * The data used to create many EventWaitlists.
   */
  data: Prisma.EventWaitlistCreateManyInput | Prisma.EventWaitlistCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventWaitlist update
 */
export type EventWaitlistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * The data needed to update a EventWaitlist.
   */
  data: Prisma.XOR<Prisma.EventWaitlistUpdateInput, Prisma.EventWaitlistUncheckedUpdateInput>
  /**
   * Choose, which EventWaitlist to update.
   */
  where: Prisma.EventWaitlistWhereUniqueInput
}

/**
 * EventWaitlist updateMany
 */
export type EventWaitlistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventWaitlists.
   */
  data: Prisma.XOR<Prisma.EventWaitlistUpdateManyMutationInput, Prisma.EventWaitlistUncheckedUpdateManyInput>
  /**
   * Filter which EventWaitlists to update
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * Limit how many EventWaitlists to update.
   */
  limit?: number
}

/**
 * EventWaitlist updateManyAndReturn
 */
export type EventWaitlistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * The data used to update EventWaitlists.
   */
  data: Prisma.XOR<Prisma.EventWaitlistUpdateManyMutationInput, Prisma.EventWaitlistUncheckedUpdateManyInput>
  /**
   * Filter which EventWaitlists to update
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * Limit how many EventWaitlists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventWaitlist upsert
 */
export type EventWaitlistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * The filter to search for the EventWaitlist to update in case it exists.
   */
  where: Prisma.EventWaitlistWhereUniqueInput
  /**
   * In case the EventWaitlist found by the `where` argument doesn't exist, create a new EventWaitlist with this data.
   */
  create: Prisma.XOR<Prisma.EventWaitlistCreateInput, Prisma.EventWaitlistUncheckedCreateInput>
  /**
   * In case the EventWaitlist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventWaitlistUpdateInput, Prisma.EventWaitlistUncheckedUpdateInput>
}

/**
 * EventWaitlist delete
 */
export type EventWaitlistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
  /**
   * Filter which EventWaitlist to delete.
   */
  where: Prisma.EventWaitlistWhereUniqueInput
}

/**
 * EventWaitlist deleteMany
 */
export type EventWaitlistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventWaitlists to delete
   */
  where?: Prisma.EventWaitlistWhereInput
  /**
   * Limit how many EventWaitlists to delete.
   */
  limit?: number
}

/**
 * EventWaitlist without action
 */
export type EventWaitlistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventWaitlist
   */
  select?: Prisma.EventWaitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventWaitlist
   */
  omit?: Prisma.EventWaitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventWaitlistInclude<ExtArgs> | null
}
