
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MenuSection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model MenuSection
 * 
 */
export type MenuSectionModel = runtime.Types.Result.DefaultSelection<Prisma.$MenuSectionPayload>

export type AggregateMenuSection = {
  _count: MenuSectionCountAggregateOutputType | null
  _avg: MenuSectionAvgAggregateOutputType | null
  _sum: MenuSectionSumAggregateOutputType | null
  _min: MenuSectionMinAggregateOutputType | null
  _max: MenuSectionMaxAggregateOutputType | null
}

export type MenuSectionAvgAggregateOutputType = {
  displayOrder: number | null
}

export type MenuSectionSumAggregateOutputType = {
  displayOrder: number | null
}

export type MenuSectionMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  displayOrder: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MenuSectionMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  displayOrder: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MenuSectionCountAggregateOutputType = {
  id: number
  name: number
  description: number
  displayOrder: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MenuSectionAvgAggregateInputType = {
  displayOrder?: true
}

export type MenuSectionSumAggregateInputType = {
  displayOrder?: true
}

export type MenuSectionMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  displayOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type MenuSectionMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  displayOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type MenuSectionCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  displayOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MenuSectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MenuSection to aggregate.
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuSections to fetch.
   */
  orderBy?: Prisma.MenuSectionOrderByWithRelationInput | Prisma.MenuSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MenuSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MenuSections
  **/
  _count?: true | MenuSectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MenuSectionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MenuSectionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MenuSectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MenuSectionMaxAggregateInputType
}

export type GetMenuSectionAggregateType<T extends MenuSectionAggregateArgs> = {
      [P in keyof T & keyof AggregateMenuSection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMenuSection[P]>
    : Prisma.GetScalarType<T[P], AggregateMenuSection[P]>
}




export type MenuSectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MenuSectionWhereInput
  orderBy?: Prisma.MenuSectionOrderByWithAggregationInput | Prisma.MenuSectionOrderByWithAggregationInput[]
  by: Prisma.MenuSectionScalarFieldEnum[] | Prisma.MenuSectionScalarFieldEnum
  having?: Prisma.MenuSectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MenuSectionCountAggregateInputType | true
  _avg?: MenuSectionAvgAggregateInputType
  _sum?: MenuSectionSumAggregateInputType
  _min?: MenuSectionMinAggregateInputType
  _max?: MenuSectionMaxAggregateInputType
}

export type MenuSectionGroupByOutputType = {
  id: string
  name: string
  description: string | null
  displayOrder: number
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: MenuSectionCountAggregateOutputType | null
  _avg: MenuSectionAvgAggregateOutputType | null
  _sum: MenuSectionSumAggregateOutputType | null
  _min: MenuSectionMinAggregateOutputType | null
  _max: MenuSectionMaxAggregateOutputType | null
}

type GetMenuSectionGroupByPayload<T extends MenuSectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MenuSectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MenuSectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MenuSectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MenuSectionGroupByOutputType[P]>
      }
    >
  >



export type MenuSectionWhereInput = {
  AND?: Prisma.MenuSectionWhereInput | Prisma.MenuSectionWhereInput[]
  OR?: Prisma.MenuSectionWhereInput[]
  NOT?: Prisma.MenuSectionWhereInput | Prisma.MenuSectionWhereInput[]
  id?: Prisma.StringFilter<"MenuSection"> | string
  name?: Prisma.StringFilter<"MenuSection"> | string
  description?: Prisma.StringNullableFilter<"MenuSection"> | string | null
  displayOrder?: Prisma.IntFilter<"MenuSection"> | number
  active?: Prisma.BoolFilter<"MenuSection"> | boolean
  createdAt?: Prisma.DateTimeFilter<"MenuSection"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MenuSection"> | Date | string
  products?: Prisma.ProductListRelationFilter
}

export type MenuSectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
}

export type MenuSectionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MenuSectionWhereInput | Prisma.MenuSectionWhereInput[]
  OR?: Prisma.MenuSectionWhereInput[]
  NOT?: Prisma.MenuSectionWhereInput | Prisma.MenuSectionWhereInput[]
  name?: Prisma.StringFilter<"MenuSection"> | string
  description?: Prisma.StringNullableFilter<"MenuSection"> | string | null
  displayOrder?: Prisma.IntFilter<"MenuSection"> | number
  active?: Prisma.BoolFilter<"MenuSection"> | boolean
  createdAt?: Prisma.DateTimeFilter<"MenuSection"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MenuSection"> | Date | string
  products?: Prisma.ProductListRelationFilter
}, "id">

export type MenuSectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MenuSectionCountOrderByAggregateInput
  _avg?: Prisma.MenuSectionAvgOrderByAggregateInput
  _max?: Prisma.MenuSectionMaxOrderByAggregateInput
  _min?: Prisma.MenuSectionMinOrderByAggregateInput
  _sum?: Prisma.MenuSectionSumOrderByAggregateInput
}

export type MenuSectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.MenuSectionScalarWhereWithAggregatesInput | Prisma.MenuSectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.MenuSectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MenuSectionScalarWhereWithAggregatesInput | Prisma.MenuSectionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MenuSection"> | string
  name?: Prisma.StringWithAggregatesFilter<"MenuSection"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"MenuSection"> | string | null
  displayOrder?: Prisma.IntWithAggregatesFilter<"MenuSection"> | number
  active?: Prisma.BoolWithAggregatesFilter<"MenuSection"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MenuSection"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MenuSection"> | Date | string
}

export type MenuSectionCreateInput = {
  id?: string
  name: string
  description?: string | null
  displayOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutMenuSectionInput
}

export type MenuSectionUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  displayOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutMenuSectionInput
}

export type MenuSectionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutMenuSectionNestedInput
}

export type MenuSectionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutMenuSectionNestedInput
}

export type MenuSectionCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  displayOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuSectionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuSectionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuSectionNullableScalarRelationFilter = {
  is?: Prisma.MenuSectionWhereInput | null
  isNot?: Prisma.MenuSectionWhereInput | null
}

export type MenuSectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MenuSectionAvgOrderByAggregateInput = {
  displayOrder?: Prisma.SortOrder
}

export type MenuSectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MenuSectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MenuSectionSumOrderByAggregateInput = {
  displayOrder?: Prisma.SortOrder
}

export type MenuSectionCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.MenuSectionCreateWithoutProductsInput, Prisma.MenuSectionUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.MenuSectionCreateOrConnectWithoutProductsInput
  connect?: Prisma.MenuSectionWhereUniqueInput
}

export type MenuSectionUpdateOneWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.MenuSectionCreateWithoutProductsInput, Prisma.MenuSectionUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.MenuSectionCreateOrConnectWithoutProductsInput
  upsert?: Prisma.MenuSectionUpsertWithoutProductsInput
  disconnect?: Prisma.MenuSectionWhereInput | boolean
  delete?: Prisma.MenuSectionWhereInput | boolean
  connect?: Prisma.MenuSectionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MenuSectionUpdateToOneWithWhereWithoutProductsInput, Prisma.MenuSectionUpdateWithoutProductsInput>, Prisma.MenuSectionUncheckedUpdateWithoutProductsInput>
}

export type MenuSectionCreateWithoutProductsInput = {
  id?: string
  name: string
  description?: string | null
  displayOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuSectionUncheckedCreateWithoutProductsInput = {
  id?: string
  name: string
  description?: string | null
  displayOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuSectionCreateOrConnectWithoutProductsInput = {
  where: Prisma.MenuSectionWhereUniqueInput
  create: Prisma.XOR<Prisma.MenuSectionCreateWithoutProductsInput, Prisma.MenuSectionUncheckedCreateWithoutProductsInput>
}

export type MenuSectionUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.MenuSectionUpdateWithoutProductsInput, Prisma.MenuSectionUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.MenuSectionCreateWithoutProductsInput, Prisma.MenuSectionUncheckedCreateWithoutProductsInput>
  where?: Prisma.MenuSectionWhereInput
}

export type MenuSectionUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.MenuSectionWhereInput
  data: Prisma.XOR<Prisma.MenuSectionUpdateWithoutProductsInput, Prisma.MenuSectionUncheckedUpdateWithoutProductsInput>
}

export type MenuSectionUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuSectionUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MenuSectionCountOutputType
 */

export type MenuSectionCountOutputType = {
  products: number
}

export type MenuSectionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | MenuSectionCountOutputTypeCountProductsArgs
}

/**
 * MenuSectionCountOutputType without action
 */
export type MenuSectionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSectionCountOutputType
   */
  select?: Prisma.MenuSectionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MenuSectionCountOutputType without action
 */
export type MenuSectionCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type MenuSectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  displayOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  products?: boolean | Prisma.MenuSection$productsArgs<ExtArgs>
  _count?: boolean | Prisma.MenuSectionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["menuSection"]>

export type MenuSectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  displayOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["menuSection"]>

export type MenuSectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  displayOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["menuSection"]>

export type MenuSectionSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  displayOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MenuSectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "displayOrder" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["menuSection"]>
export type MenuSectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.MenuSection$productsArgs<ExtArgs>
  _count?: boolean | Prisma.MenuSectionCountOutputTypeDefaultArgs<ExtArgs>
}
export type MenuSectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MenuSectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MenuSectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MenuSection"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    displayOrder: number
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["menuSection"]>
  composites: {}
}

export type MenuSectionGetPayload<S extends boolean | null | undefined | MenuSectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload, S>

export type MenuSectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MenuSectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MenuSectionCountAggregateInputType | true
  }

export interface MenuSectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MenuSection'], meta: { name: 'MenuSection' } }
  /**
   * Find zero or one MenuSection that matches the filter.
   * @param {MenuSectionFindUniqueArgs} args - Arguments to find a MenuSection
   * @example
   * // Get one MenuSection
   * const menuSection = await prisma.menuSection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MenuSectionFindUniqueArgs>(args: Prisma.SelectSubset<T, MenuSectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MenuSection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MenuSectionFindUniqueOrThrowArgs} args - Arguments to find a MenuSection
   * @example
   * // Get one MenuSection
   * const menuSection = await prisma.menuSection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MenuSectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MenuSectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MenuSection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionFindFirstArgs} args - Arguments to find a MenuSection
   * @example
   * // Get one MenuSection
   * const menuSection = await prisma.menuSection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MenuSectionFindFirstArgs>(args?: Prisma.SelectSubset<T, MenuSectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MenuSection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionFindFirstOrThrowArgs} args - Arguments to find a MenuSection
   * @example
   * // Get one MenuSection
   * const menuSection = await prisma.menuSection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MenuSectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MenuSectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MenuSections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MenuSections
   * const menuSections = await prisma.menuSection.findMany()
   * 
   * // Get first 10 MenuSections
   * const menuSections = await prisma.menuSection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const menuSectionWithIdOnly = await prisma.menuSection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MenuSectionFindManyArgs>(args?: Prisma.SelectSubset<T, MenuSectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MenuSection.
   * @param {MenuSectionCreateArgs} args - Arguments to create a MenuSection.
   * @example
   * // Create one MenuSection
   * const MenuSection = await prisma.menuSection.create({
   *   data: {
   *     // ... data to create a MenuSection
   *   }
   * })
   * 
   */
  create<T extends MenuSectionCreateArgs>(args: Prisma.SelectSubset<T, MenuSectionCreateArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MenuSections.
   * @param {MenuSectionCreateManyArgs} args - Arguments to create many MenuSections.
   * @example
   * // Create many MenuSections
   * const menuSection = await prisma.menuSection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MenuSectionCreateManyArgs>(args?: Prisma.SelectSubset<T, MenuSectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MenuSections and returns the data saved in the database.
   * @param {MenuSectionCreateManyAndReturnArgs} args - Arguments to create many MenuSections.
   * @example
   * // Create many MenuSections
   * const menuSection = await prisma.menuSection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MenuSections and only return the `id`
   * const menuSectionWithIdOnly = await prisma.menuSection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MenuSectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MenuSectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MenuSection.
   * @param {MenuSectionDeleteArgs} args - Arguments to delete one MenuSection.
   * @example
   * // Delete one MenuSection
   * const MenuSection = await prisma.menuSection.delete({
   *   where: {
   *     // ... filter to delete one MenuSection
   *   }
   * })
   * 
   */
  delete<T extends MenuSectionDeleteArgs>(args: Prisma.SelectSubset<T, MenuSectionDeleteArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MenuSection.
   * @param {MenuSectionUpdateArgs} args - Arguments to update one MenuSection.
   * @example
   * // Update one MenuSection
   * const menuSection = await prisma.menuSection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MenuSectionUpdateArgs>(args: Prisma.SelectSubset<T, MenuSectionUpdateArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MenuSections.
   * @param {MenuSectionDeleteManyArgs} args - Arguments to filter MenuSections to delete.
   * @example
   * // Delete a few MenuSections
   * const { count } = await prisma.menuSection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MenuSectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, MenuSectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MenuSections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MenuSections
   * const menuSection = await prisma.menuSection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MenuSectionUpdateManyArgs>(args: Prisma.SelectSubset<T, MenuSectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MenuSections and returns the data updated in the database.
   * @param {MenuSectionUpdateManyAndReturnArgs} args - Arguments to update many MenuSections.
   * @example
   * // Update many MenuSections
   * const menuSection = await prisma.menuSection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MenuSections and only return the `id`
   * const menuSectionWithIdOnly = await prisma.menuSection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MenuSectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MenuSectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MenuSection.
   * @param {MenuSectionUpsertArgs} args - Arguments to update or create a MenuSection.
   * @example
   * // Update or create a MenuSection
   * const menuSection = await prisma.menuSection.upsert({
   *   create: {
   *     // ... data to create a MenuSection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MenuSection we want to update
   *   }
   * })
   */
  upsert<T extends MenuSectionUpsertArgs>(args: Prisma.SelectSubset<T, MenuSectionUpsertArgs<ExtArgs>>): Prisma.Prisma__MenuSectionClient<runtime.Types.Result.GetResult<Prisma.$MenuSectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MenuSections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionCountArgs} args - Arguments to filter MenuSections to count.
   * @example
   * // Count the number of MenuSections
   * const count = await prisma.menuSection.count({
   *   where: {
   *     // ... the filter for the MenuSections we want to count
   *   }
   * })
  **/
  count<T extends MenuSectionCountArgs>(
    args?: Prisma.Subset<T, MenuSectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MenuSectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MenuSection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MenuSectionAggregateArgs>(args: Prisma.Subset<T, MenuSectionAggregateArgs>): Prisma.PrismaPromise<GetMenuSectionAggregateType<T>>

  /**
   * Group by MenuSection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuSectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MenuSectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MenuSectionGroupByArgs['orderBy'] }
      : { orderBy?: MenuSectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MenuSectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMenuSectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MenuSection model
 */
readonly fields: MenuSectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MenuSection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MenuSectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.MenuSection$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MenuSection$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MenuSection model
 */
export interface MenuSectionFieldRefs {
  readonly id: Prisma.FieldRef<"MenuSection", 'String'>
  readonly name: Prisma.FieldRef<"MenuSection", 'String'>
  readonly description: Prisma.FieldRef<"MenuSection", 'String'>
  readonly displayOrder: Prisma.FieldRef<"MenuSection", 'Int'>
  readonly active: Prisma.FieldRef<"MenuSection", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"MenuSection", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MenuSection", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MenuSection findUnique
 */
export type MenuSectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * Filter, which MenuSection to fetch.
   */
  where: Prisma.MenuSectionWhereUniqueInput
}

/**
 * MenuSection findUniqueOrThrow
 */
export type MenuSectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * Filter, which MenuSection to fetch.
   */
  where: Prisma.MenuSectionWhereUniqueInput
}

/**
 * MenuSection findFirst
 */
export type MenuSectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * Filter, which MenuSection to fetch.
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuSections to fetch.
   */
  orderBy?: Prisma.MenuSectionOrderByWithRelationInput | Prisma.MenuSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MenuSections.
   */
  cursor?: Prisma.MenuSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MenuSections.
   */
  distinct?: Prisma.MenuSectionScalarFieldEnum | Prisma.MenuSectionScalarFieldEnum[]
}

/**
 * MenuSection findFirstOrThrow
 */
export type MenuSectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * Filter, which MenuSection to fetch.
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuSections to fetch.
   */
  orderBy?: Prisma.MenuSectionOrderByWithRelationInput | Prisma.MenuSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MenuSections.
   */
  cursor?: Prisma.MenuSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MenuSections.
   */
  distinct?: Prisma.MenuSectionScalarFieldEnum | Prisma.MenuSectionScalarFieldEnum[]
}

/**
 * MenuSection findMany
 */
export type MenuSectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * Filter, which MenuSections to fetch.
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuSections to fetch.
   */
  orderBy?: Prisma.MenuSectionOrderByWithRelationInput | Prisma.MenuSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MenuSections.
   */
  cursor?: Prisma.MenuSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuSections.
   */
  skip?: number
  distinct?: Prisma.MenuSectionScalarFieldEnum | Prisma.MenuSectionScalarFieldEnum[]
}

/**
 * MenuSection create
 */
export type MenuSectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * The data needed to create a MenuSection.
   */
  data: Prisma.XOR<Prisma.MenuSectionCreateInput, Prisma.MenuSectionUncheckedCreateInput>
}

/**
 * MenuSection createMany
 */
export type MenuSectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MenuSections.
   */
  data: Prisma.MenuSectionCreateManyInput | Prisma.MenuSectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MenuSection createManyAndReturn
 */
export type MenuSectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * The data used to create many MenuSections.
   */
  data: Prisma.MenuSectionCreateManyInput | Prisma.MenuSectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MenuSection update
 */
export type MenuSectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * The data needed to update a MenuSection.
   */
  data: Prisma.XOR<Prisma.MenuSectionUpdateInput, Prisma.MenuSectionUncheckedUpdateInput>
  /**
   * Choose, which MenuSection to update.
   */
  where: Prisma.MenuSectionWhereUniqueInput
}

/**
 * MenuSection updateMany
 */
export type MenuSectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MenuSections.
   */
  data: Prisma.XOR<Prisma.MenuSectionUpdateManyMutationInput, Prisma.MenuSectionUncheckedUpdateManyInput>
  /**
   * Filter which MenuSections to update
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * Limit how many MenuSections to update.
   */
  limit?: number
}

/**
 * MenuSection updateManyAndReturn
 */
export type MenuSectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * The data used to update MenuSections.
   */
  data: Prisma.XOR<Prisma.MenuSectionUpdateManyMutationInput, Prisma.MenuSectionUncheckedUpdateManyInput>
  /**
   * Filter which MenuSections to update
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * Limit how many MenuSections to update.
   */
  limit?: number
}

/**
 * MenuSection upsert
 */
export type MenuSectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * The filter to search for the MenuSection to update in case it exists.
   */
  where: Prisma.MenuSectionWhereUniqueInput
  /**
   * In case the MenuSection found by the `where` argument doesn't exist, create a new MenuSection with this data.
   */
  create: Prisma.XOR<Prisma.MenuSectionCreateInput, Prisma.MenuSectionUncheckedCreateInput>
  /**
   * In case the MenuSection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MenuSectionUpdateInput, Prisma.MenuSectionUncheckedUpdateInput>
}

/**
 * MenuSection delete
 */
export type MenuSectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
  /**
   * Filter which MenuSection to delete.
   */
  where: Prisma.MenuSectionWhereUniqueInput
}

/**
 * MenuSection deleteMany
 */
export type MenuSectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MenuSections to delete
   */
  where?: Prisma.MenuSectionWhereInput
  /**
   * Limit how many MenuSections to delete.
   */
  limit?: number
}

/**
 * MenuSection.products
 */
export type MenuSection$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * MenuSection without action
 */
export type MenuSectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuSection
   */
  select?: Prisma.MenuSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuSection
   */
  omit?: Prisma.MenuSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuSectionInclude<ExtArgs> | null
}
