
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductAllergen` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ProductAllergen
 * 
 */
export type ProductAllergenModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductAllergenPayload>

export type AggregateProductAllergen = {
  _count: ProductAllergenCountAggregateOutputType | null
  _min: ProductAllergenMinAggregateOutputType | null
  _max: ProductAllergenMaxAggregateOutputType | null
}

export type ProductAllergenMinAggregateOutputType = {
  id: string | null
  productId: string | null
  allergenType: string | null
  allergen: string | null
  severity: string | null
  createdAt: Date | null
}

export type ProductAllergenMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  allergenType: string | null
  allergen: string | null
  severity: string | null
  createdAt: Date | null
}

export type ProductAllergenCountAggregateOutputType = {
  id: number
  productId: number
  allergenType: number
  allergen: number
  severity: number
  createdAt: number
  _all: number
}


export type ProductAllergenMinAggregateInputType = {
  id?: true
  productId?: true
  allergenType?: true
  allergen?: true
  severity?: true
  createdAt?: true
}

export type ProductAllergenMaxAggregateInputType = {
  id?: true
  productId?: true
  allergenType?: true
  allergen?: true
  severity?: true
  createdAt?: true
}

export type ProductAllergenCountAggregateInputType = {
  id?: true
  productId?: true
  allergenType?: true
  allergen?: true
  severity?: true
  createdAt?: true
  _all?: true
}

export type ProductAllergenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductAllergen to aggregate.
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductAllergens to fetch.
   */
  orderBy?: Prisma.ProductAllergenOrderByWithRelationInput | Prisma.ProductAllergenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductAllergenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductAllergens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductAllergens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductAllergens
  **/
  _count?: true | ProductAllergenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductAllergenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductAllergenMaxAggregateInputType
}

export type GetProductAllergenAggregateType<T extends ProductAllergenAggregateArgs> = {
      [P in keyof T & keyof AggregateProductAllergen]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductAllergen[P]>
    : Prisma.GetScalarType<T[P], AggregateProductAllergen[P]>
}




export type ProductAllergenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductAllergenWhereInput
  orderBy?: Prisma.ProductAllergenOrderByWithAggregationInput | Prisma.ProductAllergenOrderByWithAggregationInput[]
  by: Prisma.ProductAllergenScalarFieldEnum[] | Prisma.ProductAllergenScalarFieldEnum
  having?: Prisma.ProductAllergenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductAllergenCountAggregateInputType | true
  _min?: ProductAllergenMinAggregateInputType
  _max?: ProductAllergenMaxAggregateInputType
}

export type ProductAllergenGroupByOutputType = {
  id: string
  productId: string
  allergenType: string
  allergen: string
  severity: string
  createdAt: Date
  _count: ProductAllergenCountAggregateOutputType | null
  _min: ProductAllergenMinAggregateOutputType | null
  _max: ProductAllergenMaxAggregateOutputType | null
}

type GetProductAllergenGroupByPayload<T extends ProductAllergenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductAllergenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductAllergenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductAllergenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductAllergenGroupByOutputType[P]>
      }
    >
  >



export type ProductAllergenWhereInput = {
  AND?: Prisma.ProductAllergenWhereInput | Prisma.ProductAllergenWhereInput[]
  OR?: Prisma.ProductAllergenWhereInput[]
  NOT?: Prisma.ProductAllergenWhereInput | Prisma.ProductAllergenWhereInput[]
  id?: Prisma.StringFilter<"ProductAllergen"> | string
  productId?: Prisma.StringFilter<"ProductAllergen"> | string
  allergenType?: Prisma.StringFilter<"ProductAllergen"> | string
  allergen?: Prisma.StringFilter<"ProductAllergen"> | string
  severity?: Prisma.StringFilter<"ProductAllergen"> | string
  createdAt?: Prisma.DateTimeFilter<"ProductAllergen"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductAllergenOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  allergenType?: Prisma.SortOrder
  allergen?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ProductAllergenWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  productId_allergenType?: Prisma.ProductAllergenProductIdAllergenTypeCompoundUniqueInput
  AND?: Prisma.ProductAllergenWhereInput | Prisma.ProductAllergenWhereInput[]
  OR?: Prisma.ProductAllergenWhereInput[]
  NOT?: Prisma.ProductAllergenWhereInput | Prisma.ProductAllergenWhereInput[]
  productId?: Prisma.StringFilter<"ProductAllergen"> | string
  allergenType?: Prisma.StringFilter<"ProductAllergen"> | string
  allergen?: Prisma.StringFilter<"ProductAllergen"> | string
  severity?: Prisma.StringFilter<"ProductAllergen"> | string
  createdAt?: Prisma.DateTimeFilter<"ProductAllergen"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "productId_allergenType">

export type ProductAllergenOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  allergenType?: Prisma.SortOrder
  allergen?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ProductAllergenCountOrderByAggregateInput
  _max?: Prisma.ProductAllergenMaxOrderByAggregateInput
  _min?: Prisma.ProductAllergenMinOrderByAggregateInput
}

export type ProductAllergenScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductAllergenScalarWhereWithAggregatesInput | Prisma.ProductAllergenScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductAllergenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductAllergenScalarWhereWithAggregatesInput | Prisma.ProductAllergenScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductAllergen"> | string
  productId?: Prisma.StringWithAggregatesFilter<"ProductAllergen"> | string
  allergenType?: Prisma.StringWithAggregatesFilter<"ProductAllergen"> | string
  allergen?: Prisma.StringWithAggregatesFilter<"ProductAllergen"> | string
  severity?: Prisma.StringWithAggregatesFilter<"ProductAllergen"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProductAllergen"> | Date | string
}

export type ProductAllergenCreateInput = {
  id?: string
  allergenType: string
  allergen: string
  severity?: string
  createdAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutAllergenWarningsInput
}

export type ProductAllergenUncheckedCreateInput = {
  id?: string
  productId: string
  allergenType: string
  allergen: string
  severity?: string
  createdAt?: Date | string
}

export type ProductAllergenUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutAllergenWarningsNestedInput
}

export type ProductAllergenUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductAllergenCreateManyInput = {
  id?: string
  productId: string
  allergenType: string
  allergen: string
  severity?: string
  createdAt?: Date | string
}

export type ProductAllergenUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductAllergenUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductAllergenListRelationFilter = {
  every?: Prisma.ProductAllergenWhereInput
  some?: Prisma.ProductAllergenWhereInput
  none?: Prisma.ProductAllergenWhereInput
}

export type ProductAllergenOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductAllergenProductIdAllergenTypeCompoundUniqueInput = {
  productId: string
  allergenType: string
}

export type ProductAllergenCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  allergenType?: Prisma.SortOrder
  allergen?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductAllergenMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  allergenType?: Prisma.SortOrder
  allergen?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductAllergenMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  allergenType?: Prisma.SortOrder
  allergen?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProductAllergenCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductAllergenCreateWithoutProductInput, Prisma.ProductAllergenUncheckedCreateWithoutProductInput> | Prisma.ProductAllergenCreateWithoutProductInput[] | Prisma.ProductAllergenUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductAllergenCreateOrConnectWithoutProductInput | Prisma.ProductAllergenCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductAllergenCreateManyProductInputEnvelope
  connect?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
}

export type ProductAllergenUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductAllergenCreateWithoutProductInput, Prisma.ProductAllergenUncheckedCreateWithoutProductInput> | Prisma.ProductAllergenCreateWithoutProductInput[] | Prisma.ProductAllergenUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductAllergenCreateOrConnectWithoutProductInput | Prisma.ProductAllergenCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductAllergenCreateManyProductInputEnvelope
  connect?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
}

export type ProductAllergenUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductAllergenCreateWithoutProductInput, Prisma.ProductAllergenUncheckedCreateWithoutProductInput> | Prisma.ProductAllergenCreateWithoutProductInput[] | Prisma.ProductAllergenUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductAllergenCreateOrConnectWithoutProductInput | Prisma.ProductAllergenCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductAllergenUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductAllergenUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductAllergenCreateManyProductInputEnvelope
  set?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  disconnect?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  delete?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  connect?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  update?: Prisma.ProductAllergenUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductAllergenUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductAllergenUpdateManyWithWhereWithoutProductInput | Prisma.ProductAllergenUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductAllergenScalarWhereInput | Prisma.ProductAllergenScalarWhereInput[]
}

export type ProductAllergenUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductAllergenCreateWithoutProductInput, Prisma.ProductAllergenUncheckedCreateWithoutProductInput> | Prisma.ProductAllergenCreateWithoutProductInput[] | Prisma.ProductAllergenUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductAllergenCreateOrConnectWithoutProductInput | Prisma.ProductAllergenCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductAllergenUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductAllergenUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductAllergenCreateManyProductInputEnvelope
  set?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  disconnect?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  delete?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  connect?: Prisma.ProductAllergenWhereUniqueInput | Prisma.ProductAllergenWhereUniqueInput[]
  update?: Prisma.ProductAllergenUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductAllergenUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductAllergenUpdateManyWithWhereWithoutProductInput | Prisma.ProductAllergenUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductAllergenScalarWhereInput | Prisma.ProductAllergenScalarWhereInput[]
}

export type ProductAllergenCreateWithoutProductInput = {
  id?: string
  allergenType: string
  allergen: string
  severity?: string
  createdAt?: Date | string
}

export type ProductAllergenUncheckedCreateWithoutProductInput = {
  id?: string
  allergenType: string
  allergen: string
  severity?: string
  createdAt?: Date | string
}

export type ProductAllergenCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductAllergenWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductAllergenCreateWithoutProductInput, Prisma.ProductAllergenUncheckedCreateWithoutProductInput>
}

export type ProductAllergenCreateManyProductInputEnvelope = {
  data: Prisma.ProductAllergenCreateManyProductInput | Prisma.ProductAllergenCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type ProductAllergenUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductAllergenWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductAllergenUpdateWithoutProductInput, Prisma.ProductAllergenUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductAllergenCreateWithoutProductInput, Prisma.ProductAllergenUncheckedCreateWithoutProductInput>
}

export type ProductAllergenUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductAllergenWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductAllergenUpdateWithoutProductInput, Prisma.ProductAllergenUncheckedUpdateWithoutProductInput>
}

export type ProductAllergenUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductAllergenScalarWhereInput
  data: Prisma.XOR<Prisma.ProductAllergenUpdateManyMutationInput, Prisma.ProductAllergenUncheckedUpdateManyWithoutProductInput>
}

export type ProductAllergenScalarWhereInput = {
  AND?: Prisma.ProductAllergenScalarWhereInput | Prisma.ProductAllergenScalarWhereInput[]
  OR?: Prisma.ProductAllergenScalarWhereInput[]
  NOT?: Prisma.ProductAllergenScalarWhereInput | Prisma.ProductAllergenScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductAllergen"> | string
  productId?: Prisma.StringFilter<"ProductAllergen"> | string
  allergenType?: Prisma.StringFilter<"ProductAllergen"> | string
  allergen?: Prisma.StringFilter<"ProductAllergen"> | string
  severity?: Prisma.StringFilter<"ProductAllergen"> | string
  createdAt?: Prisma.DateTimeFilter<"ProductAllergen"> | Date | string
}

export type ProductAllergenCreateManyProductInput = {
  id?: string
  allergenType: string
  allergen: string
  severity?: string
  createdAt?: Date | string
}

export type ProductAllergenUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductAllergenUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductAllergenUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  allergenType?: Prisma.StringFieldUpdateOperationsInput | string
  allergen?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProductAllergenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  allergenType?: boolean
  allergen?: boolean
  severity?: boolean
  createdAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productAllergen"]>

export type ProductAllergenSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  allergenType?: boolean
  allergen?: boolean
  severity?: boolean
  createdAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productAllergen"]>

export type ProductAllergenSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  allergenType?: boolean
  allergen?: boolean
  severity?: boolean
  createdAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productAllergen"]>

export type ProductAllergenSelectScalar = {
  id?: boolean
  productId?: boolean
  allergenType?: boolean
  allergen?: boolean
  severity?: boolean
  createdAt?: boolean
}

export type ProductAllergenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "allergenType" | "allergen" | "severity" | "createdAt", ExtArgs["result"]["productAllergen"]>
export type ProductAllergenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductAllergenIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductAllergenIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductAllergenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductAllergen"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    allergenType: string
    allergen: string
    severity: string
    createdAt: Date
  }, ExtArgs["result"]["productAllergen"]>
  composites: {}
}

export type ProductAllergenGetPayload<S extends boolean | null | undefined | ProductAllergenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload, S>

export type ProductAllergenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductAllergenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductAllergenCountAggregateInputType | true
  }

export interface ProductAllergenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductAllergen'], meta: { name: 'ProductAllergen' } }
  /**
   * Find zero or one ProductAllergen that matches the filter.
   * @param {ProductAllergenFindUniqueArgs} args - Arguments to find a ProductAllergen
   * @example
   * // Get one ProductAllergen
   * const productAllergen = await prisma.productAllergen.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductAllergenFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductAllergenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductAllergen that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductAllergenFindUniqueOrThrowArgs} args - Arguments to find a ProductAllergen
   * @example
   * // Get one ProductAllergen
   * const productAllergen = await prisma.productAllergen.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductAllergenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductAllergenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductAllergen that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenFindFirstArgs} args - Arguments to find a ProductAllergen
   * @example
   * // Get one ProductAllergen
   * const productAllergen = await prisma.productAllergen.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductAllergenFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductAllergenFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductAllergen that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenFindFirstOrThrowArgs} args - Arguments to find a ProductAllergen
   * @example
   * // Get one ProductAllergen
   * const productAllergen = await prisma.productAllergen.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductAllergenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductAllergenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductAllergens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductAllergens
   * const productAllergens = await prisma.productAllergen.findMany()
   * 
   * // Get first 10 ProductAllergens
   * const productAllergens = await prisma.productAllergen.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productAllergenWithIdOnly = await prisma.productAllergen.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductAllergenFindManyArgs>(args?: Prisma.SelectSubset<T, ProductAllergenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductAllergen.
   * @param {ProductAllergenCreateArgs} args - Arguments to create a ProductAllergen.
   * @example
   * // Create one ProductAllergen
   * const ProductAllergen = await prisma.productAllergen.create({
   *   data: {
   *     // ... data to create a ProductAllergen
   *   }
   * })
   * 
   */
  create<T extends ProductAllergenCreateArgs>(args: Prisma.SelectSubset<T, ProductAllergenCreateArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductAllergens.
   * @param {ProductAllergenCreateManyArgs} args - Arguments to create many ProductAllergens.
   * @example
   * // Create many ProductAllergens
   * const productAllergen = await prisma.productAllergen.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductAllergenCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductAllergenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductAllergens and returns the data saved in the database.
   * @param {ProductAllergenCreateManyAndReturnArgs} args - Arguments to create many ProductAllergens.
   * @example
   * // Create many ProductAllergens
   * const productAllergen = await prisma.productAllergen.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductAllergens and only return the `id`
   * const productAllergenWithIdOnly = await prisma.productAllergen.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductAllergenCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductAllergenCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductAllergen.
   * @param {ProductAllergenDeleteArgs} args - Arguments to delete one ProductAllergen.
   * @example
   * // Delete one ProductAllergen
   * const ProductAllergen = await prisma.productAllergen.delete({
   *   where: {
   *     // ... filter to delete one ProductAllergen
   *   }
   * })
   * 
   */
  delete<T extends ProductAllergenDeleteArgs>(args: Prisma.SelectSubset<T, ProductAllergenDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductAllergen.
   * @param {ProductAllergenUpdateArgs} args - Arguments to update one ProductAllergen.
   * @example
   * // Update one ProductAllergen
   * const productAllergen = await prisma.productAllergen.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductAllergenUpdateArgs>(args: Prisma.SelectSubset<T, ProductAllergenUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductAllergens.
   * @param {ProductAllergenDeleteManyArgs} args - Arguments to filter ProductAllergens to delete.
   * @example
   * // Delete a few ProductAllergens
   * const { count } = await prisma.productAllergen.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductAllergenDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductAllergenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductAllergens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductAllergens
   * const productAllergen = await prisma.productAllergen.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductAllergenUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductAllergenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductAllergens and returns the data updated in the database.
   * @param {ProductAllergenUpdateManyAndReturnArgs} args - Arguments to update many ProductAllergens.
   * @example
   * // Update many ProductAllergens
   * const productAllergen = await prisma.productAllergen.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductAllergens and only return the `id`
   * const productAllergenWithIdOnly = await prisma.productAllergen.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductAllergenUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductAllergenUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductAllergen.
   * @param {ProductAllergenUpsertArgs} args - Arguments to update or create a ProductAllergen.
   * @example
   * // Update or create a ProductAllergen
   * const productAllergen = await prisma.productAllergen.upsert({
   *   create: {
   *     // ... data to create a ProductAllergen
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductAllergen we want to update
   *   }
   * })
   */
  upsert<T extends ProductAllergenUpsertArgs>(args: Prisma.SelectSubset<T, ProductAllergenUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductAllergenClient<runtime.Types.Result.GetResult<Prisma.$ProductAllergenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductAllergens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenCountArgs} args - Arguments to filter ProductAllergens to count.
   * @example
   * // Count the number of ProductAllergens
   * const count = await prisma.productAllergen.count({
   *   where: {
   *     // ... the filter for the ProductAllergens we want to count
   *   }
   * })
  **/
  count<T extends ProductAllergenCountArgs>(
    args?: Prisma.Subset<T, ProductAllergenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductAllergenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductAllergen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductAllergenAggregateArgs>(args: Prisma.Subset<T, ProductAllergenAggregateArgs>): Prisma.PrismaPromise<GetProductAllergenAggregateType<T>>

  /**
   * Group by ProductAllergen.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAllergenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductAllergenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductAllergenGroupByArgs['orderBy'] }
      : { orderBy?: ProductAllergenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductAllergenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductAllergenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductAllergen model
 */
readonly fields: ProductAllergenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductAllergen.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductAllergenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductAllergen model
 */
export interface ProductAllergenFieldRefs {
  readonly id: Prisma.FieldRef<"ProductAllergen", 'String'>
  readonly productId: Prisma.FieldRef<"ProductAllergen", 'String'>
  readonly allergenType: Prisma.FieldRef<"ProductAllergen", 'String'>
  readonly allergen: Prisma.FieldRef<"ProductAllergen", 'String'>
  readonly severity: Prisma.FieldRef<"ProductAllergen", 'String'>
  readonly createdAt: Prisma.FieldRef<"ProductAllergen", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProductAllergen findUnique
 */
export type ProductAllergenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * Filter, which ProductAllergen to fetch.
   */
  where: Prisma.ProductAllergenWhereUniqueInput
}

/**
 * ProductAllergen findUniqueOrThrow
 */
export type ProductAllergenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * Filter, which ProductAllergen to fetch.
   */
  where: Prisma.ProductAllergenWhereUniqueInput
}

/**
 * ProductAllergen findFirst
 */
export type ProductAllergenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * Filter, which ProductAllergen to fetch.
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductAllergens to fetch.
   */
  orderBy?: Prisma.ProductAllergenOrderByWithRelationInput | Prisma.ProductAllergenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductAllergens.
   */
  cursor?: Prisma.ProductAllergenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductAllergens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductAllergens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductAllergens.
   */
  distinct?: Prisma.ProductAllergenScalarFieldEnum | Prisma.ProductAllergenScalarFieldEnum[]
}

/**
 * ProductAllergen findFirstOrThrow
 */
export type ProductAllergenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * Filter, which ProductAllergen to fetch.
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductAllergens to fetch.
   */
  orderBy?: Prisma.ProductAllergenOrderByWithRelationInput | Prisma.ProductAllergenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductAllergens.
   */
  cursor?: Prisma.ProductAllergenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductAllergens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductAllergens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductAllergens.
   */
  distinct?: Prisma.ProductAllergenScalarFieldEnum | Prisma.ProductAllergenScalarFieldEnum[]
}

/**
 * ProductAllergen findMany
 */
export type ProductAllergenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * Filter, which ProductAllergens to fetch.
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductAllergens to fetch.
   */
  orderBy?: Prisma.ProductAllergenOrderByWithRelationInput | Prisma.ProductAllergenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductAllergens.
   */
  cursor?: Prisma.ProductAllergenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductAllergens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductAllergens.
   */
  skip?: number
  distinct?: Prisma.ProductAllergenScalarFieldEnum | Prisma.ProductAllergenScalarFieldEnum[]
}

/**
 * ProductAllergen create
 */
export type ProductAllergenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductAllergen.
   */
  data: Prisma.XOR<Prisma.ProductAllergenCreateInput, Prisma.ProductAllergenUncheckedCreateInput>
}

/**
 * ProductAllergen createMany
 */
export type ProductAllergenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductAllergens.
   */
  data: Prisma.ProductAllergenCreateManyInput | Prisma.ProductAllergenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductAllergen createManyAndReturn
 */
export type ProductAllergenCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * The data used to create many ProductAllergens.
   */
  data: Prisma.ProductAllergenCreateManyInput | Prisma.ProductAllergenCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductAllergen update
 */
export type ProductAllergenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductAllergen.
   */
  data: Prisma.XOR<Prisma.ProductAllergenUpdateInput, Prisma.ProductAllergenUncheckedUpdateInput>
  /**
   * Choose, which ProductAllergen to update.
   */
  where: Prisma.ProductAllergenWhereUniqueInput
}

/**
 * ProductAllergen updateMany
 */
export type ProductAllergenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductAllergens.
   */
  data: Prisma.XOR<Prisma.ProductAllergenUpdateManyMutationInput, Prisma.ProductAllergenUncheckedUpdateManyInput>
  /**
   * Filter which ProductAllergens to update
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * Limit how many ProductAllergens to update.
   */
  limit?: number
}

/**
 * ProductAllergen updateManyAndReturn
 */
export type ProductAllergenUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * The data used to update ProductAllergens.
   */
  data: Prisma.XOR<Prisma.ProductAllergenUpdateManyMutationInput, Prisma.ProductAllergenUncheckedUpdateManyInput>
  /**
   * Filter which ProductAllergens to update
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * Limit how many ProductAllergens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductAllergen upsert
 */
export type ProductAllergenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductAllergen to update in case it exists.
   */
  where: Prisma.ProductAllergenWhereUniqueInput
  /**
   * In case the ProductAllergen found by the `where` argument doesn't exist, create a new ProductAllergen with this data.
   */
  create: Prisma.XOR<Prisma.ProductAllergenCreateInput, Prisma.ProductAllergenUncheckedCreateInput>
  /**
   * In case the ProductAllergen was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductAllergenUpdateInput, Prisma.ProductAllergenUncheckedUpdateInput>
}

/**
 * ProductAllergen delete
 */
export type ProductAllergenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
  /**
   * Filter which ProductAllergen to delete.
   */
  where: Prisma.ProductAllergenWhereUniqueInput
}

/**
 * ProductAllergen deleteMany
 */
export type ProductAllergenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductAllergens to delete
   */
  where?: Prisma.ProductAllergenWhereInput
  /**
   * Limit how many ProductAllergens to delete.
   */
  limit?: number
}

/**
 * ProductAllergen without action
 */
export type ProductAllergenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductAllergen
   */
  select?: Prisma.ProductAllergenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductAllergen
   */
  omit?: Prisma.ProductAllergenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductAllergenInclude<ExtArgs> | null
}
