
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SubscriptionChange` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SubscriptionChange
 * 
 */
export type SubscriptionChangeModel = runtime.Types.Result.DefaultSelection<Prisma.$SubscriptionChangePayload>

export type AggregateSubscriptionChange = {
  _count: SubscriptionChangeCountAggregateOutputType | null
  _min: SubscriptionChangeMinAggregateOutputType | null
  _max: SubscriptionChangeMaxAggregateOutputType | null
}

export type SubscriptionChangeMinAggregateOutputType = {
  id: string | null
  subscriptionId: string | null
  changeType: string | null
  effectiveDate: Date | null
  createdAt: Date | null
}

export type SubscriptionChangeMaxAggregateOutputType = {
  id: string | null
  subscriptionId: string | null
  changeType: string | null
  effectiveDate: Date | null
  createdAt: Date | null
}

export type SubscriptionChangeCountAggregateOutputType = {
  id: number
  subscriptionId: number
  changeType: number
  oldValue: number
  newValue: number
  effectiveDate: number
  createdAt: number
  _all: number
}


export type SubscriptionChangeMinAggregateInputType = {
  id?: true
  subscriptionId?: true
  changeType?: true
  effectiveDate?: true
  createdAt?: true
}

export type SubscriptionChangeMaxAggregateInputType = {
  id?: true
  subscriptionId?: true
  changeType?: true
  effectiveDate?: true
  createdAt?: true
}

export type SubscriptionChangeCountAggregateInputType = {
  id?: true
  subscriptionId?: true
  changeType?: true
  oldValue?: true
  newValue?: true
  effectiveDate?: true
  createdAt?: true
  _all?: true
}

export type SubscriptionChangeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubscriptionChange to aggregate.
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubscriptionChanges to fetch.
   */
  orderBy?: Prisma.SubscriptionChangeOrderByWithRelationInput | Prisma.SubscriptionChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubscriptionChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubscriptionChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubscriptionChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SubscriptionChanges
  **/
  _count?: true | SubscriptionChangeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubscriptionChangeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubscriptionChangeMaxAggregateInputType
}

export type GetSubscriptionChangeAggregateType<T extends SubscriptionChangeAggregateArgs> = {
      [P in keyof T & keyof AggregateSubscriptionChange]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubscriptionChange[P]>
    : Prisma.GetScalarType<T[P], AggregateSubscriptionChange[P]>
}




export type SubscriptionChangeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubscriptionChangeWhereInput
  orderBy?: Prisma.SubscriptionChangeOrderByWithAggregationInput | Prisma.SubscriptionChangeOrderByWithAggregationInput[]
  by: Prisma.SubscriptionChangeScalarFieldEnum[] | Prisma.SubscriptionChangeScalarFieldEnum
  having?: Prisma.SubscriptionChangeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubscriptionChangeCountAggregateInputType | true
  _min?: SubscriptionChangeMinAggregateInputType
  _max?: SubscriptionChangeMaxAggregateInputType
}

export type SubscriptionChangeGroupByOutputType = {
  id: string
  subscriptionId: string
  changeType: string
  oldValue: runtime.JsonValue | null
  newValue: runtime.JsonValue | null
  effectiveDate: Date
  createdAt: Date
  _count: SubscriptionChangeCountAggregateOutputType | null
  _min: SubscriptionChangeMinAggregateOutputType | null
  _max: SubscriptionChangeMaxAggregateOutputType | null
}

type GetSubscriptionChangeGroupByPayload<T extends SubscriptionChangeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubscriptionChangeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubscriptionChangeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubscriptionChangeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubscriptionChangeGroupByOutputType[P]>
      }
    >
  >



export type SubscriptionChangeWhereInput = {
  AND?: Prisma.SubscriptionChangeWhereInput | Prisma.SubscriptionChangeWhereInput[]
  OR?: Prisma.SubscriptionChangeWhereInput[]
  NOT?: Prisma.SubscriptionChangeWhereInput | Prisma.SubscriptionChangeWhereInput[]
  id?: Prisma.StringFilter<"SubscriptionChange"> | string
  subscriptionId?: Prisma.StringFilter<"SubscriptionChange"> | string
  changeType?: Prisma.StringFilter<"SubscriptionChange"> | string
  oldValue?: Prisma.JsonNullableFilter<"SubscriptionChange">
  newValue?: Prisma.JsonNullableFilter<"SubscriptionChange">
  effectiveDate?: Prisma.DateTimeFilter<"SubscriptionChange"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SubscriptionChange"> | Date | string
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
}

export type SubscriptionChangeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  changeType?: Prisma.SortOrder
  oldValue?: Prisma.SortOrderInput | Prisma.SortOrder
  newValue?: Prisma.SortOrderInput | Prisma.SortOrder
  effectiveDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  subscription?: Prisma.SubscriptionOrderByWithRelationInput
}

export type SubscriptionChangeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SubscriptionChangeWhereInput | Prisma.SubscriptionChangeWhereInput[]
  OR?: Prisma.SubscriptionChangeWhereInput[]
  NOT?: Prisma.SubscriptionChangeWhereInput | Prisma.SubscriptionChangeWhereInput[]
  subscriptionId?: Prisma.StringFilter<"SubscriptionChange"> | string
  changeType?: Prisma.StringFilter<"SubscriptionChange"> | string
  oldValue?: Prisma.JsonNullableFilter<"SubscriptionChange">
  newValue?: Prisma.JsonNullableFilter<"SubscriptionChange">
  effectiveDate?: Prisma.DateTimeFilter<"SubscriptionChange"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SubscriptionChange"> | Date | string
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
}, "id">

export type SubscriptionChangeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  changeType?: Prisma.SortOrder
  oldValue?: Prisma.SortOrderInput | Prisma.SortOrder
  newValue?: Prisma.SortOrderInput | Prisma.SortOrder
  effectiveDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SubscriptionChangeCountOrderByAggregateInput
  _max?: Prisma.SubscriptionChangeMaxOrderByAggregateInput
  _min?: Prisma.SubscriptionChangeMinOrderByAggregateInput
}

export type SubscriptionChangeScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubscriptionChangeScalarWhereWithAggregatesInput | Prisma.SubscriptionChangeScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubscriptionChangeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubscriptionChangeScalarWhereWithAggregatesInput | Prisma.SubscriptionChangeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SubscriptionChange"> | string
  subscriptionId?: Prisma.StringWithAggregatesFilter<"SubscriptionChange"> | string
  changeType?: Prisma.StringWithAggregatesFilter<"SubscriptionChange"> | string
  oldValue?: Prisma.JsonNullableWithAggregatesFilter<"SubscriptionChange">
  newValue?: Prisma.JsonNullableWithAggregatesFilter<"SubscriptionChange">
  effectiveDate?: Prisma.DateTimeWithAggregatesFilter<"SubscriptionChange"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SubscriptionChange"> | Date | string
}

export type SubscriptionChangeCreateInput = {
  id?: string
  changeType: string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate: Date | string
  createdAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutChangesInput
}

export type SubscriptionChangeUncheckedCreateInput = {
  id?: string
  subscriptionId: string
  changeType: string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate: Date | string
  createdAt?: Date | string
}

export type SubscriptionChangeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutChangesNestedInput
}

export type SubscriptionChangeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubscriptionChangeCreateManyInput = {
  id?: string
  subscriptionId: string
  changeType: string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate: Date | string
  createdAt?: Date | string
}

export type SubscriptionChangeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubscriptionChangeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubscriptionChangeListRelationFilter = {
  every?: Prisma.SubscriptionChangeWhereInput
  some?: Prisma.SubscriptionChangeWhereInput
  none?: Prisma.SubscriptionChangeWhereInput
}

export type SubscriptionChangeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubscriptionChangeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  changeType?: Prisma.SortOrder
  oldValue?: Prisma.SortOrder
  newValue?: Prisma.SortOrder
  effectiveDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SubscriptionChangeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  changeType?: Prisma.SortOrder
  effectiveDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SubscriptionChangeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  changeType?: Prisma.SortOrder
  effectiveDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SubscriptionChangeCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.SubscriptionChangeCreateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput> | Prisma.SubscriptionChangeCreateWithoutSubscriptionInput[] | Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput | Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.SubscriptionChangeCreateManySubscriptionInputEnvelope
  connect?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
}

export type SubscriptionChangeUncheckedCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.SubscriptionChangeCreateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput> | Prisma.SubscriptionChangeCreateWithoutSubscriptionInput[] | Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput | Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.SubscriptionChangeCreateManySubscriptionInputEnvelope
  connect?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
}

export type SubscriptionChangeUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.SubscriptionChangeCreateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput> | Prisma.SubscriptionChangeCreateWithoutSubscriptionInput[] | Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput | Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.SubscriptionChangeUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.SubscriptionChangeUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.SubscriptionChangeCreateManySubscriptionInputEnvelope
  set?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  disconnect?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  delete?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  connect?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  update?: Prisma.SubscriptionChangeUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.SubscriptionChangeUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.SubscriptionChangeUpdateManyWithWhereWithoutSubscriptionInput | Prisma.SubscriptionChangeUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.SubscriptionChangeScalarWhereInput | Prisma.SubscriptionChangeScalarWhereInput[]
}

export type SubscriptionChangeUncheckedUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.SubscriptionChangeCreateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput> | Prisma.SubscriptionChangeCreateWithoutSubscriptionInput[] | Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput | Prisma.SubscriptionChangeCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.SubscriptionChangeUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.SubscriptionChangeUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.SubscriptionChangeCreateManySubscriptionInputEnvelope
  set?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  disconnect?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  delete?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  connect?: Prisma.SubscriptionChangeWhereUniqueInput | Prisma.SubscriptionChangeWhereUniqueInput[]
  update?: Prisma.SubscriptionChangeUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.SubscriptionChangeUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.SubscriptionChangeUpdateManyWithWhereWithoutSubscriptionInput | Prisma.SubscriptionChangeUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.SubscriptionChangeScalarWhereInput | Prisma.SubscriptionChangeScalarWhereInput[]
}

export type SubscriptionChangeCreateWithoutSubscriptionInput = {
  id?: string
  changeType: string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate: Date | string
  createdAt?: Date | string
}

export type SubscriptionChangeUncheckedCreateWithoutSubscriptionInput = {
  id?: string
  changeType: string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate: Date | string
  createdAt?: Date | string
}

export type SubscriptionChangeCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.SubscriptionChangeWhereUniqueInput
  create: Prisma.XOR<Prisma.SubscriptionChangeCreateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput>
}

export type SubscriptionChangeCreateManySubscriptionInputEnvelope = {
  data: Prisma.SubscriptionChangeCreateManySubscriptionInput | Prisma.SubscriptionChangeCreateManySubscriptionInput[]
  skipDuplicates?: boolean
}

export type SubscriptionChangeUpsertWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.SubscriptionChangeWhereUniqueInput
  update: Prisma.XOR<Prisma.SubscriptionChangeUpdateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedUpdateWithoutSubscriptionInput>
  create: Prisma.XOR<Prisma.SubscriptionChangeCreateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedCreateWithoutSubscriptionInput>
}

export type SubscriptionChangeUpdateWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.SubscriptionChangeWhereUniqueInput
  data: Prisma.XOR<Prisma.SubscriptionChangeUpdateWithoutSubscriptionInput, Prisma.SubscriptionChangeUncheckedUpdateWithoutSubscriptionInput>
}

export type SubscriptionChangeUpdateManyWithWhereWithoutSubscriptionInput = {
  where: Prisma.SubscriptionChangeScalarWhereInput
  data: Prisma.XOR<Prisma.SubscriptionChangeUpdateManyMutationInput, Prisma.SubscriptionChangeUncheckedUpdateManyWithoutSubscriptionInput>
}

export type SubscriptionChangeScalarWhereInput = {
  AND?: Prisma.SubscriptionChangeScalarWhereInput | Prisma.SubscriptionChangeScalarWhereInput[]
  OR?: Prisma.SubscriptionChangeScalarWhereInput[]
  NOT?: Prisma.SubscriptionChangeScalarWhereInput | Prisma.SubscriptionChangeScalarWhereInput[]
  id?: Prisma.StringFilter<"SubscriptionChange"> | string
  subscriptionId?: Prisma.StringFilter<"SubscriptionChange"> | string
  changeType?: Prisma.StringFilter<"SubscriptionChange"> | string
  oldValue?: Prisma.JsonNullableFilter<"SubscriptionChange">
  newValue?: Prisma.JsonNullableFilter<"SubscriptionChange">
  effectiveDate?: Prisma.DateTimeFilter<"SubscriptionChange"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SubscriptionChange"> | Date | string
}

export type SubscriptionChangeCreateManySubscriptionInput = {
  id?: string
  changeType: string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate: Date | string
  createdAt?: Date | string
}

export type SubscriptionChangeUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubscriptionChangeUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubscriptionChangeUncheckedUpdateManyWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changeType?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  newValue?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  effectiveDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SubscriptionChangeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subscriptionId?: boolean
  changeType?: boolean
  oldValue?: boolean
  newValue?: boolean
  effectiveDate?: boolean
  createdAt?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subscriptionChange"]>

export type SubscriptionChangeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subscriptionId?: boolean
  changeType?: boolean
  oldValue?: boolean
  newValue?: boolean
  effectiveDate?: boolean
  createdAt?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subscriptionChange"]>

export type SubscriptionChangeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subscriptionId?: boolean
  changeType?: boolean
  oldValue?: boolean
  newValue?: boolean
  effectiveDate?: boolean
  createdAt?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subscriptionChange"]>

export type SubscriptionChangeSelectScalar = {
  id?: boolean
  subscriptionId?: boolean
  changeType?: boolean
  oldValue?: boolean
  newValue?: boolean
  effectiveDate?: boolean
  createdAt?: boolean
}

export type SubscriptionChangeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "subscriptionId" | "changeType" | "oldValue" | "newValue" | "effectiveDate" | "createdAt", ExtArgs["result"]["subscriptionChange"]>
export type SubscriptionChangeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}
export type SubscriptionChangeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}
export type SubscriptionChangeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
}

export type $SubscriptionChangePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SubscriptionChange"
  objects: {
    subscription: Prisma.$SubscriptionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    subscriptionId: string
    changeType: string
    oldValue: runtime.JsonValue | null
    newValue: runtime.JsonValue | null
    effectiveDate: Date
    createdAt: Date
  }, ExtArgs["result"]["subscriptionChange"]>
  composites: {}
}

export type SubscriptionChangeGetPayload<S extends boolean | null | undefined | SubscriptionChangeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload, S>

export type SubscriptionChangeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubscriptionChangeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubscriptionChangeCountAggregateInputType | true
  }

export interface SubscriptionChangeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SubscriptionChange'], meta: { name: 'SubscriptionChange' } }
  /**
   * Find zero or one SubscriptionChange that matches the filter.
   * @param {SubscriptionChangeFindUniqueArgs} args - Arguments to find a SubscriptionChange
   * @example
   * // Get one SubscriptionChange
   * const subscriptionChange = await prisma.subscriptionChange.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubscriptionChangeFindUniqueArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SubscriptionChange that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubscriptionChangeFindUniqueOrThrowArgs} args - Arguments to find a SubscriptionChange
   * @example
   * // Get one SubscriptionChange
   * const subscriptionChange = await prisma.subscriptionChange.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubscriptionChangeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubscriptionChange that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeFindFirstArgs} args - Arguments to find a SubscriptionChange
   * @example
   * // Get one SubscriptionChange
   * const subscriptionChange = await prisma.subscriptionChange.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubscriptionChangeFindFirstArgs>(args?: Prisma.SelectSubset<T, SubscriptionChangeFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubscriptionChange that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeFindFirstOrThrowArgs} args - Arguments to find a SubscriptionChange
   * @example
   * // Get one SubscriptionChange
   * const subscriptionChange = await prisma.subscriptionChange.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubscriptionChangeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubscriptionChangeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SubscriptionChanges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SubscriptionChanges
   * const subscriptionChanges = await prisma.subscriptionChange.findMany()
   * 
   * // Get first 10 SubscriptionChanges
   * const subscriptionChanges = await prisma.subscriptionChange.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const subscriptionChangeWithIdOnly = await prisma.subscriptionChange.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubscriptionChangeFindManyArgs>(args?: Prisma.SelectSubset<T, SubscriptionChangeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SubscriptionChange.
   * @param {SubscriptionChangeCreateArgs} args - Arguments to create a SubscriptionChange.
   * @example
   * // Create one SubscriptionChange
   * const SubscriptionChange = await prisma.subscriptionChange.create({
   *   data: {
   *     // ... data to create a SubscriptionChange
   *   }
   * })
   * 
   */
  create<T extends SubscriptionChangeCreateArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeCreateArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SubscriptionChanges.
   * @param {SubscriptionChangeCreateManyArgs} args - Arguments to create many SubscriptionChanges.
   * @example
   * // Create many SubscriptionChanges
   * const subscriptionChange = await prisma.subscriptionChange.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubscriptionChangeCreateManyArgs>(args?: Prisma.SelectSubset<T, SubscriptionChangeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SubscriptionChanges and returns the data saved in the database.
   * @param {SubscriptionChangeCreateManyAndReturnArgs} args - Arguments to create many SubscriptionChanges.
   * @example
   * // Create many SubscriptionChanges
   * const subscriptionChange = await prisma.subscriptionChange.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SubscriptionChanges and only return the `id`
   * const subscriptionChangeWithIdOnly = await prisma.subscriptionChange.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubscriptionChangeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubscriptionChangeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SubscriptionChange.
   * @param {SubscriptionChangeDeleteArgs} args - Arguments to delete one SubscriptionChange.
   * @example
   * // Delete one SubscriptionChange
   * const SubscriptionChange = await prisma.subscriptionChange.delete({
   *   where: {
   *     // ... filter to delete one SubscriptionChange
   *   }
   * })
   * 
   */
  delete<T extends SubscriptionChangeDeleteArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeDeleteArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SubscriptionChange.
   * @param {SubscriptionChangeUpdateArgs} args - Arguments to update one SubscriptionChange.
   * @example
   * // Update one SubscriptionChange
   * const subscriptionChange = await prisma.subscriptionChange.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubscriptionChangeUpdateArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeUpdateArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SubscriptionChanges.
   * @param {SubscriptionChangeDeleteManyArgs} args - Arguments to filter SubscriptionChanges to delete.
   * @example
   * // Delete a few SubscriptionChanges
   * const { count } = await prisma.subscriptionChange.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubscriptionChangeDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubscriptionChangeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubscriptionChanges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SubscriptionChanges
   * const subscriptionChange = await prisma.subscriptionChange.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubscriptionChangeUpdateManyArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubscriptionChanges and returns the data updated in the database.
   * @param {SubscriptionChangeUpdateManyAndReturnArgs} args - Arguments to update many SubscriptionChanges.
   * @example
   * // Update many SubscriptionChanges
   * const subscriptionChange = await prisma.subscriptionChange.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SubscriptionChanges and only return the `id`
   * const subscriptionChangeWithIdOnly = await prisma.subscriptionChange.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubscriptionChangeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SubscriptionChange.
   * @param {SubscriptionChangeUpsertArgs} args - Arguments to update or create a SubscriptionChange.
   * @example
   * // Update or create a SubscriptionChange
   * const subscriptionChange = await prisma.subscriptionChange.upsert({
   *   create: {
   *     // ... data to create a SubscriptionChange
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SubscriptionChange we want to update
   *   }
   * })
   */
  upsert<T extends SubscriptionChangeUpsertArgs>(args: Prisma.SelectSubset<T, SubscriptionChangeUpsertArgs<ExtArgs>>): Prisma.Prisma__SubscriptionChangeClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionChangePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SubscriptionChanges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeCountArgs} args - Arguments to filter SubscriptionChanges to count.
   * @example
   * // Count the number of SubscriptionChanges
   * const count = await prisma.subscriptionChange.count({
   *   where: {
   *     // ... the filter for the SubscriptionChanges we want to count
   *   }
   * })
  **/
  count<T extends SubscriptionChangeCountArgs>(
    args?: Prisma.Subset<T, SubscriptionChangeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubscriptionChangeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SubscriptionChange.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubscriptionChangeAggregateArgs>(args: Prisma.Subset<T, SubscriptionChangeAggregateArgs>): Prisma.PrismaPromise<GetSubscriptionChangeAggregateType<T>>

  /**
   * Group by SubscriptionChange.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubscriptionChangeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubscriptionChangeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubscriptionChangeGroupByArgs['orderBy'] }
      : { orderBy?: SubscriptionChangeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubscriptionChangeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubscriptionChangeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SubscriptionChange model
 */
readonly fields: SubscriptionChangeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SubscriptionChange.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubscriptionChangeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subscription<T extends Prisma.SubscriptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubscriptionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubscriptionClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SubscriptionChange model
 */
export interface SubscriptionChangeFieldRefs {
  readonly id: Prisma.FieldRef<"SubscriptionChange", 'String'>
  readonly subscriptionId: Prisma.FieldRef<"SubscriptionChange", 'String'>
  readonly changeType: Prisma.FieldRef<"SubscriptionChange", 'String'>
  readonly oldValue: Prisma.FieldRef<"SubscriptionChange", 'Json'>
  readonly newValue: Prisma.FieldRef<"SubscriptionChange", 'Json'>
  readonly effectiveDate: Prisma.FieldRef<"SubscriptionChange", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"SubscriptionChange", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SubscriptionChange findUnique
 */
export type SubscriptionChangeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * Filter, which SubscriptionChange to fetch.
   */
  where: Prisma.SubscriptionChangeWhereUniqueInput
}

/**
 * SubscriptionChange findUniqueOrThrow
 */
export type SubscriptionChangeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * Filter, which SubscriptionChange to fetch.
   */
  where: Prisma.SubscriptionChangeWhereUniqueInput
}

/**
 * SubscriptionChange findFirst
 */
export type SubscriptionChangeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * Filter, which SubscriptionChange to fetch.
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubscriptionChanges to fetch.
   */
  orderBy?: Prisma.SubscriptionChangeOrderByWithRelationInput | Prisma.SubscriptionChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubscriptionChanges.
   */
  cursor?: Prisma.SubscriptionChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubscriptionChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubscriptionChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubscriptionChanges.
   */
  distinct?: Prisma.SubscriptionChangeScalarFieldEnum | Prisma.SubscriptionChangeScalarFieldEnum[]
}

/**
 * SubscriptionChange findFirstOrThrow
 */
export type SubscriptionChangeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * Filter, which SubscriptionChange to fetch.
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubscriptionChanges to fetch.
   */
  orderBy?: Prisma.SubscriptionChangeOrderByWithRelationInput | Prisma.SubscriptionChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubscriptionChanges.
   */
  cursor?: Prisma.SubscriptionChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubscriptionChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubscriptionChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubscriptionChanges.
   */
  distinct?: Prisma.SubscriptionChangeScalarFieldEnum | Prisma.SubscriptionChangeScalarFieldEnum[]
}

/**
 * SubscriptionChange findMany
 */
export type SubscriptionChangeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * Filter, which SubscriptionChanges to fetch.
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubscriptionChanges to fetch.
   */
  orderBy?: Prisma.SubscriptionChangeOrderByWithRelationInput | Prisma.SubscriptionChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SubscriptionChanges.
   */
  cursor?: Prisma.SubscriptionChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubscriptionChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubscriptionChanges.
   */
  skip?: number
  distinct?: Prisma.SubscriptionChangeScalarFieldEnum | Prisma.SubscriptionChangeScalarFieldEnum[]
}

/**
 * SubscriptionChange create
 */
export type SubscriptionChangeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * The data needed to create a SubscriptionChange.
   */
  data: Prisma.XOR<Prisma.SubscriptionChangeCreateInput, Prisma.SubscriptionChangeUncheckedCreateInput>
}

/**
 * SubscriptionChange createMany
 */
export type SubscriptionChangeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SubscriptionChanges.
   */
  data: Prisma.SubscriptionChangeCreateManyInput | Prisma.SubscriptionChangeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SubscriptionChange createManyAndReturn
 */
export type SubscriptionChangeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * The data used to create many SubscriptionChanges.
   */
  data: Prisma.SubscriptionChangeCreateManyInput | Prisma.SubscriptionChangeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SubscriptionChange update
 */
export type SubscriptionChangeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * The data needed to update a SubscriptionChange.
   */
  data: Prisma.XOR<Prisma.SubscriptionChangeUpdateInput, Prisma.SubscriptionChangeUncheckedUpdateInput>
  /**
   * Choose, which SubscriptionChange to update.
   */
  where: Prisma.SubscriptionChangeWhereUniqueInput
}

/**
 * SubscriptionChange updateMany
 */
export type SubscriptionChangeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SubscriptionChanges.
   */
  data: Prisma.XOR<Prisma.SubscriptionChangeUpdateManyMutationInput, Prisma.SubscriptionChangeUncheckedUpdateManyInput>
  /**
   * Filter which SubscriptionChanges to update
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * Limit how many SubscriptionChanges to update.
   */
  limit?: number
}

/**
 * SubscriptionChange updateManyAndReturn
 */
export type SubscriptionChangeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * The data used to update SubscriptionChanges.
   */
  data: Prisma.XOR<Prisma.SubscriptionChangeUpdateManyMutationInput, Prisma.SubscriptionChangeUncheckedUpdateManyInput>
  /**
   * Filter which SubscriptionChanges to update
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * Limit how many SubscriptionChanges to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SubscriptionChange upsert
 */
export type SubscriptionChangeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * The filter to search for the SubscriptionChange to update in case it exists.
   */
  where: Prisma.SubscriptionChangeWhereUniqueInput
  /**
   * In case the SubscriptionChange found by the `where` argument doesn't exist, create a new SubscriptionChange with this data.
   */
  create: Prisma.XOR<Prisma.SubscriptionChangeCreateInput, Prisma.SubscriptionChangeUncheckedCreateInput>
  /**
   * In case the SubscriptionChange was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubscriptionChangeUpdateInput, Prisma.SubscriptionChangeUncheckedUpdateInput>
}

/**
 * SubscriptionChange delete
 */
export type SubscriptionChangeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
  /**
   * Filter which SubscriptionChange to delete.
   */
  where: Prisma.SubscriptionChangeWhereUniqueInput
}

/**
 * SubscriptionChange deleteMany
 */
export type SubscriptionChangeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubscriptionChanges to delete
   */
  where?: Prisma.SubscriptionChangeWhereInput
  /**
   * Limit how many SubscriptionChanges to delete.
   */
  limit?: number
}

/**
 * SubscriptionChange without action
 */
export type SubscriptionChangeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubscriptionChange
   */
  select?: Prisma.SubscriptionChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubscriptionChange
   */
  omit?: Prisma.SubscriptionChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionChangeInclude<ExtArgs> | null
}
