
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TableReservation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TableReservation
 * 
 */
export type TableReservationModel = runtime.Types.Result.DefaultSelection<Prisma.$TableReservationPayload>

export type AggregateTableReservation = {
  _count: TableReservationCountAggregateOutputType | null
  _avg: TableReservationAvgAggregateOutputType | null
  _sum: TableReservationSumAggregateOutputType | null
  _min: TableReservationMinAggregateOutputType | null
  _max: TableReservationMaxAggregateOutputType | null
}

export type TableReservationAvgAggregateOutputType = {
  partySize: number | null
}

export type TableReservationSumAggregateOutputType = {
  partySize: number | null
}

export type TableReservationMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  userId: string | null
  tableNumber: string | null
  reservationDate: Date | null
  reservationTime: Date | null
  partySize: number | null
  specialRequests: string | null
  status: $Enums.ReservationStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TableReservationMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  userId: string | null
  tableNumber: string | null
  reservationDate: Date | null
  reservationTime: Date | null
  partySize: number | null
  specialRequests: string | null
  status: $Enums.ReservationStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TableReservationCountAggregateOutputType = {
  id: number
  orderId: number
  userId: number
  tableNumber: number
  reservationDate: number
  reservationTime: number
  partySize: number
  specialRequests: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TableReservationAvgAggregateInputType = {
  partySize?: true
}

export type TableReservationSumAggregateInputType = {
  partySize?: true
}

export type TableReservationMinAggregateInputType = {
  id?: true
  orderId?: true
  userId?: true
  tableNumber?: true
  reservationDate?: true
  reservationTime?: true
  partySize?: true
  specialRequests?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type TableReservationMaxAggregateInputType = {
  id?: true
  orderId?: true
  userId?: true
  tableNumber?: true
  reservationDate?: true
  reservationTime?: true
  partySize?: true
  specialRequests?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type TableReservationCountAggregateInputType = {
  id?: true
  orderId?: true
  userId?: true
  tableNumber?: true
  reservationDate?: true
  reservationTime?: true
  partySize?: true
  specialRequests?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TableReservationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TableReservation to aggregate.
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableReservations to fetch.
   */
  orderBy?: Prisma.TableReservationOrderByWithRelationInput | Prisma.TableReservationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TableReservationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableReservations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableReservations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TableReservations
  **/
  _count?: true | TableReservationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TableReservationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TableReservationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TableReservationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TableReservationMaxAggregateInputType
}

export type GetTableReservationAggregateType<T extends TableReservationAggregateArgs> = {
      [P in keyof T & keyof AggregateTableReservation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTableReservation[P]>
    : Prisma.GetScalarType<T[P], AggregateTableReservation[P]>
}




export type TableReservationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TableReservationWhereInput
  orderBy?: Prisma.TableReservationOrderByWithAggregationInput | Prisma.TableReservationOrderByWithAggregationInput[]
  by: Prisma.TableReservationScalarFieldEnum[] | Prisma.TableReservationScalarFieldEnum
  having?: Prisma.TableReservationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TableReservationCountAggregateInputType | true
  _avg?: TableReservationAvgAggregateInputType
  _sum?: TableReservationSumAggregateInputType
  _min?: TableReservationMinAggregateInputType
  _max?: TableReservationMaxAggregateInputType
}

export type TableReservationGroupByOutputType = {
  id: string
  orderId: string
  userId: string | null
  tableNumber: string | null
  reservationDate: Date
  reservationTime: Date
  partySize: number
  specialRequests: string | null
  status: $Enums.ReservationStatus
  createdAt: Date
  updatedAt: Date
  _count: TableReservationCountAggregateOutputType | null
  _avg: TableReservationAvgAggregateOutputType | null
  _sum: TableReservationSumAggregateOutputType | null
  _min: TableReservationMinAggregateOutputType | null
  _max: TableReservationMaxAggregateOutputType | null
}

type GetTableReservationGroupByPayload<T extends TableReservationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TableReservationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TableReservationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TableReservationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TableReservationGroupByOutputType[P]>
      }
    >
  >



export type TableReservationWhereInput = {
  AND?: Prisma.TableReservationWhereInput | Prisma.TableReservationWhereInput[]
  OR?: Prisma.TableReservationWhereInput[]
  NOT?: Prisma.TableReservationWhereInput | Prisma.TableReservationWhereInput[]
  id?: Prisma.StringFilter<"TableReservation"> | string
  orderId?: Prisma.StringFilter<"TableReservation"> | string
  userId?: Prisma.StringNullableFilter<"TableReservation"> | string | null
  tableNumber?: Prisma.StringNullableFilter<"TableReservation"> | string | null
  reservationDate?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  reservationTime?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  partySize?: Prisma.IntFilter<"TableReservation"> | number
  specialRequests?: Prisma.StringNullableFilter<"TableReservation"> | string | null
  status?: Prisma.EnumReservationStatusFilter<"TableReservation"> | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}

export type TableReservationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  tableNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  reservationDate?: Prisma.SortOrder
  reservationTime?: Prisma.SortOrder
  partySize?: Prisma.SortOrder
  specialRequests?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
}

export type TableReservationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  orderId?: string
  AND?: Prisma.TableReservationWhereInput | Prisma.TableReservationWhereInput[]
  OR?: Prisma.TableReservationWhereInput[]
  NOT?: Prisma.TableReservationWhereInput | Prisma.TableReservationWhereInput[]
  userId?: Prisma.StringNullableFilter<"TableReservation"> | string | null
  tableNumber?: Prisma.StringNullableFilter<"TableReservation"> | string | null
  reservationDate?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  reservationTime?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  partySize?: Prisma.IntFilter<"TableReservation"> | number
  specialRequests?: Prisma.StringNullableFilter<"TableReservation"> | string | null
  status?: Prisma.EnumReservationStatusFilter<"TableReservation"> | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TableReservation"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}, "id" | "orderId">

export type TableReservationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  tableNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  reservationDate?: Prisma.SortOrder
  reservationTime?: Prisma.SortOrder
  partySize?: Prisma.SortOrder
  specialRequests?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TableReservationCountOrderByAggregateInput
  _avg?: Prisma.TableReservationAvgOrderByAggregateInput
  _max?: Prisma.TableReservationMaxOrderByAggregateInput
  _min?: Prisma.TableReservationMinOrderByAggregateInput
  _sum?: Prisma.TableReservationSumOrderByAggregateInput
}

export type TableReservationScalarWhereWithAggregatesInput = {
  AND?: Prisma.TableReservationScalarWhereWithAggregatesInput | Prisma.TableReservationScalarWhereWithAggregatesInput[]
  OR?: Prisma.TableReservationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TableReservationScalarWhereWithAggregatesInput | Prisma.TableReservationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TableReservation"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"TableReservation"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"TableReservation"> | string | null
  tableNumber?: Prisma.StringNullableWithAggregatesFilter<"TableReservation"> | string | null
  reservationDate?: Prisma.DateTimeWithAggregatesFilter<"TableReservation"> | Date | string
  reservationTime?: Prisma.DateTimeWithAggregatesFilter<"TableReservation"> | Date | string
  partySize?: Prisma.IntWithAggregatesFilter<"TableReservation"> | number
  specialRequests?: Prisma.StringNullableWithAggregatesFilter<"TableReservation"> | string | null
  status?: Prisma.EnumReservationStatusWithAggregatesFilter<"TableReservation"> | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TableReservation"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TableReservation"> | Date | string
}

export type TableReservationCreateInput = {
  id?: string
  userId?: string | null
  tableNumber?: string | null
  reservationDate: Date | string
  reservationTime: Date | string
  partySize: number
  specialRequests?: string | null
  status?: $Enums.ReservationStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  order: Prisma.OrderCreateNestedOneWithoutTableReservationInput
}

export type TableReservationUncheckedCreateInput = {
  id?: string
  orderId: string
  userId?: string | null
  tableNumber?: string | null
  reservationDate: Date | string
  reservationTime: Date | string
  partySize: number
  specialRequests?: string | null
  status?: $Enums.ReservationStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableReservationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tableNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reservationDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservationTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partySize?: Prisma.IntFieldUpdateOperationsInput | number
  specialRequests?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReservationStatusFieldUpdateOperationsInput | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.OrderUpdateOneRequiredWithoutTableReservationNestedInput
}

export type TableReservationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tableNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reservationDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservationTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partySize?: Prisma.IntFieldUpdateOperationsInput | number
  specialRequests?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReservationStatusFieldUpdateOperationsInput | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableReservationCreateManyInput = {
  id?: string
  orderId: string
  userId?: string | null
  tableNumber?: string | null
  reservationDate: Date | string
  reservationTime: Date | string
  partySize: number
  specialRequests?: string | null
  status?: $Enums.ReservationStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableReservationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tableNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reservationDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservationTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partySize?: Prisma.IntFieldUpdateOperationsInput | number
  specialRequests?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReservationStatusFieldUpdateOperationsInput | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableReservationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tableNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reservationDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservationTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partySize?: Prisma.IntFieldUpdateOperationsInput | number
  specialRequests?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReservationStatusFieldUpdateOperationsInput | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableReservationNullableScalarRelationFilter = {
  is?: Prisma.TableReservationWhereInput | null
  isNot?: Prisma.TableReservationWhereInput | null
}

export type TableReservationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrder
  reservationDate?: Prisma.SortOrder
  reservationTime?: Prisma.SortOrder
  partySize?: Prisma.SortOrder
  specialRequests?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TableReservationAvgOrderByAggregateInput = {
  partySize?: Prisma.SortOrder
}

export type TableReservationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrder
  reservationDate?: Prisma.SortOrder
  reservationTime?: Prisma.SortOrder
  partySize?: Prisma.SortOrder
  specialRequests?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TableReservationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tableNumber?: Prisma.SortOrder
  reservationDate?: Prisma.SortOrder
  reservationTime?: Prisma.SortOrder
  partySize?: Prisma.SortOrder
  specialRequests?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TableReservationSumOrderByAggregateInput = {
  partySize?: Prisma.SortOrder
}

export type TableReservationCreateNestedOneWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.TableReservationCreateWithoutOrderInput, Prisma.TableReservationUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.TableReservationCreateOrConnectWithoutOrderInput
  connect?: Prisma.TableReservationWhereUniqueInput
}

export type TableReservationUncheckedCreateNestedOneWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.TableReservationCreateWithoutOrderInput, Prisma.TableReservationUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.TableReservationCreateOrConnectWithoutOrderInput
  connect?: Prisma.TableReservationWhereUniqueInput
}

export type TableReservationUpdateOneWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.TableReservationCreateWithoutOrderInput, Prisma.TableReservationUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.TableReservationCreateOrConnectWithoutOrderInput
  upsert?: Prisma.TableReservationUpsertWithoutOrderInput
  disconnect?: Prisma.TableReservationWhereInput | boolean
  delete?: Prisma.TableReservationWhereInput | boolean
  connect?: Prisma.TableReservationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TableReservationUpdateToOneWithWhereWithoutOrderInput, Prisma.TableReservationUpdateWithoutOrderInput>, Prisma.TableReservationUncheckedUpdateWithoutOrderInput>
}

export type TableReservationUncheckedUpdateOneWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.TableReservationCreateWithoutOrderInput, Prisma.TableReservationUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.TableReservationCreateOrConnectWithoutOrderInput
  upsert?: Prisma.TableReservationUpsertWithoutOrderInput
  disconnect?: Prisma.TableReservationWhereInput | boolean
  delete?: Prisma.TableReservationWhereInput | boolean
  connect?: Prisma.TableReservationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TableReservationUpdateToOneWithWhereWithoutOrderInput, Prisma.TableReservationUpdateWithoutOrderInput>, Prisma.TableReservationUncheckedUpdateWithoutOrderInput>
}

export type EnumReservationStatusFieldUpdateOperationsInput = {
  set?: $Enums.ReservationStatus
}

export type TableReservationCreateWithoutOrderInput = {
  id?: string
  userId?: string | null
  tableNumber?: string | null
  reservationDate: Date | string
  reservationTime: Date | string
  partySize: number
  specialRequests?: string | null
  status?: $Enums.ReservationStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableReservationUncheckedCreateWithoutOrderInput = {
  id?: string
  userId?: string | null
  tableNumber?: string | null
  reservationDate: Date | string
  reservationTime: Date | string
  partySize: number
  specialRequests?: string | null
  status?: $Enums.ReservationStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableReservationCreateOrConnectWithoutOrderInput = {
  where: Prisma.TableReservationWhereUniqueInput
  create: Prisma.XOR<Prisma.TableReservationCreateWithoutOrderInput, Prisma.TableReservationUncheckedCreateWithoutOrderInput>
}

export type TableReservationUpsertWithoutOrderInput = {
  update: Prisma.XOR<Prisma.TableReservationUpdateWithoutOrderInput, Prisma.TableReservationUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.TableReservationCreateWithoutOrderInput, Prisma.TableReservationUncheckedCreateWithoutOrderInput>
  where?: Prisma.TableReservationWhereInput
}

export type TableReservationUpdateToOneWithWhereWithoutOrderInput = {
  where?: Prisma.TableReservationWhereInput
  data: Prisma.XOR<Prisma.TableReservationUpdateWithoutOrderInput, Prisma.TableReservationUncheckedUpdateWithoutOrderInput>
}

export type TableReservationUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tableNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reservationDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservationTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partySize?: Prisma.IntFieldUpdateOperationsInput | number
  specialRequests?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReservationStatusFieldUpdateOperationsInput | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableReservationUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tableNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reservationDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservationTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partySize?: Prisma.IntFieldUpdateOperationsInput | number
  specialRequests?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReservationStatusFieldUpdateOperationsInput | $Enums.ReservationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TableReservationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  userId?: boolean
  tableNumber?: boolean
  reservationDate?: boolean
  reservationTime?: boolean
  partySize?: boolean
  specialRequests?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tableReservation"]>

export type TableReservationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  userId?: boolean
  tableNumber?: boolean
  reservationDate?: boolean
  reservationTime?: boolean
  partySize?: boolean
  specialRequests?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tableReservation"]>

export type TableReservationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  userId?: boolean
  tableNumber?: boolean
  reservationDate?: boolean
  reservationTime?: boolean
  partySize?: boolean
  specialRequests?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tableReservation"]>

export type TableReservationSelectScalar = {
  id?: boolean
  orderId?: boolean
  userId?: boolean
  tableNumber?: boolean
  reservationDate?: boolean
  reservationTime?: boolean
  partySize?: boolean
  specialRequests?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TableReservationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "userId" | "tableNumber" | "reservationDate" | "reservationTime" | "partySize" | "specialRequests" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["tableReservation"]>
export type TableReservationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type TableReservationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type TableReservationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}

export type $TableReservationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TableReservation"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    userId: string | null
    tableNumber: string | null
    reservationDate: Date
    reservationTime: Date
    partySize: number
    specialRequests: string | null
    status: $Enums.ReservationStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tableReservation"]>
  composites: {}
}

export type TableReservationGetPayload<S extends boolean | null | undefined | TableReservationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TableReservationPayload, S>

export type TableReservationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TableReservationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TableReservationCountAggregateInputType | true
  }

export interface TableReservationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TableReservation'], meta: { name: 'TableReservation' } }
  /**
   * Find zero or one TableReservation that matches the filter.
   * @param {TableReservationFindUniqueArgs} args - Arguments to find a TableReservation
   * @example
   * // Get one TableReservation
   * const tableReservation = await prisma.tableReservation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TableReservationFindUniqueArgs>(args: Prisma.SelectSubset<T, TableReservationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TableReservation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TableReservationFindUniqueOrThrowArgs} args - Arguments to find a TableReservation
   * @example
   * // Get one TableReservation
   * const tableReservation = await prisma.tableReservation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TableReservationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TableReservationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TableReservation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationFindFirstArgs} args - Arguments to find a TableReservation
   * @example
   * // Get one TableReservation
   * const tableReservation = await prisma.tableReservation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TableReservationFindFirstArgs>(args?: Prisma.SelectSubset<T, TableReservationFindFirstArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TableReservation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationFindFirstOrThrowArgs} args - Arguments to find a TableReservation
   * @example
   * // Get one TableReservation
   * const tableReservation = await prisma.tableReservation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TableReservationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TableReservationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TableReservations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TableReservations
   * const tableReservations = await prisma.tableReservation.findMany()
   * 
   * // Get first 10 TableReservations
   * const tableReservations = await prisma.tableReservation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tableReservationWithIdOnly = await prisma.tableReservation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TableReservationFindManyArgs>(args?: Prisma.SelectSubset<T, TableReservationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TableReservation.
   * @param {TableReservationCreateArgs} args - Arguments to create a TableReservation.
   * @example
   * // Create one TableReservation
   * const TableReservation = await prisma.tableReservation.create({
   *   data: {
   *     // ... data to create a TableReservation
   *   }
   * })
   * 
   */
  create<T extends TableReservationCreateArgs>(args: Prisma.SelectSubset<T, TableReservationCreateArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TableReservations.
   * @param {TableReservationCreateManyArgs} args - Arguments to create many TableReservations.
   * @example
   * // Create many TableReservations
   * const tableReservation = await prisma.tableReservation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TableReservationCreateManyArgs>(args?: Prisma.SelectSubset<T, TableReservationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TableReservations and returns the data saved in the database.
   * @param {TableReservationCreateManyAndReturnArgs} args - Arguments to create many TableReservations.
   * @example
   * // Create many TableReservations
   * const tableReservation = await prisma.tableReservation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TableReservations and only return the `id`
   * const tableReservationWithIdOnly = await prisma.tableReservation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TableReservationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TableReservationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TableReservation.
   * @param {TableReservationDeleteArgs} args - Arguments to delete one TableReservation.
   * @example
   * // Delete one TableReservation
   * const TableReservation = await prisma.tableReservation.delete({
   *   where: {
   *     // ... filter to delete one TableReservation
   *   }
   * })
   * 
   */
  delete<T extends TableReservationDeleteArgs>(args: Prisma.SelectSubset<T, TableReservationDeleteArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TableReservation.
   * @param {TableReservationUpdateArgs} args - Arguments to update one TableReservation.
   * @example
   * // Update one TableReservation
   * const tableReservation = await prisma.tableReservation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TableReservationUpdateArgs>(args: Prisma.SelectSubset<T, TableReservationUpdateArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TableReservations.
   * @param {TableReservationDeleteManyArgs} args - Arguments to filter TableReservations to delete.
   * @example
   * // Delete a few TableReservations
   * const { count } = await prisma.tableReservation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TableReservationDeleteManyArgs>(args?: Prisma.SelectSubset<T, TableReservationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TableReservations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TableReservations
   * const tableReservation = await prisma.tableReservation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TableReservationUpdateManyArgs>(args: Prisma.SelectSubset<T, TableReservationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TableReservations and returns the data updated in the database.
   * @param {TableReservationUpdateManyAndReturnArgs} args - Arguments to update many TableReservations.
   * @example
   * // Update many TableReservations
   * const tableReservation = await prisma.tableReservation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TableReservations and only return the `id`
   * const tableReservationWithIdOnly = await prisma.tableReservation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TableReservationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TableReservationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TableReservation.
   * @param {TableReservationUpsertArgs} args - Arguments to update or create a TableReservation.
   * @example
   * // Update or create a TableReservation
   * const tableReservation = await prisma.tableReservation.upsert({
   *   create: {
   *     // ... data to create a TableReservation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TableReservation we want to update
   *   }
   * })
   */
  upsert<T extends TableReservationUpsertArgs>(args: Prisma.SelectSubset<T, TableReservationUpsertArgs<ExtArgs>>): Prisma.Prisma__TableReservationClient<runtime.Types.Result.GetResult<Prisma.$TableReservationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TableReservations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationCountArgs} args - Arguments to filter TableReservations to count.
   * @example
   * // Count the number of TableReservations
   * const count = await prisma.tableReservation.count({
   *   where: {
   *     // ... the filter for the TableReservations we want to count
   *   }
   * })
  **/
  count<T extends TableReservationCountArgs>(
    args?: Prisma.Subset<T, TableReservationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TableReservationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TableReservation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TableReservationAggregateArgs>(args: Prisma.Subset<T, TableReservationAggregateArgs>): Prisma.PrismaPromise<GetTableReservationAggregateType<T>>

  /**
   * Group by TableReservation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableReservationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TableReservationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TableReservationGroupByArgs['orderBy'] }
      : { orderBy?: TableReservationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TableReservationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTableReservationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TableReservation model
 */
readonly fields: TableReservationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TableReservation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TableReservationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TableReservation model
 */
export interface TableReservationFieldRefs {
  readonly id: Prisma.FieldRef<"TableReservation", 'String'>
  readonly orderId: Prisma.FieldRef<"TableReservation", 'String'>
  readonly userId: Prisma.FieldRef<"TableReservation", 'String'>
  readonly tableNumber: Prisma.FieldRef<"TableReservation", 'String'>
  readonly reservationDate: Prisma.FieldRef<"TableReservation", 'DateTime'>
  readonly reservationTime: Prisma.FieldRef<"TableReservation", 'DateTime'>
  readonly partySize: Prisma.FieldRef<"TableReservation", 'Int'>
  readonly specialRequests: Prisma.FieldRef<"TableReservation", 'String'>
  readonly status: Prisma.FieldRef<"TableReservation", 'ReservationStatus'>
  readonly createdAt: Prisma.FieldRef<"TableReservation", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TableReservation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TableReservation findUnique
 */
export type TableReservationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * Filter, which TableReservation to fetch.
   */
  where: Prisma.TableReservationWhereUniqueInput
}

/**
 * TableReservation findUniqueOrThrow
 */
export type TableReservationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * Filter, which TableReservation to fetch.
   */
  where: Prisma.TableReservationWhereUniqueInput
}

/**
 * TableReservation findFirst
 */
export type TableReservationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * Filter, which TableReservation to fetch.
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableReservations to fetch.
   */
  orderBy?: Prisma.TableReservationOrderByWithRelationInput | Prisma.TableReservationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TableReservations.
   */
  cursor?: Prisma.TableReservationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableReservations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableReservations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TableReservations.
   */
  distinct?: Prisma.TableReservationScalarFieldEnum | Prisma.TableReservationScalarFieldEnum[]
}

/**
 * TableReservation findFirstOrThrow
 */
export type TableReservationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * Filter, which TableReservation to fetch.
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableReservations to fetch.
   */
  orderBy?: Prisma.TableReservationOrderByWithRelationInput | Prisma.TableReservationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TableReservations.
   */
  cursor?: Prisma.TableReservationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableReservations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableReservations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TableReservations.
   */
  distinct?: Prisma.TableReservationScalarFieldEnum | Prisma.TableReservationScalarFieldEnum[]
}

/**
 * TableReservation findMany
 */
export type TableReservationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * Filter, which TableReservations to fetch.
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TableReservations to fetch.
   */
  orderBy?: Prisma.TableReservationOrderByWithRelationInput | Prisma.TableReservationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TableReservations.
   */
  cursor?: Prisma.TableReservationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TableReservations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TableReservations.
   */
  skip?: number
  distinct?: Prisma.TableReservationScalarFieldEnum | Prisma.TableReservationScalarFieldEnum[]
}

/**
 * TableReservation create
 */
export type TableReservationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * The data needed to create a TableReservation.
   */
  data: Prisma.XOR<Prisma.TableReservationCreateInput, Prisma.TableReservationUncheckedCreateInput>
}

/**
 * TableReservation createMany
 */
export type TableReservationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TableReservations.
   */
  data: Prisma.TableReservationCreateManyInput | Prisma.TableReservationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TableReservation createManyAndReturn
 */
export type TableReservationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * The data used to create many TableReservations.
   */
  data: Prisma.TableReservationCreateManyInput | Prisma.TableReservationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TableReservation update
 */
export type TableReservationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * The data needed to update a TableReservation.
   */
  data: Prisma.XOR<Prisma.TableReservationUpdateInput, Prisma.TableReservationUncheckedUpdateInput>
  /**
   * Choose, which TableReservation to update.
   */
  where: Prisma.TableReservationWhereUniqueInput
}

/**
 * TableReservation updateMany
 */
export type TableReservationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TableReservations.
   */
  data: Prisma.XOR<Prisma.TableReservationUpdateManyMutationInput, Prisma.TableReservationUncheckedUpdateManyInput>
  /**
   * Filter which TableReservations to update
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * Limit how many TableReservations to update.
   */
  limit?: number
}

/**
 * TableReservation updateManyAndReturn
 */
export type TableReservationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * The data used to update TableReservations.
   */
  data: Prisma.XOR<Prisma.TableReservationUpdateManyMutationInput, Prisma.TableReservationUncheckedUpdateManyInput>
  /**
   * Filter which TableReservations to update
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * Limit how many TableReservations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TableReservation upsert
 */
export type TableReservationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * The filter to search for the TableReservation to update in case it exists.
   */
  where: Prisma.TableReservationWhereUniqueInput
  /**
   * In case the TableReservation found by the `where` argument doesn't exist, create a new TableReservation with this data.
   */
  create: Prisma.XOR<Prisma.TableReservationCreateInput, Prisma.TableReservationUncheckedCreateInput>
  /**
   * In case the TableReservation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TableReservationUpdateInput, Prisma.TableReservationUncheckedUpdateInput>
}

/**
 * TableReservation delete
 */
export type TableReservationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
  /**
   * Filter which TableReservation to delete.
   */
  where: Prisma.TableReservationWhereUniqueInput
}

/**
 * TableReservation deleteMany
 */
export type TableReservationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TableReservations to delete
   */
  where?: Prisma.TableReservationWhereInput
  /**
   * Limit how many TableReservations to delete.
   */
  limit?: number
}

/**
 * TableReservation without action
 */
export type TableReservationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableReservation
   */
  select?: Prisma.TableReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TableReservation
   */
  omit?: Prisma.TableReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableReservationInclude<ExtArgs> | null
}
