
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Category: 'Category',
  Product: 'Product',
  CartItem: 'CartItem',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Payment: 'Payment',
  WishlistItem: 'WishlistItem',
  Review: 'Review',
  Address: 'Address',
  SavedPaymentMethod: 'SavedPaymentMethod',
  PromoCode: 'PromoCode',
  OrderStatusHistory: 'OrderStatusHistory',
  ProductRelation: 'ProductRelation',
  Notification: 'Notification',
  RecentlyViewed: 'RecentlyViewed',
  ContactMessage: 'ContactMessage',
  ChatSession: 'ChatSession',
  ChatMessage: 'ChatMessage',
  StoreConfig: 'StoreConfig',
  MenuSection: 'MenuSection',
  ProductVariant: 'ProductVariant',
  Combo: 'Combo',
  ComboItem: 'ComboItem',
  ProductIngredient: 'ProductIngredient',
  ProductAllergen: 'ProductAllergen',
  TableReservation: 'TableReservation',
  Location: 'Location',
  Subscription: 'Subscription',
  SubscriptionPayment: 'SubscriptionPayment',
  SubscriptionChange: 'SubscriptionChange',
  Appointment: 'Appointment',
  AppointmentReminder: 'AppointmentReminder',
  DigitalProduct: 'DigitalProduct',
  DigitalDownload: 'DigitalDownload',
  LicenseKey: 'LicenseKey',
  Rental: 'Rental',
  Event: 'Event',
  Ticket: 'Ticket',
  EventWaitlist: 'EventWaitlist',
  AbandonedCart: 'AbandonedCart',
  SupportTicket: 'SupportTicket',
  TicketMessage: 'TicketMessage',
  ProductQuestion: 'ProductQuestion',
  PosSession: 'PosSession',
  PosTransaction: 'PosTransaction'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  name: 'name',
  phone: 'phone',
  role: 'role',
  avatar: 'avatar',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  referralCode: 'referralCode',
  referredBy: 'referredBy',
  loyaltyPoints: 'loyaltyPoints'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  price: 'price',
  comparePrice: 'comparePrice',
  stock: 'stock',
  imageUrls: 'imageUrls',
  active: 'active',
  featured: 'featured',
  categoryId: 'categoryId',
  sku: 'sku',
  weight: 'weight',
  dimensions: 'dimensions',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  menuSectionId: 'menuSectionId',
  prepTimeMinutes: 'prepTimeMinutes',
  deliveryTimeMinutes: 'deliveryTimeMinutes',
  dietaryInfo: 'dietaryInfo',
  nutritionInfo: 'nutritionInfo'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const CartItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  variantId: 'variantId',
  quantity: 'quantity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CartItemScalarFieldEnum = (typeof CartItemScalarFieldEnum)[keyof typeof CartItemScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orderNumber: 'orderNumber',
  totalAmount: 'totalAmount',
  subtotal: 'subtotal',
  shippingCost: 'shippingCost',
  discount: 'discount',
  promoCode: 'promoCode',
  status: 'status',
  deliveryMethod: 'deliveryMethod',
  paymentTiming: 'paymentTiming',
  shippingAddress: 'shippingAddress',
  pickupAddress: 'pickupAddress',
  billingAddress: 'billingAddress',
  paymentMethod: 'paymentMethod',
  trackingNumber: 'trackingNumber',
  shippingCarrier: 'shippingCarrier',
  estimatedDelivery: 'estimatedDelivery',
  estimatedPickup: 'estimatedPickup',
  notes: 'notes',
  cancelledAt: 'cancelledAt',
  cancelledReason: 'cancelledReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  locationId: 'locationId',
  tipAmount: 'tipAmount',
  scheduledFor: 'scheduledFor',
  estimatedReadyTime: 'estimatedReadyTime',
  source: 'source',
  posSessionId: 'posSessionId',
  posTransactionId: 'posTransactionId'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  quantity: 'quantity',
  priceAtPurchase: 'priceAtPurchase',
  variantId: 'variantId',
  specialInstructions: 'specialInstructions',
  createdAt: 'createdAt'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  paymentMethod: 'paymentMethod',
  gatewayTransactionId: 'gatewayTransactionId',
  stripePaymentIntentId: 'stripePaymentIntentId',
  paypalOrderId: 'paypalOrderId',
  bkashTransactionId: 'bkashTransactionId',
  nagadTransactionId: 'nagadTransactionId',
  rocketTransactionId: 'rocketTransactionId',
  bitcoinAddress: 'bitcoinAddress',
  bitcoinTransactionId: 'bitcoinTransactionId',
  ethereumAddress: 'ethereumAddress',
  ethereumTransactionId: 'ethereumTransactionId',
  cryptoAmount: 'cryptoAmount',
  exchangeRate: 'exchangeRate',
  exchangeRateExpiry: 'exchangeRateExpiry',
  networkConfirmations: 'networkConfirmations',
  requiredConfirmations: 'requiredConfirmations',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  gatewayResponse: 'gatewayResponse',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const WishlistItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  sharedWithCompany: 'sharedWithCompany',
  createdAt: 'createdAt'
} as const

export type WishlistItemScalarFieldEnum = (typeof WishlistItemScalarFieldEnum)[keyof typeof WishlistItemScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  orderId: 'orderId',
  rating: 'rating',
  title: 'title',
  comment: 'comment',
  verified: 'verified',
  helpful: 'helpful',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const AddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  name: 'name',
  line1: 'line1',
  line2: 'line2',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  country: 'country',
  phone: 'phone',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AddressScalarFieldEnum = (typeof AddressScalarFieldEnum)[keyof typeof AddressScalarFieldEnum]


export const SavedPaymentMethodScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  paymentMethod: 'paymentMethod',
  last4: 'last4',
  brand: 'brand',
  expiryMonth: 'expiryMonth',
  expiryYear: 'expiryYear',
  metadata: 'metadata',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SavedPaymentMethodScalarFieldEnum = (typeof SavedPaymentMethodScalarFieldEnum)[keyof typeof SavedPaymentMethodScalarFieldEnum]


export const PromoCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  description: 'description',
  discountType: 'discountType',
  discountValue: 'discountValue',
  minPurchase: 'minPurchase',
  maxDiscount: 'maxDiscount',
  usageLimit: 'usageLimit',
  usedCount: 'usedCount',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PromoCodeScalarFieldEnum = (typeof PromoCodeScalarFieldEnum)[keyof typeof PromoCodeScalarFieldEnum]


export const OrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  status: 'status',
  note: 'note',
  createdAt: 'createdAt'
} as const

export type OrderStatusHistoryScalarFieldEnum = (typeof OrderStatusHistoryScalarFieldEnum)[keyof typeof OrderStatusHistoryScalarFieldEnum]


export const ProductRelationScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  relatedId: 'relatedId',
  createdAt: 'createdAt'
} as const

export type ProductRelationScalarFieldEnum = (typeof ProductRelationScalarFieldEnum)[keyof typeof ProductRelationScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  link: 'link',
  read: 'read',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const RecentlyViewedScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  sessionId: 'sessionId',
  viewedAt: 'viewedAt'
} as const

export type RecentlyViewedScalarFieldEnum = (typeof RecentlyViewedScalarFieldEnum)[keyof typeof RecentlyViewedScalarFieldEnum]


export const ContactMessageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  subject: 'subject',
  message: 'message',
  response: 'response',
  respondedAt: 'respondedAt',
  respondedBy: 'respondedBy',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContactMessageScalarFieldEnum = (typeof ContactMessageScalarFieldEnum)[keyof typeof ContactMessageScalarFieldEnum]


export const ChatSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sessionId: 'sessionId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatSessionScalarFieldEnum = (typeof ChatSessionScalarFieldEnum)[keyof typeof ChatSessionScalarFieldEnum]


export const ChatMessageScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  role: 'role',
  content: 'content',
  products: 'products',
  createdAt: 'createdAt'
} as const

export type ChatMessageScalarFieldEnum = (typeof ChatMessageScalarFieldEnum)[keyof typeof ChatMessageScalarFieldEnum]


export const StoreConfigScalarFieldEnum = {
  id: 'id',
  storeName: 'storeName',
  storeType: 'storeType',
  tagline: 'tagline',
  description: 'description',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  accentColor: 'accentColor',
  logoUrl: 'logoUrl',
  faviconUrl: 'faviconUrl',
  bannerImageUrl: 'bannerImageUrl',
  currency: 'currency',
  currencySymbol: 'currencySymbol',
  country: 'country',
  language: 'language',
  email: 'email',
  phone: 'phone',
  address: 'address',
  businessHours: 'businessHours',
  facebookUrl: 'facebookUrl',
  twitterUrl: 'twitterUrl',
  instagramUrl: 'instagramUrl',
  youtubeUrl: 'youtubeUrl',
  footerText: 'footerText',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  metaKeywords: 'metaKeywords',
  heroTitle: 'heroTitle',
  heroSubtitle: 'heroSubtitle',
  heroButtonText: 'heroButtonText',
  heroButton2Text: 'heroButton2Text',
  heroButton2Url: 'heroButton2Url',
  heroParticlesEnabled: 'heroParticlesEnabled',
  heroParticlesDensity: 'heroParticlesDensity',
  heroParticlesSpeed: 'heroParticlesSpeed',
  heroParticlesColor: 'heroParticlesColor',
  heroParticlesType: 'heroParticlesType',
  featuresEnabled: 'featuresEnabled',
  featuresJson: 'featuresJson',
  showHero: 'showHero',
  showFeatures: 'showFeatures',
  showFeaturedProducts: 'showFeaturedProducts',
  showRecentlyViewed: 'showRecentlyViewed',
  featuredProductsTitle: 'featuredProductsTitle',
  featuredProductsSubtitle: 'featuredProductsSubtitle',
  featuredProductsLimit: 'featuredProductsLimit',
  chatbotEnabled: 'chatbotEnabled',
  wishlistEnabled: 'wishlistEnabled',
  reviewsEnabled: 'reviewsEnabled',
  notificationsEnabled: 'notificationsEnabled',
  recentlyViewedEnabled: 'recentlyViewedEnabled',
  pickupEnabled: 'pickupEnabled',
  payAtStoreEnabled: 'payAtStoreEnabled',
  posEnabled: 'posEnabled',
  guestCheckoutEnabled: 'guestCheckoutEnabled',
  cashOnDeliveryEnabled: 'cashOnDeliveryEnabled',
  buyNowPayLaterEnabled: 'buyNowPayLaterEnabled',
  minimumOrderAmountEnabled: 'minimumOrderAmountEnabled',
  minimumOrderAmount: 'minimumOrderAmount',
  customerAccountsEnabled: 'customerAccountsEnabled',
  savedPaymentMethodsEnabled: 'savedPaymentMethodsEnabled',
  multipleAddressesEnabled: 'multipleAddressesEnabled',
  backInStockNotificationsEnabled: 'backInStockNotificationsEnabled',
  loyaltyProgramEnabled: 'loyaltyProgramEnabled',
  referralProgramEnabled: 'referralProgramEnabled',
  giftCardsEnabled: 'giftCardsEnabled',
  giftWrappingEnabled: 'giftWrappingEnabled',
  productVariantsEnabled: 'productVariantsEnabled',
  productCategoriesEnabled: 'productCategoriesEnabled',
  relatedProductsEnabled: 'relatedProductsEnabled',
  productSearchEnabled: 'productSearchEnabled',
  searchAutocompleteEnabled: 'searchAutocompleteEnabled',
  productQuickViewEnabled: 'productQuickViewEnabled',
  imageZoomEnabled: 'imageZoomEnabled',
  inventoryManagementEnabled: 'inventoryManagementEnabled',
  promoCodesEnabled: 'promoCodesEnabled',
  promotionalDiscountEnabled: 'promotionalDiscountEnabled',
  promotionalDiscountType: 'promotionalDiscountType',
  promotionalDiscountValue: 'promotionalDiscountValue',
  promotionalDiscountValidFrom: 'promotionalDiscountValidFrom',
  promotionalDiscountValidUntil: 'promotionalDiscountValidUntil',
  promotionalDiscountActive: 'promotionalDiscountActive',
  flashSalesEnabled: 'flashSalesEnabled',
  newsletterEnabled: 'newsletterEnabled',
  emailMarketingEnabled: 'emailMarketingEnabled',
  contactFormEnabled: 'contactFormEnabled',
  liveChatEnabled: 'liveChatEnabled',
  orderTrackingEnabled: 'orderTrackingEnabled',
  emailNotificationsEnabled: 'emailNotificationsEnabled',
  printReceiptEnabled: 'printReceiptEnabled',
  multiLanguageEnabled: 'multiLanguageEnabled',
  multiCurrencyEnabled: 'multiCurrencyEnabled',
  taxCalculationEnabled: 'taxCalculationEnabled',
  shippingZonesEnabled: 'shippingZonesEnabled',
  blogEnabled: 'blogEnabled',
  breadcrumbsNavigationEnabled: 'breadcrumbsNavigationEnabled',
  advancedPaginationEnabled: 'advancedPaginationEnabled',
  socialMediaIntegrationEnabled: 'socialMediaIntegrationEnabled',
  analyticsTrackingEnabled: 'analyticsTrackingEnabled',
  subscriptionOrdersEnabled: 'subscriptionOrdersEnabled',
  storeHoursEnabled: 'storeHoursEnabled',
  storeHours: 'storeHours',
  holidayModeEnabled: 'holidayModeEnabled',
  holidayModeUntil: 'holidayModeUntil',
  maintenanceModeEnabled: 'maintenanceModeEnabled',
  maintenanceMessage: 'maintenanceMessage',
  storePickupAddress: 'storePickupAddress',
  stripeEnabled: 'stripeEnabled',
  paypalEnabled: 'paypalEnabled',
  applePayEnabled: 'applePayEnabled',
  googlePayEnabled: 'googlePayEnabled',
  amazonPayEnabled: 'amazonPayEnabled',
  bkashEnabled: 'bkashEnabled',
  nagadEnabled: 'nagadEnabled',
  rocketEnabled: 'rocketEnabled',
  bitcoinEnabled: 'bitcoinEnabled',
  ethereumEnabled: 'ethereumEnabled',
  manualCreditCardEnabled: 'manualCreditCardEnabled',
  navigationItems: 'navigationItems',
  tableReservationsEnabled: 'tableReservationsEnabled',
  menuBuilderEnabled: 'menuBuilderEnabled',
  dietaryFiltersEnabled: 'dietaryFiltersEnabled',
  prepTimeEnabled: 'prepTimeEnabled',
  deliveryTimeEnabled: 'deliveryTimeEnabled',
  ingredientListEnabled: 'ingredientListEnabled',
  allergenWarningsEnabled: 'allergenWarningsEnabled',
  mealComboBuilderEnabled: 'mealComboBuilderEnabled',
  nutritionalInfoEnabled: 'nutritionalInfoEnabled',
  productVariantsEnabledRestaurant: 'productVariantsEnabledRestaurant',
  orderSchedulingEnabled: 'orderSchedulingEnabled',
  multiLocationEnabled: 'multiLocationEnabled',
  tippingEnabled: 'tippingEnabled',
  tippingDefaultPercentages: 'tippingDefaultPercentages',
  loyaltyStampsEnabled: 'loyaltyStampsEnabled',
  loyaltyStampsRequired: 'loyaltyStampsRequired',
  appointmentBookingEnabled: 'appointmentBookingEnabled',
  servicePackagesEnabled: 'servicePackagesEnabled',
  staffManagementEnabled: 'staffManagementEnabled',
  serviceDurationEnabled: 'serviceDurationEnabled',
  clientHistoryEnabled: 'clientHistoryEnabled',
  recurringAppointmentsEnabled: 'recurringAppointmentsEnabled',
  resourceBookingEnabled: 'resourceBookingEnabled',
  serviceAddonsEnabled: 'serviceAddonsEnabled',
  cancellationPoliciesEnabled: 'cancellationPoliciesEnabled',
  serviceRemindersEnabled: 'serviceRemindersEnabled',
  beforeAfterPhotosEnabled: 'beforeAfterPhotosEnabled',
  serviceAreasEnabled: 'serviceAreasEnabled',
  subscriptionPlansEnabled: 'subscriptionPlansEnabled',
  recurringBillingEnabled: 'recurringBillingEnabled',
  trialPeriodsEnabled: 'trialPeriodsEnabled',
  planUpgradesDowngradesEnabled: 'planUpgradesDowngradesEnabled',
  pauseResumeSubscriptionsEnabled: 'pauseResumeSubscriptionsEnabled',
  subscriptionDashboardEnabled: 'subscriptionDashboardEnabled',
  prorationEnabled: 'prorationEnabled',
  dunningManagementEnabled: 'dunningManagementEnabled',
  giftSubscriptionsEnabled: 'giftSubscriptionsEnabled',
  familyGroupPlansEnabled: 'familyGroupPlansEnabled',
  advancedCalendarEnabled: 'advancedCalendarEnabled',
  bufferTimesEnabled: 'bufferTimesEnabled',
  waitingListsEnabled: 'waitingListsEnabled',
  classWorkshopBookingsEnabled: 'classWorkshopBookingsEnabled',
  serviceCategoriesEnabled: 'serviceCategoriesEnabled',
  intakeFormsEnabled: 'intakeFormsEnabled',
  videoConsultationsEnabled: 'videoConsultationsEnabled',
  appointmentRemindersEnabled: 'appointmentRemindersEnabled',
  noShowTrackingEnabled: 'noShowTrackingEnabled',
  staffAvailabilityEnabled: 'staffAvailabilityEnabled',
  instantDigitalDeliveryEnabled: 'instantDigitalDeliveryEnabled',
  licenseKeyManagementEnabled: 'licenseKeyManagementEnabled',
  downloadLimitsEnabled: 'downloadLimitsEnabled',
  fileHostingEnabled: 'fileHostingEnabled',
  courseProgressTrackingEnabled: 'courseProgressTrackingEnabled',
  accessExpirationEnabled: 'accessExpirationEnabled',
  bulkLicensePurchasesEnabled: 'bulkLicensePurchasesEnabled',
  affiliateSystemEnabled: 'affiliateSystemEnabled',
  softwareUpdatesEnabled: 'softwareUpdatesEnabled',
  previewFreeSamplesEnabled: 'previewFreeSamplesEnabled',
  rentalDurationSelectionEnabled: 'rentalDurationSelectionEnabled',
  dateRangePickerEnabled: 'dateRangePickerEnabled',
  availabilityCalendarEnabled: 'availabilityCalendarEnabled',
  depositSecurityHoldEnabled: 'depositSecurityHoldEnabled',
  lateReturnFeesEnabled: 'lateReturnFeesEnabled',
  deliveryPickupSchedulingEnabled: 'deliveryPickupSchedulingEnabled',
  damageReportingEnabled: 'damageReportingEnabled',
  rentalAgreementsEnabled: 'rentalAgreementsEnabled',
  maintenanceSchedulingEnabled: 'maintenanceSchedulingEnabled',
  rentalWaitingListsEnabled: 'rentalWaitingListsEnabled',
  marketplaceEnabled: 'marketplaceEnabled',
  vendorRegistrationEnabled: 'vendorRegistrationEnabled',
  commissionManagementEnabled: 'commissionManagementEnabled',
  vendorDashboardEnabled: 'vendorDashboardEnabled',
  vendorReviewsEnabled: 'vendorReviewsEnabled',
  splitPaymentsEnabled: 'splitPaymentsEnabled',
  vendorAnalyticsEnabled: 'vendorAnalyticsEnabled',
  vendorStorefrontsEnabled: 'vendorStorefrontsEnabled',
  vendorMessagingEnabled: 'vendorMessagingEnabled',
  disputeResolutionEnabled: 'disputeResolutionEnabled',
  eventCalendarEnabled: 'eventCalendarEnabled',
  seatTableSelectionEnabled: 'seatTableSelectionEnabled',
  ticketTypesEnabled: 'ticketTypesEnabled',
  eventCapacityManagementEnabled: 'eventCapacityManagementEnabled',
  earlyBirdPricingEnabled: 'earlyBirdPricingEnabled',
  groupDiscountsEnabled: 'groupDiscountsEnabled',
  eventRemindersEnabled: 'eventRemindersEnabled',
  qrCodeTicketsEnabled: 'qrCodeTicketsEnabled',
  eventWaitlistEnabled: 'eventWaitlistEnabled',
  eventHostingEnabled: 'eventHostingEnabled',
  eventPackagesEnabled: 'eventPackagesEnabled',
  deliveryZonesEnabled: 'deliveryZonesEnabled',
  deliveryFeeCalculatorEnabled: 'deliveryFeeCalculatorEnabled',
  sameDayDeliveryEnabled: 'sameDayDeliveryEnabled',
  deliveryDriverManagementEnabled: 'deliveryDriverManagementEnabled',
  realTimeTrackingEnabled: 'realTimeTrackingEnabled',
  deliveryInstructionsEnabled: 'deliveryInstructionsEnabled',
  tipForDriverEnabled: 'tipForDriverEnabled',
  multiAddressOrdersEnabled: 'multiAddressOrdersEnabled',
  scheduledDeliveriesEnabled: 'scheduledDeliveriesEnabled',
  minimumOrderFreeDeliveryEnabled: 'minimumOrderFreeDeliveryEnabled',
  customizationOptionsEnabled: 'customizationOptionsEnabled',
  madeToOrderItemsEnabled: 'madeToOrderItemsEnabled',
  customQuoteRequestsEnabled: 'customQuoteRequestsEnabled',
  productionStatusEnabled: 'productionStatusEnabled',
  materialsOriginInfoEnabled: 'materialsOriginInfoEnabled',
  artistBrandStoriesEnabled: 'artistBrandStoriesEnabled',
  commissionRequestsEnabled: 'commissionRequestsEnabled',
  limitedEditionsEnabled: 'limitedEditionsEnabled',
  inProgressPhotosEnabled: 'inProgressPhotosEnabled',
  backorderSupportEnabled: 'backorderSupportEnabled',
  wholesalePricingTiersEnabled: 'wholesalePricingTiersEnabled',
  businessAccountRegistrationEnabled: 'businessAccountRegistrationEnabled',
  creditTermsEnabled: 'creditTermsEnabled',
  poSupportEnabled: 'poSupportEnabled',
  bulkOrderFormsEnabled: 'bulkOrderFormsEnabled',
  minimumOrderQuantitiesEnabled: 'minimumOrderQuantitiesEnabled',
  catalogPricingEnabled: 'catalogPricingEnabled',
  taxExemptHandlingEnabled: 'taxExemptHandlingEnabled',
  salesRepAssignmentEnabled: 'salesRepAssignmentEnabled',
  creditLimitsEnabled: 'creditLimitsEnabled',
  abandonedCartRecoveryEnabled: 'abandonedCartRecoveryEnabled',
  productComparisonEnabled: 'productComparisonEnabled',
  bulkOrderingEnabled: 'bulkOrderingEnabled',
  preOrdersEnabled: 'preOrdersEnabled',
  customerGroupsEnabled: 'customerGroupsEnabled',
  advancedFilteringEnabled: 'advancedFilteringEnabled',
  giftRegistryEnabled: 'giftRegistryEnabled',
  socialSharingEnabled: 'socialSharingEnabled',
  multiWarehouseInventoryEnabled: 'multiWarehouseInventoryEnabled',
  barcodeQrScanningEnabled: 'barcodeQrScanningEnabled',
  advancedAnalyticsEnabled: 'advancedAnalyticsEnabled',
  emailMarketingIntegrationEnabled: 'emailMarketingIntegrationEnabled',
  smsNotificationsEnabled: 'smsNotificationsEnabled',
  customerSupportTicketsEnabled: 'customerSupportTicketsEnabled',
  productQAEnabled: 'productQAEnabled',
  videoProductDemosEnabled: 'videoProductDemosEnabled',
  product360ViewsEnabled: 'product360ViewsEnabled',
  arVrProductPreviewEnabled: 'arVrProductPreviewEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StoreConfigScalarFieldEnum = (typeof StoreConfigScalarFieldEnum)[keyof typeof StoreConfigScalarFieldEnum]


export const MenuSectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  displayOrder: 'displayOrder',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MenuSectionScalarFieldEnum = (typeof MenuSectionScalarFieldEnum)[keyof typeof MenuSectionScalarFieldEnum]


export const ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  type: 'type',
  sku: 'sku',
  priceModifier: 'priceModifier',
  price: 'price',
  stock: 'stock',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductVariantScalarFieldEnum = (typeof ProductVariantScalarFieldEnum)[keyof typeof ProductVariantScalarFieldEnum]


export const ComboScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  imageUrl: 'imageUrl',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ComboScalarFieldEnum = (typeof ComboScalarFieldEnum)[keyof typeof ComboScalarFieldEnum]


export const ComboItemScalarFieldEnum = {
  id: 'id',
  comboId: 'comboId',
  productId: 'productId',
  quantity: 'quantity',
  required: 'required',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt'
} as const

export type ComboItemScalarFieldEnum = (typeof ComboItemScalarFieldEnum)[keyof typeof ComboItemScalarFieldEnum]


export const ProductIngredientScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  quantity: 'quantity',
  isAllergen: 'isAllergen',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt'
} as const

export type ProductIngredientScalarFieldEnum = (typeof ProductIngredientScalarFieldEnum)[keyof typeof ProductIngredientScalarFieldEnum]


export const ProductAllergenScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  allergenType: 'allergenType',
  allergen: 'allergen',
  severity: 'severity',
  createdAt: 'createdAt'
} as const

export type ProductAllergenScalarFieldEnum = (typeof ProductAllergenScalarFieldEnum)[keyof typeof ProductAllergenScalarFieldEnum]


export const TableReservationScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  tableNumber: 'tableNumber',
  reservationDate: 'reservationDate',
  reservationTime: 'reservationTime',
  partySize: 'partySize',
  specialRequests: 'specialRequests',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TableReservationScalarFieldEnum = (typeof TableReservationScalarFieldEnum)[keyof typeof TableReservationScalarFieldEnum]


export const LocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  phone: 'phone',
  email: 'email',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LocationScalarFieldEnum = (typeof LocationScalarFieldEnum)[keyof typeof LocationScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  planName: 'planName',
  planType: 'planType',
  interval: 'interval',
  price: 'price',
  status: 'status',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  trialStart: 'trialStart',
  trialEnd: 'trialEnd',
  canceledAt: 'canceledAt',
  pauseUntil: 'pauseUntil',
  billingDayOfMonth: 'billingDayOfMonth',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const SubscriptionPaymentScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  amount: 'amount',
  status: 'status',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  gatewayTransactionId: 'gatewayTransactionId',
  retryCount: 'retryCount',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionPaymentScalarFieldEnum = (typeof SubscriptionPaymentScalarFieldEnum)[keyof typeof SubscriptionPaymentScalarFieldEnum]


export const SubscriptionChangeScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  changeType: 'changeType',
  oldValue: 'oldValue',
  newValue: 'newValue',
  effectiveDate: 'effectiveDate',
  createdAt: 'createdAt'
} as const

export type SubscriptionChangeScalarFieldEnum = (typeof SubscriptionChangeScalarFieldEnum)[keyof typeof SubscriptionChangeScalarFieldEnum]


export const AppointmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  staffId: 'staffId',
  serviceId: 'serviceId',
  appointmentDate: 'appointmentDate',
  duration: 'duration',
  status: 'status',
  notes: 'notes',
  cancellationReason: 'cancellationReason',
  canceledAt: 'canceledAt',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppointmentScalarFieldEnum = (typeof AppointmentScalarFieldEnum)[keyof typeof AppointmentScalarFieldEnum]


export const AppointmentReminderScalarFieldEnum = {
  id: 'id',
  appointmentId: 'appointmentId',
  reminderType: 'reminderType',
  reminderTime: 'reminderTime',
  sent: 'sent',
  sentAt: 'sentAt',
  createdAt: 'createdAt'
} as const

export type AppointmentReminderScalarFieldEnum = (typeof AppointmentReminderScalarFieldEnum)[keyof typeof AppointmentReminderScalarFieldEnum]


export const DigitalProductScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  fileUrl: 'fileUrl',
  downloadLimit: 'downloadLimit',
  expiresAfterDays: 'expiresAfterDays',
  licenseRequired: 'licenseRequired',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DigitalProductScalarFieldEnum = (typeof DigitalProductScalarFieldEnum)[keyof typeof DigitalProductScalarFieldEnum]


export const DigitalDownloadScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  orderId: 'orderId',
  digitalProductId: 'digitalProductId',
  downloadUrl: 'downloadUrl',
  downloadCount: 'downloadCount',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  lastDownloadedAt: 'lastDownloadedAt'
} as const

export type DigitalDownloadScalarFieldEnum = (typeof DigitalDownloadScalarFieldEnum)[keyof typeof DigitalDownloadScalarFieldEnum]


export const LicenseKeyScalarFieldEnum = {
  id: 'id',
  digitalProductId: 'digitalProductId',
  userId: 'userId',
  orderId: 'orderId',
  key: 'key',
  activationCount: 'activationCount',
  maxActivations: 'maxActivations',
  expiresAt: 'expiresAt',
  activatedAt: 'activatedAt',
  createdAt: 'createdAt'
} as const

export type LicenseKeyScalarFieldEnum = (typeof LicenseKeyScalarFieldEnum)[keyof typeof LicenseKeyScalarFieldEnum]


export const RentalScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  userId: 'userId',
  startDate: 'startDate',
  endDate: 'endDate',
  returnDate: 'returnDate',
  dailyRate: 'dailyRate',
  depositAmount: 'depositAmount',
  depositReturned: 'depositReturned',
  lateFee: 'lateFee',
  status: 'status',
  conditionBefore: 'conditionBefore',
  conditionAfter: 'conditionAfter',
  damageReport: 'damageReport',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RentalScalarFieldEnum = (typeof RentalScalarFieldEnum)[keyof typeof RentalScalarFieldEnum]


export const EventScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  eventDate: 'eventDate',
  eventTime: 'eventTime',
  venue: 'venue',
  venueAddress: 'venueAddress',
  capacity: 'capacity',
  ticketPrice: 'ticketPrice',
  earlyBirdPrice: 'earlyBirdPrice',
  earlyBirdUntil: 'earlyBirdUntil',
  imageUrl: 'imageUrl',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EventScalarFieldEnum = (typeof EventScalarFieldEnum)[keyof typeof EventScalarFieldEnum]


export const TicketScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  orderId: 'orderId',
  userId: 'userId',
  ticketType: 'ticketType',
  qrCode: 'qrCode',
  price: 'price',
  seatNumber: 'seatNumber',
  tableNumber: 'tableNumber',
  status: 'status',
  scannedAt: 'scannedAt',
  createdAt: 'createdAt'
} as const

export type TicketScalarFieldEnum = (typeof TicketScalarFieldEnum)[keyof typeof TicketScalarFieldEnum]


export const EventWaitlistScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  userId: 'userId',
  email: 'email',
  quantity: 'quantity',
  notified: 'notified',
  createdAt: 'createdAt'
} as const

export type EventWaitlistScalarFieldEnum = (typeof EventWaitlistScalarFieldEnum)[keyof typeof EventWaitlistScalarFieldEnum]


export const AbandonedCartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sessionId: 'sessionId',
  email: 'email',
  cartData: 'cartData',
  reminderCount: 'reminderCount',
  lastReminderAt: 'lastReminderAt',
  recovered: 'recovered',
  recoveredAt: 'recoveredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AbandonedCartScalarFieldEnum = (typeof AbandonedCartScalarFieldEnum)[keyof typeof AbandonedCartScalarFieldEnum]


export const SupportTicketScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orderId: 'orderId',
  subject: 'subject',
  description: 'description',
  status: 'status',
  priority: 'priority',
  assignedTo: 'assignedTo',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SupportTicketScalarFieldEnum = (typeof SupportTicketScalarFieldEnum)[keyof typeof SupportTicketScalarFieldEnum]


export const TicketMessageScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  userId: 'userId',
  adminId: 'adminId',
  message: 'message',
  attachments: 'attachments',
  createdAt: 'createdAt'
} as const

export type TicketMessageScalarFieldEnum = (typeof TicketMessageScalarFieldEnum)[keyof typeof TicketMessageScalarFieldEnum]


export const ProductQuestionScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  userId: 'userId',
  question: 'question',
  answer: 'answer',
  answeredBy: 'answeredBy',
  answeredAt: 'answeredAt',
  helpful: 'helpful',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductQuestionScalarFieldEnum = (typeof ProductQuestionScalarFieldEnum)[keyof typeof ProductQuestionScalarFieldEnum]


export const PosSessionScalarFieldEnum = {
  id: 'id',
  managerId: 'managerId',
  status: 'status',
  openedAt: 'openedAt',
  closedAt: 'closedAt',
  openingBalance: 'openingBalance',
  closingBalance: 'closingBalance',
  expectedCash: 'expectedCash',
  actualCash: 'actualCash',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PosSessionScalarFieldEnum = (typeof PosSessionScalarFieldEnum)[keyof typeof PosSessionScalarFieldEnum]


export const PosTransactionScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  orderId: 'orderId',
  transactionType: 'transactionType',
  paymentMethod: 'paymentMethod',
  subtotal: 'subtotal',
  tax: 'tax',
  discount: 'discount',
  total: 'total',
  cashAmount: 'cashAmount',
  cardAmount: 'cardAmount',
  customerEmail: 'customerEmail',
  customerName: 'customerName',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type PosTransactionScalarFieldEnum = (typeof PosTransactionScalarFieldEnum)[keyof typeof PosTransactionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

