/**
 * Comprehensive store type presets for client-side use
 * Each preset includes storeType, colors, and relevant feature flags
 */

export interface StorePreset {
  value: string;
  label: string;
  description: string;
  color: string;
  category: string;
  features: Record<string, boolean | string | number>;
}

export const STORE_PRESETS: StorePreset[] = [
  // ========== RESTAURANT & FOOD ==========
  {
    value: 'restaurant',
    label: 'Restaurant',
    description: 'Full-service restaurant with reservations, menu builder, and delivery',
    color: '25 95% 53%',
    category: 'Restaurant & Food',
    features: {
      storeType: 'restaurant',
      tableReservationsEnabled: true,
      menuBuilderEnabled: true,
      dietaryFiltersEnabled: true,
      prepTimeEnabled: true,
      deliveryTimeEnabled: true,
      ingredientListEnabled: true,
      allergenWarningsEnabled: true,
      mealComboBuilderEnabled: true,
      nutritionalInfoEnabled: true,
      orderSchedulingEnabled: true,
      tippingEnabled: true,
      loyaltyStampsEnabled: true,
      pickupEnabled: true,
      deliveryZonesEnabled: true,
      sameDayDeliveryEnabled: true,
      scheduledDeliveriesEnabled: true,
      posEnabled: true,
      employeeTimeTrackingEnabled: true,
    },
  },
  {
    value: 'cafe',
    label: 'Cafe',
    description: 'Coffee shop with online ordering and loyalty program',
    color: '35 80% 50%',
    category: 'Restaurant & Food',
    features: {
      storeType: 'cafe',
      menuBuilderEnabled: true,
      dietaryFiltersEnabled: true,
      prepTimeEnabled: true,
      mealComboBuilderEnabled: true,
      loyaltyStampsEnabled: true,
      pickupEnabled: true,
      orderSchedulingEnabled: true,
      tippingEnabled: true,
    },
  },
  {
    value: 'bakery',
    label: 'Bakery',
    description: 'Bakery with custom orders and dietary options',
    color: '340 75% 55%',
    category: 'Restaurant & Food',
    features: {
      storeType: 'bakery',
      menuBuilderEnabled: true,
      dietaryFiltersEnabled: true,
      ingredientListEnabled: true,
      allergenWarningsEnabled: true,
      madeToOrderItemsEnabled: true,
      customQuoteRequestsEnabled: true,
      productionStatusEnabled: true,
      pickupEnabled: true,
      orderSchedulingEnabled: true,
      preOrdersEnabled: true,
    },
  },
  {
    value: 'pizza',
    label: 'Pizza Shop',
    description: 'Pizza delivery with customization and tracking',
    color: '15 95% 50%',
    category: 'Restaurant & Food',
    features: {
      storeType: 'pizza',
      menuBuilderEnabled: true,
      mealComboBuilderEnabled: true,
      customizationOptionsEnabled: true,
      deliveryZonesEnabled: true,
      sameDayDeliveryEnabled: true,
      realTimeTrackingEnabled: true,
      deliveryDriverManagementEnabled: true,
      tipForDriverEnabled: true,
      orderSchedulingEnabled: true,
      pickupEnabled: true,
    },
  },
  {
    value: 'food-truck',
    label: 'Food Truck',
    description: 'Mobile food service with location tracking',
    color: '45 95% 55%',
    category: 'Restaurant & Food',
    features: {
      storeType: 'food-truck',
      menuBuilderEnabled: true,
      multiLocationEnabled: true,
      realTimeTrackingEnabled: true,
      pickupEnabled: true,
      orderSchedulingEnabled: true,
      posEnabled: true,
    },
  },

  // ========== RETAIL ==========
  {
    value: 'electronics',
    label: 'Electronics Store',
    description: 'Tech products with warranties and specifications',
    color: '221 83% 53%',
    category: 'Retail',
    features: {
      storeType: 'electronics',
      productVariantsEnabled: true,
      productComparisonEnabled: true,
      productQAEnabled: true,
      videoProductDemosEnabled: true,
      product360ViewsEnabled: true,
      shippingEnabled: true,
      advancedFilteringEnabled: true,
      barcodeQrScanningEnabled: true,
    },
  },
  {
    value: 'clothing',
    label: 'Clothing Store',
    description: 'Fashion retail with size guides and styling',
    color: '280 75% 60%',
    category: 'Retail',
    features: {
      storeType: 'clothing',
      productVariantsEnabled: true,
      productComparisonEnabled: true,
      wishlistEnabled: true,
      productQuickViewEnabled: true,
      imageZoomEnabled: true,
      socialSharingEnabled: true,
      shippingEnabled: true,
      pickupEnabled: true,
    },
  },
  {
    value: 'furniture',
    label: 'Furniture Store',
    description: 'Home furnishings with room planning and delivery',
    color: '35 80% 50%',
    category: 'Retail',
    features: {
      storeType: 'furniture',
      product360ViewsEnabled: true,
      arVrProductPreviewEnabled: true,
      deliveryZonesEnabled: true,
      scheduledDeliveriesEnabled: true,
      deliveryInstructionsEnabled: true,
      shippingEnabled: true,
      productComparisonEnabled: true,
    },
  },
  {
    value: 'books',
    label: 'Bookstore',
    description: 'Books with reviews and recommendations',
    color: '220 60% 45%',
    category: 'Retail',
    features: {
      storeType: 'books',
      reviewsEnabled: true,
      productComparisonEnabled: true,
      recentlyViewedEnabled: true,
      wishlistEnabled: true,
      advancedFilteringEnabled: true,
      shippingEnabled: true,
      pickupEnabled: true,
      preOrdersEnabled: true,
    },
  },
  {
    value: 'jewelry',
    label: 'Jewelry Store',
    description: 'Fine jewelry with customization and certificates',
    color: '50 80% 60%',
    category: 'Retail',
    features: {
      storeType: 'jewelry',
      customizationOptionsEnabled: true,
      madeToOrderItemsEnabled: true,
      customQuoteRequestsEnabled: true,
      product360ViewsEnabled: true,
      imageZoomEnabled: true,
      productComparisonEnabled: true,
      shippingEnabled: true,
      pickupEnabled: true,
    },
  },
  {
    value: 'general',
    label: 'General Store',
    description: 'Multi-category retail store',
    color: '221 83% 53%',
    category: 'Retail',
    features: {
      storeType: 'general',
      productVariantsEnabled: true,
      productCategoriesEnabled: true,
      reviewsEnabled: true,
      wishlistEnabled: true,
      shippingEnabled: true,
      pickupEnabled: true,
      advancedFilteringEnabled: true,
    },
  },

  // ========== SERVICE-BASED ==========
  {
    value: 'salon',
    label: 'Hair Salon',
    description: 'Beauty salon with appointments and service packages',
    color: '320 70% 60%',
    category: 'Service-Based',
    features: {
      storeType: 'salon',
      appointmentBookingEnabled: true,
      servicePackagesEnabled: true,
      staffManagementEnabled: true,
      serviceDurationEnabled: true,
      clientHistoryEnabled: true,
      recurringAppointmentsEnabled: true,
      serviceAddonsEnabled: true,
      cancellationPoliciesEnabled: true,
      serviceRemindersEnabled: true,
      beforeAfterPhotosEnabled: true,
      advancedCalendarEnabled: true,
      bufferTimesEnabled: true,
      waitingListsEnabled: true,
      staffAvailabilityEnabled: true,
    },
  },
  {
    value: 'spa',
    label: 'Spa & Wellness',
    description: 'Spa services with packages and memberships',
    color: '180 50% 55%',
    category: 'Service-Based',
    features: {
      storeType: 'spa',
      appointmentBookingEnabled: true,
      servicePackagesEnabled: true,
      staffManagementEnabled: true,
      resourceBookingEnabled: true,
      serviceAddonsEnabled: true,
      cancellationPoliciesEnabled: true,
      serviceRemindersEnabled: true,
      beforeAfterPhotosEnabled: true,
      advancedCalendarEnabled: true,
      bufferTimesEnabled: true,
      subscriptionPlansEnabled: true,
      pauseResumeSubscriptionsEnabled: true,
    },
  },
  {
    value: 'fitness',
    label: 'Fitness Studio',
    description: 'Gym with classes and memberships',
    color: '10 85% 55%',
    category: 'Service-Based',
    features: {
      storeType: 'fitness',
      appointmentBookingEnabled: true,
      classWorkshopBookingsEnabled: true,
      subscriptionPlansEnabled: true,
      recurringBillingEnabled: true,
      planUpgradesDowngradesEnabled: true,
      pauseResumeSubscriptionsEnabled: true,
      subscriptionDashboardEnabled: true,
      staffAvailabilityEnabled: true,
      waitingListsEnabled: true,
      resourceBookingEnabled: true,
    },
  },
  {
    value: 'medical',
    label: 'Medical Practice',
    description: 'Healthcare with appointments and patient management',
    color: '200 80% 50%',
    category: 'Service-Based',
    features: {
      storeType: 'medical',
      appointmentBookingEnabled: true,
      advancedCalendarEnabled: true,
      bufferTimesEnabled: true,
      waitingListsEnabled: true,
      intakeFormsEnabled: true,
      videoConsultationsEnabled: true,
      appointmentRemindersEnabled: true,
      noShowTrackingEnabled: true,
      staffAvailabilityEnabled: true,
      clientHistoryEnabled: true,
      cancellationPoliciesEnabled: true,
    },
  },
  {
    value: 'legal',
    label: 'Legal Services',
    description: 'Law firm with consultations and document services',
    color: '240 60% 50%',
    category: 'Service-Based',
    features: {
      storeType: 'legal',
      appointmentBookingEnabled: true,
      videoConsultationsEnabled: true,
      intakeFormsEnabled: true,
      servicePackagesEnabled: true,
      customQuoteRequestsEnabled: true,
      advancedCalendarEnabled: true,
      bufferTimesEnabled: true,
      appointmentRemindersEnabled: true,
      clientHistoryEnabled: true,
    },
  },
  {
    value: 'cleaning',
    label: 'Cleaning Service',
    description: 'Home/office cleaning with scheduling',
    color: '200 70% 60%',
    category: 'Service-Based',
    features: {
      storeType: 'cleaning',
      appointmentBookingEnabled: true,
      serviceAreasEnabled: true,
      servicePackagesEnabled: true,
      recurringAppointmentsEnabled: true,
      serviceAddonsEnabled: true,
      deliveryPickupSchedulingEnabled: true,
      advancedCalendarEnabled: true,
      serviceRemindersEnabled: true,
    },
  },

  // ========== SUBSCRIPTION ==========
  {
    value: 'saas',
    label: 'SaaS Business',
    description: 'Software as a Service with subscriptions',
    color: '221 83% 53%',
    category: 'Subscription',
    features: {
      storeType: 'saas',
      subscriptionPlansEnabled: true,
      recurringBillingEnabled: true,
      trialPeriodsEnabled: true,
      planUpgradesDowngradesEnabled: true,
      pauseResumeSubscriptionsEnabled: true,
      subscriptionDashboardEnabled: true,
      prorationEnabled: true,
      dunningManagementEnabled: true,
      familyGroupPlansEnabled: true,
      instantDigitalDeliveryEnabled: true,
      licenseKeyManagementEnabled: true,
    },
  },
  {
    value: 'subscription-box',
    label: 'Subscription Box',
    description: 'Monthly subscription boxes',
    color: '280 75% 60%',
    category: 'Subscription',
    features: {
      storeType: 'subscription-box',
      subscriptionPlansEnabled: true,
      recurringBillingEnabled: true,
      planUpgradesDowngradesEnabled: true,
      pauseResumeSubscriptionsEnabled: true,
      subscriptionDashboardEnabled: true,
      giftSubscriptionsEnabled: true,
      shippingEnabled: true,
      scheduledDeliveriesEnabled: true,
      productVariantsEnabled: true,
    },
  },
  {
    value: 'membership',
    label: 'Membership Club',
    description: 'Membership-based business with tiers',
    color: '25 95% 53%',
    category: 'Subscription',
    features: {
      storeType: 'membership',
      subscriptionPlansEnabled: true,
      recurringBillingEnabled: true,
      planUpgradesDowngradesEnabled: true,
      familyGroupPlansEnabled: true,
      subscriptionDashboardEnabled: true,
      customerGroupsEnabled: true,
      loyaltyProgramEnabled: true,
    },
  },

  // ========== DIGITAL PRODUCTS ==========
  {
    value: 'digital-products',
    label: 'Digital Products',
    description: 'Software, courses, and digital downloads',
    color: '221 83% 53%',
    category: 'Digital Products',
    features: {
      storeType: 'digital-products',
      instantDigitalDeliveryEnabled: true,
      licenseKeyManagementEnabled: true,
      downloadLimitsEnabled: true,
      fileHostingEnabled: true,
      courseProgressTrackingEnabled: true,
      accessExpirationEnabled: true,
      bulkLicensePurchasesEnabled: true,
      affiliateSystemEnabled: true,
      softwareUpdatesEnabled: true,
      previewFreeSamplesEnabled: true,
    },
  },
  {
    value: 'online-courses',
    label: 'Online Courses',
    description: 'Educational courses with progress tracking',
    color: '200 80% 50%',
    category: 'Digital Products',
    features: {
      storeType: 'online-courses',
      instantDigitalDeliveryEnabled: true,
      courseProgressTrackingEnabled: true,
      accessExpirationEnabled: true,
      subscriptionPlansEnabled: true,
      previewFreeSamplesEnabled: true,
      videoProductDemosEnabled: true,
    },
  },
  {
    value: 'software',
    label: 'Software Store',
    description: 'Software sales with licenses and updates',
    color: '221 83% 53%',
    category: 'Digital Products',
    features: {
      storeType: 'software',
      instantDigitalDeliveryEnabled: true,
      licenseKeyManagementEnabled: true,
      bulkLicensePurchasesEnabled: true,
      softwareUpdatesEnabled: true,
      previewFreeSamplesEnabled: true,
      subscriptionPlansEnabled: true,
    },
  },

  // ========== RENTAL ==========
  {
    value: 'equipment-rental',
    label: 'Equipment Rental',
    description: 'Tool and equipment rentals',
    color: '35 80% 50%',
    category: 'Rental',
    features: {
      storeType: 'equipment-rental',
      rentalDurationSelectionEnabled: true,
      dateRangePickerEnabled: true,
      availabilityCalendarEnabled: true,
      depositSecurityHoldEnabled: true,
      lateReturnFeesEnabled: true,
      deliveryPickupSchedulingEnabled: true,
      damageReportingEnabled: true,
      rentalAgreementsEnabled: true,
      maintenanceSchedulingEnabled: true,
      rentalWaitingListsEnabled: true,
    },
  },
  {
    value: 'party-rental',
    label: 'Party Rental',
    description: 'Party supplies and event equipment',
    color: '320 70% 60%',
    category: 'Rental',
    features: {
      storeType: 'party-rental',
      rentalDurationSelectionEnabled: true,
      dateRangePickerEnabled: true,
      availabilityCalendarEnabled: true,
      depositSecurityHoldEnabled: true,
      deliveryPickupSchedulingEnabled: true,
      scheduledDeliveriesEnabled: true,
      rentalAgreementsEnabled: true,
      eventPackagesEnabled: true,
    },
  },

  // ========== MARKETPLACE ==========
  {
    value: 'marketplace',
    label: 'Marketplace',
    description: 'Multi-vendor marketplace platform',
    color: '221 83% 53%',
    category: 'Marketplace',
    features: {
      storeType: 'marketplace',
      marketplaceEnabled: true,
      vendorRegistrationEnabled: true,
      commissionManagementEnabled: true,
      vendorDashboardEnabled: true,
      vendorReviewsEnabled: true,
      splitPaymentsEnabled: true,
      vendorAnalyticsEnabled: true,
      vendorStorefrontsEnabled: true,
      vendorMessagingEnabled: true,
      disputeResolutionEnabled: true,
    },
  },

  // ========== EVENTS & TICKETS ==========
  {
    value: 'events',
    label: 'Event & Tickets',
    description: 'Event management and ticket sales',
    color: '280 75% 60%',
    category: 'Events',
    features: {
      storeType: 'events',
      eventCalendarEnabled: true,
      seatTableSelectionEnabled: true,
      ticketTypesEnabled: true,
      eventCapacityManagementEnabled: true,
      earlyBirdPricingEnabled: true,
      groupDiscountsEnabled: true,
      eventRemindersEnabled: true,
      qrCodeTicketsEnabled: true,
      eventWaitlistEnabled: true,
      eventHostingEnabled: true,
      eventPackagesEnabled: true,
    },
  },

  // ========== LOCAL DELIVERY ==========
  {
    value: 'local-delivery',
    label: 'Local Delivery',
    description: 'Local delivery service with zones',
    color: '25 95% 53%',
    category: 'Delivery',
    features: {
      storeType: 'local-delivery',
      deliveryZonesEnabled: true,
      deliveryFeeCalculatorEnabled: true,
      sameDayDeliveryEnabled: true,
      deliveryDriverManagementEnabled: true,
      realTimeTrackingEnabled: true,
      deliveryInstructionsEnabled: true,
      tipForDriverEnabled: true,
      multiAddressOrdersEnabled: true,
      scheduledDeliveriesEnabled: true,
      minimumOrderFreeDeliveryEnabled: true,
    },
  },

  // ========== CRAFT & HANDMADE ==========
  {
    value: 'handmade',
    label: 'Handmade & Crafts',
    description: 'Handmade products with customization',
    color: '340 75% 55%',
    category: 'Craft',
    features: {
      storeType: 'handmade',
      customizationOptionsEnabled: true,
      madeToOrderItemsEnabled: true,
      customQuoteRequestsEnabled: true,
      productionStatusEnabled: true,
      materialsOriginInfoEnabled: true,
      artistBrandStoriesEnabled: true,
      commissionRequestsEnabled: true,
      limitedEditionsEnabled: true,
      inProgressPhotosEnabled: true,
      backorderSupportEnabled: true,
    },
  },

  // ========== B2B/WHOLESALE ==========
  {
    value: 'b2b',
    label: 'B2B/Wholesale',
    description: 'Business-to-business wholesale platform',
    color: '221 83% 53%',
    category: 'B2B',
    features: {
      storeType: 'b2b',
      wholesalePricingTiersEnabled: true,
      businessAccountRegistrationEnabled: true,
      creditTermsEnabled: true,
      poSupportEnabled: true,
      bulkOrderFormsEnabled: true,
      minimumOrderQuantitiesEnabled: true,
      catalogPricingEnabled: true,
      taxExemptHandlingEnabled: true,
      salesRepAssignmentEnabled: true,
      creditLimitsEnabled: true,
      customerGroupsEnabled: true,
      advancedFilteringEnabled: true,
    },
  },
];

/**
 * Get preset by value
 */
export function getPresetByValue(value: string): StorePreset | undefined {
  return STORE_PRESETS.find(preset => preset.value === value);
}

/**
 * Get presets by category
 */
export function getPresetsByCategory(category: string): StorePreset[] {
  return STORE_PRESETS.filter(preset => preset.category === category);
}

/**
 * Get all categories
 */
export function getCategories(): string[] {
  return Array.from(new Set(STORE_PRESETS.map(preset => preset.category)));
}
