'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Play, Pause, SkipBack, SkipForward, Check, Wand2 } from 'lucide-react';
import type { TrackItem } from '@makeyourmusic/shared';
import { usePlayerStore } from '@/lib/store/playerStore';
import { useAuthStore } from '@/lib/store/authStore';
import { track } from '@/lib/analytics';
import api from '@/lib/api';
import { t } from '@/lib/i18n';

const PROMPT_CYCLE = [
  'rainy tokyo lo-fi for late-night coding',
  "warm jazz piano, softly mic'd, 3am",
  'dreampop on a beach in 1986',
  'instrumental synthwave for a long drive',
  'ambient folk with cassette tape hiss',
  'garage rock about losing your apartment keys',
];

const MARQUEE_GENRES = [
  'Synthwave', 'Lo-Fi', 'Jazz', 'Ambient', 'Drum & Bass', 'K-Pop',
  'Garage', 'Folk', 'Trap', 'Bossa Nova', 'Indie', 'Cinematic',
  'House', 'Phonk', 'Bluegrass', 'Afrobeat', 'Vapor', 'Drill',
];

const FAQ_ITEMS: ReadonlyArray<readonly [string, string]> = [
  ['Is it really AI-generated?', 'Every track is generated by Minimax (with Suno as a fallback). Cover art and preview videos are AI too. Humans curate, agents create.'],
  ['Can I download and keep tracks?', 'Yes — Premium subscribers get offline downloads and lossless audio. Sync licensing and stems are sold à la carte for filmmakers and producers.'],
  ['Who owns the music?', "The agent's owner does. Listeners get a streaming license. Sync buyers get a clearance certificate. We never train on your prompts."],
  ['What about copyright?', 'Tracks are filtered against major-label fingerprints before publishing, and we honor DMCA takedowns within 24 hours.'],
];

const FALLBACK_GENRES: Array<{ name: string; count: string; hue: number; slug: string }> = [
  { name: 'Lo-Fi', count: '12,418', hue: 290, slug: 'lo-fi' },
  { name: 'Synthwave', count: '8,902', hue: 264, slug: 'synthwave' },
  { name: 'Jazz', count: '5,621', hue: 32, slug: 'jazz' },
  { name: 'Ambient', count: '9,114', hue: 180, slug: 'ambient' },
  { name: 'Hip-Hop', count: '7,883', hue: 12, slug: 'hip-hop' },
  { name: 'Electronic', count: '14,206', hue: 200, slug: 'electronic' },
  { name: 'Folk', count: '3,344', hue: 140, slug: 'folk' },
  { name: 'Drum & Bass', count: '4,712', hue: 312, slug: 'drum-and-bass' },
];

function PlayGlyph({ size = 14 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" aria-hidden>
      <path d="M3 1.5v9l8-4.5z" fill="currentColor" />
    </svg>
  );
}

// ────────────────────────────────────────────────────────────────────
// Spectrum / waveform — animates while a track is playing in the store
// ────────────────────────────────────────────────────────────────────
function Spectrum({ live, bars = 42, className = '' }: { live: boolean; bars?: number; className?: string }) {
  const [t, setT] = useState(0);
  useEffect(() => {
    if (!live) return;
    let raf = 0;
    const loop = () => {
      setT((p) => p + 1);
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(raf);
  }, [live]);
  return (
    <div className={`flex items-end gap-[2px] h-9 w-full ${className}`}>
      {Array.from({ length: bars }).map((_, i) => {
        const v = live
          ? Math.abs(Math.sin(t / 14 + i * 0.45) * 0.55 + Math.sin(t / 9 + i * 0.12) * 0.4) * 100
          : 30 + ((i * 13) % 50);
        const color = i % 5 === 0 ? 'var(--brand-3, #2dd4bf)' : i % 3 === 0 ? 'var(--brand)' : 'var(--brand-2)';
        return (
          <span
            key={i}
            className="flex-1 min-w-[2px] rounded-t-[2px] opacity-85 transition-[height] duration-[120ms] ease-out"
            style={{ height: `${10 + v * 0.8}%`, background: color }}
          />
        );
      })}
    </div>
  );
}

function SpectrumLarge({ live }: { live: boolean }) {
  const [t, setT] = useState(0);
  useEffect(() => {
    let raf = 0;
    const loop = () => {
      setT((p) => p + 1);
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(raf);
  }, []);
  const bars = 80;
  return (
    <div className="flex items-end gap-[3px] h-[220px] w-full mt-12">
      {Array.from({ length: bars }).map((_, i) => {
        const dist = Math.abs(i - bars / 2) / (bars / 2);
        const env = 1 - dist * dist * 0.55;
        const v = live
          ? Math.abs(Math.sin(t / 12 + i * 0.32) * 0.5 + Math.sin(t / 7 + i * 0.09) * 0.5) * env
          : Math.abs(Math.sin(i * 0.32) * 0.5 + Math.sin(i * 0.09) * 0.5) * env;
        const h = 14 + v * 86;
        const color = i % 9 === 0 ? 'var(--brand-3, #2dd4bf)' : i % 4 === 0 ? 'var(--brand)' : 'var(--brand-2)';
        return (
          <span
            key={i}
            className="flex-1 min-w-[2px] rounded-t-[4px] opacity-90 transition-[height] duration-[120ms] ease-out"
            style={{ height: `${h}%`, background: color, boxShadow: `0 0 20px ${color}` }}
          />
        );
      })}
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Procedural cover art (when a track has no coverArt)
// ────────────────────────────────────────────────────────────────────
function CoverArt({ seed = '', src }: { seed?: string; src?: string | null }) {
  const hue = useMemo(() => {
    let h = 0;
    for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) % 360;
    return h || 290;
  }, [seed]);

  if (src) {
    return <img src={src} alt="" className="absolute inset-0 w-full h-full object-cover" />;
  }
  return (
    <div
      className="absolute inset-0"
      style={{
        background: `radial-gradient(120% 90% at 25% 20%, hsl(${hue} 90% 65%) 0%, hsl(${(hue + 60) % 360} 70% 35%) 45%, #0a0a0d 100%)`,
      }}
    >
      <div className="absolute right-[12%] top-[12%]">
        <span className="absolute right-0 top-0 w-10 h-10 rounded-full border-[1.5px] border-white/35" />
        <span className="absolute -right-2.5 -top-2.5 w-[60px] h-[60px] rounded-full border-[1.5px] border-white/35 opacity-60" />
        <span className="absolute -right-[22px] -top-[22px] w-[84px] h-[84px] rounded-full border-[1.5px] border-white/35 opacity-30" />
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Hero backdrop (gradient halos + grid + noise)
// ────────────────────────────────────────────────────────────────────
function HeroBackdrop({ rays = false }: { rays?: boolean }) {
  return (
    <>
      <div
        className="absolute inset-0 -z-30"
        style={{
          background:
            'radial-gradient(60% 50% at 18% 0%, color-mix(in srgb, var(--brand-2) 36%, transparent) 0%, transparent 60%), radial-gradient(50% 45% at 82% 6%, color-mix(in srgb, var(--brand) 30%, transparent) 0%, transparent 60%), radial-gradient(70% 50% at 50% 95%, color-mix(in srgb, var(--brand-3, #2dd4bf) 18%, transparent) 0%, transparent 60%)',
        }}
      />
      <div
        className="absolute inset-0 -z-20"
        style={{
          backgroundImage:
            'linear-gradient(rgba(255,255,255,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.05) 1px, transparent 1px)',
          backgroundSize: '56px 56px',
          maskImage: 'radial-gradient(70% 60% at 50% 30%, black 0%, transparent 80%)',
          WebkitMaskImage: 'radial-gradient(70% 60% at 50% 30%, black 0%, transparent 80%)',
        }}
      />
      {rays && (
        <div
          className="absolute -top-[10%] left-0 right-0 bottom-0 -z-20 opacity-70"
          style={{
            background:
              'conic-gradient(from 200deg at 50% 0%, transparent 0deg, color-mix(in srgb, var(--brand) 18%, transparent) 30deg, transparent 60deg, color-mix(in srgb, var(--brand-2) 14%, transparent) 95deg, transparent 130deg)',
            filter: 'blur(40px)',
          }}
        />
      )}
    </>
  );
}

// ────────────────────────────────────────────────────────────────────
// Hero — interactable Deck player. Click play => actually plays a track.
// ────────────────────────────────────────────────────────────────────
function HeroDeck({ tracks }: { tracks: TrackItem[] }) {
  const { currentTrack, isPlaying, playTrack, togglePlay, nextTrack, prevTrack, progress, duration } = usePlayerStore();
  const [autoIdx, setAutoIdx] = useState(0);

  // When nothing is playing, auto-cycle the highlighted track in the deck
  useEffect(() => {
    if (currentTrack || tracks.length === 0) return;
    const i = setInterval(() => setAutoIdx((x) => (x + 1) % tracks.length), 3500);
    return () => clearInterval(i);
  }, [currentTrack, tracks.length]);

  const visibleQueue = tracks.slice(0, 4);
  const featured = currentTrack ?? tracks[autoIdx];
  const fmt = (s: number) => {
    if (!s || !Number.isFinite(s)) return '0:00';
    const m = Math.floor(s / 60);
    const r = Math.floor(s % 60);
    return `${m}:${r.toString().padStart(2, '0')}`;
  };
  const progressPct = duration > 0 ? Math.min(100, (progress / duration) * 100) : 32;

  const handlePlay = () => {
    if (!featured) return;
    if (currentTrack && currentTrack.id === featured.id) {
      togglePlay();
    } else {
      playTrack(featured, tracks);
    }
  };

  return (
    <div
      className="relative rounded-[22px] p-4 sm:p-5 overflow-hidden"
      style={{
        background: 'linear-gradient(180deg, var(--bg-elev-2), var(--bg-elev-1))',
        border: '1px solid var(--stroke-strong)',
        boxShadow: '0 30px 60px -30px rgba(0,0,0,0.6)',
      }}
    >
      <div className="flex items-center justify-between mb-3.5">
        <div
          className="text-[10px] font-bold uppercase px-2.5 py-1 rounded"
          style={{ letterSpacing: '0.25em', color: 'var(--brand)', background: 'var(--brand-soft)' }}
        >
          NOW PLAYING · STATION 88.1
        </div>
        <div className="flex gap-1">
          <span className="w-2 h-2 rounded-full" style={{ background: '#2dd4bf', boxShadow: '0 0 8px #2dd4bf' }} />
          <span className="w-2 h-2 rounded-full" style={{ background: '#f59e0b', boxShadow: '0 0 8px #f59e0b' }} />
          <span className="w-2 h-2 rounded-full bg-white/15" />
        </div>
      </div>

      <div className="grid grid-cols-[100px_1fr] sm:grid-cols-[130px_1fr] gap-4">
        <div className="relative w-[100px] h-[100px] sm:w-[130px] sm:h-[130px] rounded-[14px] overflow-hidden">
          <CoverArt seed={featured?.title || 'demo'} src={featured?.coverArt ?? undefined} />
        </div>
        <div className="min-w-0 flex flex-col gap-1">
          <div className="font-display font-extrabold text-base sm:text-lg leading-tight truncate">
            {featured?.title ?? 'Rain on Neon Glass'}
          </div>
          <div className="text-[13px] truncate" style={{ color: 'var(--text-soft)' }}>
            {featured?.agent?.name ?? 'Midnight Lo-Fi Engine'}
          </div>
          <div className="text-[11.5px] mb-2.5 truncate" style={{ color: 'var(--text-mute)' }}>
            {featured?.genre?.name ?? 'cinematic synthwave'}
          </div>
          <Spectrum live={isPlaying && !!currentTrack} bars={36} />
          <div className="flex items-center gap-2 mt-auto pt-2">
            <button
              onClick={prevTrack}
              disabled={!currentTrack}
              aria-label="Previous track"
              className="p-1.5 transition-colors disabled:opacity-30"
              style={{ color: 'var(--text-soft)' }}
            >
              <SkipBack className="w-4 h-4" fill="currentColor" />
            </button>
            <button
              onClick={handlePlay}
              aria-label={isPlaying && currentTrack?.id === featured?.id ? 'Pause' : 'Play'}
              className="w-[42px] h-[42px] rounded-full inline-flex items-center justify-center text-white border-0 cursor-pointer transition-all"
              style={{
                background: 'var(--brand)',
                boxShadow: '0 12px 26px -8px var(--brand-glow)',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'scale(1.05)';
                e.currentTarget.style.background = 'var(--brand-strong)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'scale(1)';
                e.currentTarget.style.background = 'var(--brand)';
              }}
            >
              {isPlaying && currentTrack?.id === featured?.id ? (
                <Pause className="w-4 h-4" fill="currentColor" />
              ) : (
                <PlayGlyph size={14} />
              )}
            </button>
            <button
              onClick={nextTrack}
              disabled={!currentTrack}
              aria-label="Next track"
              className="p-1.5 transition-colors disabled:opacity-30"
              style={{ color: 'var(--text-soft)' }}
            >
              <SkipForward className="w-4 h-4" fill="currentColor" />
            </button>
            <div className="flex-1 min-w-0 ml-1">
              <div className="h-1 rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,0.08)' }}>
                <div
                  className="h-full rounded-full transition-[width] duration-100"
                  style={{ width: `${progressPct}%`, background: 'var(--aurora)' }}
                />
              </div>
              <div
                className="flex justify-between text-[10.5px] mt-1 tabular-nums"
                style={{ color: 'var(--text-mute)' }}
              >
                <span>{currentTrack ? fmt(progress) : '1:24'}</span>
                <span>{featured?.duration ? fmt(featured.duration) : '3:48'}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-4 pt-3 border-t flex flex-col gap-0.5" style={{ borderColor: 'var(--stroke)' }}>
        {visibleQueue.map((track, i) => {
          const isNow = currentTrack ? currentTrack.id === track.id : i === autoIdx % visibleQueue.length;
          return (
            <button
              key={track.id}
              onClick={() => playTrack(track, tracks)}
              className="grid grid-cols-[24px_1fr_auto] items-center gap-2.5 px-2 py-1.5 rounded-lg text-[12.5px] text-left transition-colors hover:bg-white/[0.04]"
              style={isNow ? { background: 'var(--brand-soft)' } : undefined}
            >
              <span
                className="text-[11px] tabular-nums"
                style={{ color: isNow ? 'var(--brand)' : 'var(--text-faint)' }}
              >
                {String(i + 1).padStart(2, '0')}
              </span>
              <span className="truncate">{track.title}</span>
              <span className="text-[11px] tabular-nums" style={{ color: 'var(--text-mute)' }}>
                {fmt(track.duration)}
              </span>
            </button>
          );
        })}
        {visibleQueue.length === 0 && (
          <div className="px-2 py-3 text-xs" style={{ color: 'var(--text-mute)' }}>
            Loading queue…
          </div>
        )}
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Hero — Spectrum (centered) layout
// ────────────────────────────────────────────────────────────────────
function HeroSpectrum({ tracks }: { tracks: TrackItem[] }) {
  const { isPlaying, playTrack } = usePlayerStore();
  const router = useRouter();
  const startListening = () => {
    const first = tracks[0];
    if (first) playTrack(first, tracks);
  };
  const makeSong = () => {
    track('landing_cta_click', { surface: 'hero_spectrum' });
    router.push('/create');
  };
  return (
    <div className="relative isolate overflow-hidden" style={{ padding: '140px 0 90px' }}>
      <HeroBackdrop rays />
      <div className="relative max-w-[1100px] mx-auto px-6 grid place-items-center text-center gap-12">
        <div className="w-full">
          <span
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
            style={{
              background: 'rgba(255,255,255,0.04)',
              borderColor: 'var(--stroke)',
              color: 'var(--text-soft)',
              letterSpacing: '0.02em',
            }}
          >
            <span
              className="w-1.5 h-1.5 rounded-full"
              style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }}
            />
            Streaming, but it writes itself
          </span>
          <h1
            className="font-display font-extrabold m-0 mb-5"
            style={{ fontSize: 'clamp(3rem, 8vw, 6rem)', lineHeight: 1.02, letterSpacing: '-0.035em', textWrap: 'balance' }}
          >
            Sound that <span className="aurora-text">writes itself.</span>
          </h1>
          <p
            className="mx-auto m-0 mb-8 max-w-[560px]"
            style={{ fontSize: 'clamp(1.05rem, 1.4vw, 1.18rem)', color: 'var(--text-soft)', lineHeight: 1.55 }}
          >
            A music app where the catalog never ends. AI agents drop new tracks every minute — across every mood,
            every genre, every weird little niche.
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            <button onClick={makeSong} className="mym-cta">
              <Wand2 className="w-4 h-4" /> {t('landing.primaryCta')}
            </button>
            <button onClick={startListening} className="mym-ghost">
              <PlayGlyph /> {t('landing.secondaryCta')}
            </button>
            <Link href="#how" className="mym-ghost" style={{ opacity: 0.7 }}>
              See how it works
            </Link>
          </div>
        </div>

        <div className="w-full max-w-[1000px]">
          <SpectrumLarge live={isPlaying} />
          <div className="flex flex-wrap justify-center gap-2.5 mt-7">
            {['rainy tokyo lo-fi', 'garage rock', 'dreampop', 'deep house', 'ambient folk', 'synthwave', 'cinematic', 'afro-house'].map(
              (g) => (
                <span
                  key={g}
                  className="text-[12.5px] font-semibold px-3.5 py-1.5 rounded-full border"
                  style={{
                    background: 'rgba(255,255,255,0.05)',
                    borderColor: 'var(--stroke)',
                    color: 'var(--text-soft)',
                  }}
                >
                  {g}
                </span>
              ),
            )}
          </div>
        </div>

        <div className="mt-2 grid grid-cols-2 sm:grid-cols-4 gap-4 w-full max-w-[1000px]">
          {[
            ['2.1M', 'listeners'],
            ['14.6K', 'AI agents publishing'],
            ['84K+', 'new tracks daily'],
            ['130+', 'genres & niches'],
          ].map(([n, l]) => (
            <div
              key={l}
              className="text-center p-6 rounded-[14px] border"
              style={{ background: 'rgba(255,255,255,0.02)', borderColor: 'var(--stroke)' }}
            >
              <div className="font-display font-extrabold text-[32px]" style={{ letterSpacing: '-0.02em' }}>
                {n}
              </div>
              <div className="text-[12.5px] mt-1" style={{ color: 'var(--text-mute)' }}>
                {l}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Marquee strip
// ────────────────────────────────────────────────────────────────────
function MarqueeStrip() {
  return (
    <div
      className="my-6 py-4 overflow-hidden whitespace-nowrap relative"
      style={{
        borderTop: '1px solid var(--stroke)',
        borderBottom: '1px solid var(--stroke)',
        background: 'linear-gradient(90deg, var(--bg) 0%, transparent 5%, transparent 95%, var(--bg) 100%)',
      }}
      aria-hidden
    >
      <div className="inline-flex gap-10 pr-10 mym-marquee-track">
        {[...MARQUEE_GENRES, ...MARQUEE_GENRES].map((g, i) => (
          <span key={i} className="inline-flex items-center gap-2.5 font-display font-bold text-[16px]" style={{ color: 'var(--text-soft)' }}>
            <span
              className="w-1.5 h-1.5 rounded-full inline-block"
              style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }}
            />
            {g}
          </span>
        ))}
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Discover grid — uses real tracks; clicking play actually plays
// ────────────────────────────────────────────────────────────────────
function DiscoverGrid({ tracks }: { tracks: TrackItem[] }) {
  const { currentTrack, isPlaying, playTrack, togglePlay } = usePlayerStore();
  const handlePlay = (track: TrackItem) => {
    if (currentTrack?.id === track.id) togglePlay();
    else playTrack(track, tracks);
  };

  return (
    <section id="discover" className="max-w-[1240px] mx-auto px-5 sm:px-6 py-14 sm:py-20 md:py-24">
      <div className="flex justify-between items-end gap-6 flex-wrap mb-9 sm:mb-12 md:mb-14">
        <div className="max-w-[720px]">
          <span
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
            style={{
              background: 'rgba(255,255,255,0.04)',
              borderColor: 'var(--stroke)',
              color: 'var(--text-soft)',
            }}
          >
            <span
              className="w-1.5 h-1.5 rounded-full"
              style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }}
            />
            Discover
          </span>
          <h2
            className="font-display font-extrabold m-0 mb-4"
            style={{ fontSize: 'clamp(2.2rem, 4.4vw, 3.4rem)', lineHeight: 1.05, letterSpacing: '-0.03em' }}
          >
            Pulled fresh from the<br />
            <span className="aurora-text">infinite catalog.</span>
          </h2>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
        {tracks.slice(0, 8).map((t, i) => {
          const isThis = currentTrack?.id === t.id;
          return (
            <article
              key={t.id}
              className="rounded-[14px] p-3 border transition-transform hover:-translate-y-0.5"
              style={{
                background: 'var(--bg-elev-2)',
                borderColor: 'var(--stroke)',
              }}
            >
              <Link href={`/track/${t.slug}`} className="block">
                <div className="relative aspect-square rounded-[10px] overflow-hidden mb-3 group">
                  <CoverArt seed={t.title} src={t.coverArt} />
                  <button
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      handlePlay(t);
                    }}
                    aria-label={isThis && isPlaying ? 'Pause' : 'Play'}
                    className="absolute bottom-2.5 right-2.5 w-10 h-10 rounded-full inline-flex items-center justify-center text-white opacity-0 translate-y-2 group-hover:opacity-100 group-hover:translate-y-0 transition-all"
                    style={{ background: 'var(--brand)', boxShadow: '0 12px 26px -8px var(--brand-glow)' }}
                  >
                    {isThis && isPlaying ? <Pause className="w-4 h-4" fill="currentColor" /> : <PlayGlyph />}
                  </button>
                  {i === 0 && (
                    <span
                      className="absolute top-2 left-2 text-[10.5px] font-extrabold px-2 py-1 rounded-full text-white"
                      style={{ background: 'var(--brand)', letterSpacing: '0.04em' }}
                    >
                      #1
                    </span>
                  )}
                </div>
                <div
                  className="font-display font-bold text-[14.5px] truncate mb-0.5"
                  style={{ color: isThis ? 'var(--brand)' : 'var(--text)' }}
                >
                  {t.title}
                </div>
                <div className="text-xs truncate" style={{ color: 'var(--text-soft)' }}>
                  {t.agent?.name ?? 'AI Agent'}
                </div>
                <div className="flex justify-between gap-2 mt-1.5">
                  <span className="text-[11px] truncate" style={{ color: 'var(--text-mute)' }}>
                    {t.genre?.name ?? ''}
                  </span>
                </div>
              </Link>
            </article>
          );
        })}
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────────────
// How it works — three steps
// ────────────────────────────────────────────────────────────────────
function HowItWorks() {
  const router = useRouter();
  const [text, setText] = useState('');
  const [userTyped, setUserTyped] = useState(false);
  const idxRef = useRef(0);
  const charRef = useRef(0);
  useEffect(() => {
    if (userTyped) return;
    const tick = setInterval(() => {
      const target = PROMPT_CYCLE[idxRef.current % PROMPT_CYCLE.length] ?? '';
      charRef.current += 1;
      if (charRef.current <= target.length) {
        setText(target.slice(0, charRef.current));
      } else if (charRef.current >= target.length + 18) {
        charRef.current = 0;
        idxRef.current += 1;
      }
    }, 55);
    return () => clearInterval(tick);
  }, [userTyped]);

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    const value = text.trim();
    track('prompt_typed', { surface: 'howitworks', length: value.length });
    router.push(value ? `/create?prompt=${encodeURIComponent(value)}` : '/create');
  };

  return (
    <section id="how" className="max-w-[1240px] mx-auto px-5 sm:px-6 py-14 sm:py-20 md:py-24">
      <div className="max-w-[720px] mb-9 sm:mb-12 md:mb-14">
        <span
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
          style={{
            background: 'rgba(255,255,255,0.04)',
            borderColor: 'var(--stroke)',
            color: 'var(--text-soft)',
          }}
        >
          <span
            className="w-1.5 h-1.5 rounded-full"
            style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }}
          />
          How it works
        </span>
        <h2
          className="font-display font-extrabold m-0 mb-4"
          style={{ fontSize: 'clamp(2.2rem, 4.4vw, 3.4rem)', lineHeight: 1.05, letterSpacing: '-0.03em' }}
        >
          Three steps from <span className="aurora-text">vibe to play.</span>
        </h2>
        <p className="m-0 max-w-[580px]" style={{ fontSize: '1.06rem', color: 'var(--text-soft)', lineHeight: 1.55 }}>
          Most music apps make you guess what to play. We make you describe it. Then the catalog comes to you.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {[
          {
            num: '01',
            title: 'Tell us what you want',
            body: '"rainy tokyo lo-fi for late-night coding" works. So does "songs about my cat being chaotic." Type a vibe, mood, weather, scene — anything.',
            art: (
              <form onSubmit={submit} className="w-full">
                <div
                  className="flex items-center gap-2 w-full p-2 pr-2.5 rounded-xl border"
                  style={{
                    background: 'rgba(255,255,255,0.04)',
                    borderColor: 'var(--stroke-strong)',
                  }}
                >
                  <input
                    type="text"
                    value={userTyped ? text : ''}
                    placeholder={text || PROMPT_CYCLE[0]}
                    onFocus={() => setUserTyped(true)}
                    onChange={(e) => { setUserTyped(true); setText(e.target.value); }}
                    className="flex-1 min-w-0 px-2 py-2 bg-transparent outline-none text-[15px] font-medium"
                    style={{ color: 'var(--text)' }}
                    aria-label="Describe a vibe"
                  />
                  <button
                    type="submit"
                    className="px-3 py-1.5 rounded-lg text-xs font-bold inline-flex items-center gap-1.5 text-white shrink-0"
                    style={{ background: 'var(--brand)', boxShadow: '0 8px 18px -8px var(--brand-glow)' }}
                  >
                    <Wand2 className="w-3.5 h-3.5" /> Make
                  </button>
                </div>
              </form>
            ),
          },
          {
            num: '02',
            title: 'Agents build the queue',
            body: 'Thousands of AI agents — each with a sound, a label, a personality — write tracks that match. Cover art, lyrics, preview videos: all of it.',
            art: <AgentOrbit />,
          },
          {
            num: '03',
            title: 'Hit play, never run out',
            body: 'Listen, like, save, share. The more you play, the sharper your station gets. And the catalog keeps growing — by the second.',
            art: <Spectrum live bars={36} className="!h-24" />,
          },
        ].map((s) => (
          <article
            key={s.num}
            className="rounded-[22px] p-7 flex flex-col gap-3.5 relative overflow-hidden border min-h-[360px]"
            style={{
              background: 'var(--bg-elev-2)',
              borderColor: 'var(--stroke)',
            }}
          >
            <div
              className="font-display font-extrabold text-[13px]"
              style={{ letterSpacing: '0.12em', color: 'var(--brand)' }}
            >
              {s.num}
            </div>
            <h3
              className="font-display font-extrabold text-[22px] m-0"
              style={{ letterSpacing: '-0.01em' }}
            >
              {s.title}
            </h3>
            <p className="m-0 text-[14.5px]" style={{ color: 'var(--text-soft)', lineHeight: 1.55 }}>
              {s.body}
            </p>
            <div className="mt-auto h-[130px] flex items-center justify-center relative">{s.art}</div>
          </article>
        ))}
      </div>
    </section>
  );
}

function AgentOrbit() {
  return (
    <div className="relative w-[220px] h-[130px] mx-auto">
      <div
        className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 px-3 py-2 rounded-full z-[2] text-xs font-semibold"
        style={{
          background: 'var(--bg-elev-3)',
          border: '1px solid var(--stroke-strong)',
        }}
      >
        agents
      </div>
      {[0, 1, 2, 3, 4, 5].map((i) => (
        <span
          key={i}
          className="absolute left-1/2 top-1/2 w-[22px] h-[22px] rounded-full -ml-[11px] -mt-[11px]"
          style={{
            transform: `rotate(${i * 60}deg) translate(82px) rotate(-${i * 60}deg)`,
            background: `conic-gradient(from ${i * 60}deg, hsl(${(290 + i * 30) % 360} 80% 60%), hsl(${(i * 60) % 360} 80% 50%))`,
          }}
        />
      ))}
      <span
        className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full mym-orbit-spin"
        style={{ width: 180, height: 180, border: '1px dashed var(--stroke-strong)' }}
      />
      <span
        className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full mym-orbit-spin-rev opacity-40"
        style={{ width: 240, height: 240, border: '1px dashed var(--stroke-strong)' }}
      />
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Genres section
// ────────────────────────────────────────────────────────────────────
function Genres({ genres }: { genres: Array<{ name: string; count: string; hue: number; slug: string }> }) {
  return (
    <section id="genres" className="max-w-[1240px] mx-auto px-5 sm:px-6 py-14 sm:py-20 md:py-24">
      <div className="max-w-[720px] mb-9 sm:mb-12 md:mb-14">
        <span
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
          style={{ background: 'rgba(255,255,255,0.04)', borderColor: 'var(--stroke)', color: 'var(--text-soft)' }}
        >
          <span className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }} />
          Browse
        </span>
        <h2
          className="font-display font-extrabold m-0 mb-4"
          style={{ fontSize: 'clamp(2.2rem, 4.4vw, 3.4rem)', lineHeight: 1.05, letterSpacing: '-0.03em' }}
        >
          Every mood. Every<br />
          <span className="aurora-text">microscopic niche.</span>
        </h2>
        <p className="m-0 max-w-[580px]" style={{ fontSize: '1.06rem', color: 'var(--text-soft)', lineHeight: 1.55 }}>
          From &ldquo;phonk for skating empty parking lots&rdquo; to &ldquo;Bossa nova about the IRS&rdquo; — if it has a vibe, an agent has made an
          album about it.
        </p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
        {genres.map((g) => (
          <Link
            key={g.slug}
            href={`/genre/${g.slug}`}
            className="relative h-[150px] rounded-[14px] p-[18px] flex flex-col justify-between overflow-hidden border transition-transform hover:-translate-y-0.5"
            style={{
              background: `linear-gradient(135deg, hsl(${g.hue} 80% 55% / 0.55) 0%, hsl(${g.hue} 80% 35% / 0.18) 60%, transparent 100%), var(--bg-elev-2)`,
              borderColor: 'var(--stroke)',
            }}
          >
            <span
              className="absolute -right-5 -bottom-5 w-[90px] h-[90px] rounded-2xl opacity-50"
              style={{ background: `hsl(${g.hue} 80% 55%)`, transform: 'rotate(18deg)' }}
            />
            <h3 className="font-display font-extrabold text-[22px] m-0 relative" style={{ letterSpacing: '-0.01em' }}>
              {g.name}
            </h3>
            <span
              className="text-[11px] font-bold uppercase relative"
              style={{ letterSpacing: '0.12em', color: 'rgba(255,255,255,0.85)' }}
            >
              {g.count} tracks
            </span>
          </Link>
        ))}
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────────────
// Mobile section — interactable phone preview
// ────────────────────────────────────────────────────────────────────
function MobileSection({ tracks }: { tracks: TrackItem[] }) {
  return (
    <section id="mobile" className="max-w-[1240px] mx-auto px-5 sm:px-6 py-14 sm:py-20 md:py-24">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-14 lg:gap-20 items-center">
        <div className="max-w-[560px]">
          <span
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
            style={{ background: 'rgba(255,255,255,0.04)', borderColor: 'var(--stroke)', color: 'var(--text-soft)' }}
          >
            <span className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }} />
            On the go
          </span>
          <h2
            className="font-display font-extrabold m-0 mb-4"
            style={{ fontSize: 'clamp(2.2rem, 4.4vw, 3.4rem)', lineHeight: 1.05, letterSpacing: '-0.03em' }}
          >
            Plays where <br />
            <span className="aurora-text">you do.</span>
          </h2>
          <p className="m-0" style={{ fontSize: '1.06rem', color: 'var(--text-soft)', lineHeight: 1.55 }}>
            iOS &amp; Android. CarPlay &amp; Android Auto. Apple Watch glances. Lock-screen scrubbing. Sleep timer. 5-band EQ for the audiophiles.
          </p>
          <ul className="list-none p-0 my-7 flex flex-col gap-3">
            {[
              'CarPlay + Android Auto certified',
              'Lock-screen + lock-screen widget',
              'Background audio, offline downloads',
              '"Make a song about this" share extension',
            ].map((b) => (
              <li key={b} className="flex items-center gap-2.5 text-[14.5px]" style={{ color: 'var(--text-soft)' }}>
                <Check className="w-4 h-4" style={{ color: 'var(--brand)' }} />
                {b}
              </li>
            ))}
          </ul>
          <div className="flex flex-wrap gap-2">
            {['App Store', 'Google Play', 'CarPlay', 'Android Auto'].map((b) => (
              <span
                key={b}
                className="px-3 py-1.5 rounded-lg text-xs font-semibold border"
                style={{ background: 'rgba(255,255,255,0.05)', borderColor: 'var(--stroke)' }}
              >
                {b}
              </span>
            ))}
          </div>
        </div>
        <div className="flex justify-center">
          <Phone tracks={tracks} />
        </div>
      </div>
    </section>
  );
}

function Phone({ tracks }: { tracks: TrackItem[] }) {
  const { currentTrack, isPlaying, playTrack, togglePlay, nextTrack, prevTrack, progress, duration } = usePlayerStore();
  const featured = currentTrack ?? tracks[0];
  const list = tracks.slice(0, 3);
  const progressPct = duration > 0 ? Math.min(100, (progress / duration) * 100) : 38;

  const handleHeroPlay = () => {
    if (!featured) return;
    if (currentTrack && currentTrack.id === featured.id) togglePlay();
    else playTrack(featured, tracks);
  };

  const fmt = (s: number) => {
    if (!s || !Number.isFinite(s)) return '0:00';
    const m = Math.floor(s / 60);
    const r = Math.floor(s % 60);
    return `${m}:${r.toString().padStart(2, '0')}`;
  };

  return (
    <div
      className="relative w-[260px] h-[520px] sm:w-[290px] sm:h-[580px] max-w-full"
      style={{
        background: 'linear-gradient(180deg, #1a1a22 0%, #0f0f15 100%)',
        borderRadius: 44,
        padding: 12,
        border: '1.5px solid #2a2a36',
        boxShadow: '0 60px 80px -40px rgba(0,0,0,0.6), inset 0 0 0 1.5px rgba(255,255,255,0.04)',
      }}
    >
      <div
        className="absolute left-1/2 -translate-x-1/2 z-[2]"
        style={{ top: 14, width: 90, height: 22, background: '#000', borderRadius: 999 }}
      />
      <div
        className="w-full h-full overflow-hidden relative flex flex-col"
        style={{ background: '#0a0a0d', borderRadius: 32 }}
      >
        <div className="flex justify-between items-center text-xs font-bold text-white" style={{ padding: '14px 22px 6px' }}>
          <span>9:41</span>
          <span className="flex gap-1 items-center">
            <span className="block opacity-85" style={{ width: 14, height: 8, borderRadius: 2, background: '#fff' }} />
          </span>
        </div>

        <div className="relative mx-4 rounded-2xl overflow-hidden" style={{ height: 200 }}>
          <CoverArt seed={featured?.title || 'moonlight drive'} src={featured?.coverArt ?? undefined} />
          <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, transparent 30%, rgba(0,0,0,0.7) 100%)' }} />
          <div className="absolute left-4 right-4 bottom-3.5 text-white">
            <div className="text-[10px] opacity-60 uppercase" style={{ letterSpacing: '0.18em' }}>
              Now playing
            </div>
            <div className="font-bold text-[17px] mt-1 truncate">{featured?.title ?? 'Moonlight Drive'}</div>
            <div className="text-[11px] opacity-70 mt-0.5 truncate">
              {featured?.agent?.name ?? 'Astral Jukebox'} · {featured?.genre?.name ?? 'synthwave'}
            </div>
          </div>
        </div>

        <div className="text-white" style={{ padding: '14px 16px' }}>
          <Spectrum live={isPlaying && !!currentTrack} bars={28} />
          <div className="h-[3px] rounded-full mt-3 overflow-hidden" style={{ background: 'rgba(255,255,255,0.15)' }}>
            <div className="h-full transition-[width] duration-100" style={{ width: `${progressPct}%`, background: 'var(--brand)' }} />
          </div>
          <div className="flex justify-between text-[10px] mt-1.5 opacity-60 tabular-nums">
            <span>{currentTrack ? fmt(progress) : '0:00'}</span>
            <span>{featured?.duration ? fmt(featured.duration) : '0:00'}</span>
          </div>
          <div className="flex justify-around items-center mt-3.5">
            <button
              onClick={prevTrack}
              disabled={!currentTrack}
              aria-label="Previous"
              className="text-[22px] disabled:opacity-30"
              style={{ color: 'rgba(255,255,255,0.85)' }}
            >
              ⏮
            </button>
            <button
              onClick={handleHeroPlay}
              aria-label={isPlaying && currentTrack?.id === featured?.id ? 'Pause' : 'Play'}
              className="w-[42px] h-[42px] rounded-full inline-flex items-center justify-center text-white"
              style={{ background: 'var(--brand)', boxShadow: '0 0 20px var(--brand-glow)' }}
            >
              {isPlaying && currentTrack?.id === featured?.id ? (
                <Pause className="w-4 h-4" fill="currentColor" />
              ) : (
                <Play className="w-4 h-4" fill="currentColor" />
              )}
            </button>
            <button
              onClick={nextTrack}
              disabled={!currentTrack}
              aria-label="Next"
              className="text-[22px] disabled:opacity-30"
              style={{ color: 'rgba(255,255,255,0.85)' }}
            >
              ⏭
            </button>
          </div>
        </div>

        <div className="flex-1 flex flex-col gap-2" style={{ padding: '8px 16px' }}>
          {list.map((t) => {
            const isThis = currentTrack?.id === t.id;
            return (
              <button
                key={t.id}
                onClick={() => playTrack(t, tracks)}
                className="flex items-center gap-2.5 text-left rounded-md p-1 -m-1 transition-colors hover:bg-white/[0.04]"
              >
                <div className="w-9 h-9 rounded-md flex-shrink-0 overflow-hidden relative">
                  <CoverArt seed={t.title} src={t.coverArt} />
                </div>
                <div className="flex-1 min-w-0">
                  <div
                    className="text-xs font-semibold truncate"
                    style={{ color: isThis ? 'var(--brand)' : 'white' }}
                  >
                    {t.title}
                  </div>
                  <div className="text-[10px] opacity-55 truncate text-white">{t.agent?.name ?? ''}</div>
                </div>
                <div className="text-[10px] opacity-50 text-white">{fmt(t.duration)}</div>
              </button>
            );
          })}
        </div>

        <div
          className="absolute left-1/2 -translate-x-1/2 rounded-full"
          style={{ bottom: 6, width: 100, height: 4, background: 'rgba(255,255,255,0.4)' }}
        />
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Pricing
// ────────────────────────────────────────────────────────────────────
function Pricing() {
  const tiers: Array<{
    tier: string;
    price: string;
    sub: string;
    features: string[];
    cta: { label: string; href: string };
    popular?: boolean;
  }> = [
    {
      tier: 'Free',
      price: '$0',
      sub: 'Listen forever, free.',
      features: ['Unlimited streaming', '3 generations / day', 'Standard audio', 'Mobile + CarPlay'],
      cta: { label: 'Start listening', href: '/register' },
    },
    {
      tier: 'Premium',
      price: '$14.99',
      sub: 'Lossless + unlimited generation.',
      features: ['Everything in Free', '500 generations / day', 'Lossless audio', 'Stems & sync licensing', 'Offline downloads'],
      cta: { label: 'Go Premium', href: '/pricing' },
      popular: true,
    },
    {
      tier: 'Creator',
      price: '$9.99',
      sub: 'Spin up agents & publish.',
      features: ['Everything in Premium', 'Publish unlimited agents', 'Tips & channel subs', 'Stripe payouts'],
      cta: { label: 'Become a creator', href: '/register?role=creator' },
    },
  ];

  return (
    <section id="pricing" className="max-w-[1240px] mx-auto px-5 sm:px-6 py-14 sm:py-20 md:py-24">
      <div className="max-w-[720px] mb-9 sm:mb-12 md:mb-14">
        <span
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
          style={{ background: 'rgba(255,255,255,0.04)', borderColor: 'var(--stroke)', color: 'var(--text-soft)' }}
        >
          <span className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }} />
          Pricing
        </span>
        <h2
          className="font-display font-extrabold m-0 mb-4"
          style={{ fontSize: 'clamp(2.2rem, 4.4vw, 3.4rem)', lineHeight: 1.05, letterSpacing: '-0.03em' }}
        >
          Free to listen.<br />
          <span className="aurora-text">Pro for power users.</span>
        </h2>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 lg:items-stretch">
        {tiers.map((p) => (
          <div
            key={p.tier}
            className="rounded-[22px] p-7 flex flex-col gap-3.5 relative border"
            style={
              p.popular
                ? {
                    background: 'linear-gradient(160deg, var(--brand-soft), var(--bg-elev-2) 60%)',
                    borderColor: 'var(--brand)',
                    boxShadow: '0 30px 60px -30px var(--brand-glow)',
                  }
                : { background: 'var(--bg-elev-2)', borderColor: 'var(--stroke)' }
            }
          >
            {p.popular && (
              <span
                className="absolute -top-2.5 right-5 text-[11px] font-extrabold px-2.5 py-1 rounded-full text-white"
                style={{ background: 'var(--brand)', letterSpacing: '0.04em' }}
              >
                Most popular
              </span>
            )}
            <div
              className="font-display font-extrabold text-[14px] uppercase"
              style={{ letterSpacing: '0.12em', color: 'var(--text-mute)' }}
            >
              {p.tier}
            </div>
            <div className="font-display font-extrabold text-[44px] leading-none" style={{ letterSpacing: '-0.03em' }}>
              {p.price}
              <span className="text-sm ml-1.5 font-semibold" style={{ color: 'var(--text-mute)' }}>
                /mo
              </span>
            </div>
            <div className="text-[13px] mb-1" style={{ color: 'var(--text-soft)' }}>
              {p.sub}
            </div>
            <ul className="list-none p-0 m-0 mb-4 flex flex-col gap-2.5 flex-1">
              {p.features.map((f) => (
                <li key={f} className="flex items-center gap-2.5 text-[13.5px]" style={{ color: 'var(--text-soft)' }}>
                  <Check className="w-4 h-4" style={{ color: 'var(--brand)' }} />
                  {f}
                </li>
              ))}
            </ul>
            <Link href={p.cta.href} className={`${p.popular ? 'mym-cta' : 'mym-ghost'} w-full justify-center`}>
              {p.cta.label}
            </Link>
          </div>
        ))}
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────────────
// FAQ
// ────────────────────────────────────────────────────────────────────
function FAQ() {
  const [open, setOpen] = useState(0);
  return (
    <section className="max-w-[1240px] mx-auto px-5 sm:px-6 py-14 sm:py-20 md:py-24">
      <div className="max-w-[720px] mb-9 sm:mb-12 md:mb-14">
        <span
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-5"
          style={{ background: 'rgba(255,255,255,0.04)', borderColor: 'var(--stroke)', color: 'var(--text-soft)' }}
        >
          <span className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }} />
          Questions
        </span>
        <h2
          className="font-display font-extrabold m-0 mb-4"
          style={{ fontSize: 'clamp(2.2rem, 4.4vw, 3.4rem)', lineHeight: 1.05, letterSpacing: '-0.03em' }}
        >
          Frequently<br />
          <span className="aurora-text">asked</span>.
        </h2>
      </div>
      <div className="flex flex-col gap-2.5">
        {FAQ_ITEMS.map(([q, a], i) => {
          const isOpen = open === i;
          return (
            <div
              key={q}
              onClick={() => setOpen(isOpen ? -1 : i)}
              className="rounded-[14px] p-5 cursor-pointer transition-colors border"
              style={{
                background: isOpen ? 'var(--bg-elev-3)' : 'var(--bg-elev-2)',
                borderColor: 'var(--stroke)',
              }}
            >
              <div className="flex justify-between items-center font-display font-bold text-[17px] gap-3">
                <span>{q}</span>
                <span className="text-[22px] leading-none" style={{ color: 'var(--brand)' }}>
                  {isOpen ? '−' : '+'}
                </span>
              </div>
              {isOpen && (
                <div className="mt-3 text-[14.5px]" style={{ color: 'var(--text-soft)', lineHeight: 1.6 }}>
                  {a}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────────────
// CTA Band
// ────────────────────────────────────────────────────────────────────
function CTABand({ tracks }: { tracks: TrackItem[] }) {
  const { isPlaying, playTrack } = usePlayerStore();
  const start = () => {
    const first = tracks[0];
    if (first) playTrack(first, tracks);
  };
  return (
    <section className="relative isolate text-center overflow-hidden mt-10" style={{ padding: '100px 24px 0' }}>
      <div
        className="absolute inset-0 -z-10"
        style={{
          background:
            'radial-gradient(60% 60% at 50% 100%, color-mix(in srgb, var(--brand) 30%, transparent) 0%, transparent 70%), radial-gradient(50% 50% at 20% 30%, color-mix(in srgb, var(--brand-2) 20%, transparent) 0%, transparent 70%)',
        }}
      />
      <div className="max-w-[880px] mx-auto">
        <h2
          className="font-display font-extrabold m-0 mb-4"
          style={{ fontSize: 'clamp(2.4rem, 5.6vw, 4rem)', letterSpacing: '-0.03em', lineHeight: 1.05 }}
        >
          Your turn.<br />
          Make something new.
        </h2>
        <p className="m-0 mb-7" style={{ color: 'var(--text-soft)', fontSize: '1.1rem' }}>
          Describe a vibe. AI writes and produces the track. No credit card, no login to start.
        </p>
        <div className="flex flex-wrap justify-center gap-3">
          <Link href="/create" className="mym-cta">
            <Wand2 className="w-4 h-4" /> {t('landing.primaryCta')} — free
          </Link>
          <button onClick={start} className="mym-ghost">
            <PlayGlyph /> {t('landing.secondaryCta')}
          </button>
        </div>
        <SpectrumLarge live={isPlaying} />
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────────────
// Top-level landing page
// ────────────────────────────────────────────────────────────────────
export function LandingPage() {
  const [tracks, setTracks] = useState<TrackItem[]>([]);
  const [genres, setGenres] = useState<Array<{ name: string; count: string; hue: number; slug: string }>>(FALLBACK_GENRES);

  useEffect(() => {
    track('landing_view');
  }, []);

  useEffect(() => {
    let cancelled = false;
    api
      .get('/tracks/trending')
      .then((res) => {
        if (cancelled) return;
        const fetched = (res.data?.tracks || []) as TrackItem[];
        if (fetched.length > 0) setTracks(fetched);
      })
      .catch(() => undefined);

    api
      .get('/genres')
      .then((res) => {
        if (cancelled) return;
        type ApiGenre = { name?: string; slug?: string; color?: string | null; _count?: { tracks?: number } };
        const fetched: ApiGenre[] = res.data?.genres || [];
        if (fetched.length === 0) return;
        const mapped = fetched.slice(0, 8).map((g, i) => {
          const hueFromColor = colorToHue(g.color ?? null);
          const fallbackHue = FALLBACK_GENRES[i % FALLBACK_GENRES.length]?.hue ?? 290;
          return {
            name: g.name ?? 'Unknown',
            slug: g.slug ?? (g.name ?? 'unknown').toLowerCase().replace(/\s+/g, '-'),
            count: (g._count?.tracks ?? 0).toLocaleString(),
            hue: hueFromColor ?? fallbackHue,
          };
        });
        setGenres(mapped);
      })
      .catch(() => undefined);

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="mym-landing-root">
      <HeroDeckLayout tracks={tracks} />

      <MarqueeStrip />
      <DiscoverGrid tracks={tracks} />
      <HowItWorks />
      <Genres genres={genres} />
      <MobileSection tracks={tracks} />
      <Pricing />
      <FAQ />
      <CTABand tracks={tracks} />
      <StickyMobileCTA />
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────
// Sticky mobile-web "Make a song" bar — guests only, mobile breakpoint
// ────────────────────────────────────────────────────────────────────
function StickyMobileCTA() {
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const [hasMounted, setHasMounted] = useState(false);
  useEffect(() => setHasMounted(true), []);
  if (!hasMounted || isAuthenticated) return null;
  return (
    <div
      className="md:hidden fixed left-0 right-0 z-40 px-4"
      style={{ bottom: 'calc(env(safe-area-inset-bottom, 0px) + 12px)' }}
    >
      <Link
        href="/create"
        onClick={() => track('landing_cta_click', { surface: 'sticky_mobile' })}
        className="mym-cta w-full justify-center text-base"
        style={{
          height: 52,
          boxShadow: '0 18px 40px -10px var(--brand-glow), 0 0 0 1px rgba(255,255,255,0.04)',
        }}
      >
        <Wand2 className="w-4 h-4" /> Make a song — free
      </Link>
    </div>
  );
}

function HeroDeckLayout({ tracks }: { tracks: TrackItem[] }) {
  const { playTrack } = usePlayerStore();
  const router = useRouter();
  const [vibePrompt, setVibePrompt] = useState('');

  const start = () => {
    const first = tracks[0];
    if (first) playTrack(first, tracks);
  };

  const handleMakeSong = (e: React.FormEvent) => {
    e.preventDefault();
    const value = vibePrompt.trim();
    track('prompt_typed', { surface: 'hero', length: value.length });
    track('landing_cta_click', { surface: 'hero_inline' });
    router.push(value ? `/create?prompt=${encodeURIComponent(value)}` : '/create');
  };

  return (
    <div className="relative isolate overflow-hidden pt-16 pb-12 sm:pt-24 sm:pb-16 md:pt-[140px] md:pb-[90px]">
      <HeroBackdrop />
      <div className="relative max-w-[1240px] mx-auto px-5 sm:px-6 grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_minmax(0,480px)] gap-10 sm:gap-12 lg:gap-16 items-center">
        <div className="min-w-0">
          <span
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border mb-4 sm:mb-5"
            style={{ background: 'rgba(255,255,255,0.04)', borderColor: 'var(--stroke)', color: 'var(--text-soft)' }}
          >
            <span className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--brand)', boxShadow: '0 0 10px var(--brand-glow)' }} />
            Personal radio, infinite
          </span>
          <h1
            className="font-display font-extrabold m-0 mb-4 sm:mb-5"
            style={{ fontSize: 'clamp(2.1rem, 8vw, 4.8rem)', lineHeight: 1.04, letterSpacing: '-0.035em', textWrap: 'balance' }}
          >
            Your station,<br />
            <span className="aurora-text">re-recorded daily.</span>
          </h1>
          <p
            className="m-0 mb-6 sm:mb-7 max-w-[560px]"
            style={{ fontSize: 'clamp(0.98rem, 1.4vw, 1.18rem)', color: 'var(--text-soft)', lineHeight: 1.55 }}
          >
            Hit play. AI agents keep the queue full of new music shaped by what you love — across moods, niches, and 4am
            detours.
          </p>

          {/* Inline vibe prompt → /create */}
          <form onSubmit={handleMakeSong} className="flex gap-2 mb-4 max-w-[520px]">
            <input
              type="text"
              value={vibePrompt}
              onChange={(e) => setVibePrompt(e.target.value)}
              placeholder="rainy tokyo lo-fi, 3am energy…"
              className="flex-1 min-w-0 px-4 py-3 rounded-xl text-sm font-medium outline-none"
              style={{
                background: 'rgba(255,255,255,0.06)',
                border: '1px solid var(--stroke-strong)',
                color: 'var(--text)',
              }}
            />
            <button type="submit" className="mym-cta shrink-0">
              <Wand2 className="w-4 h-4" /> {t('landing.primaryCta')}
            </button>
          </form>

          <div className="flex flex-wrap gap-3">
            <button onClick={start} className="mym-ghost">
              <PlayGlyph /> {t('landing.secondaryCta')}
            </button>
            <Link href="#discover" className="mym-ghost" style={{ opacity: 0.7 }}>
              Browse the catalog
            </Link>
          </div>
        </div>
        <div className="relative">
          <HeroDeck tracks={tracks} />
          <div
            className="absolute -top-3 right-2 sm:-top-4 sm:-right-2 z-[5] px-3 py-2 sm:px-3.5 sm:py-2.5 rounded-2xl flex items-center gap-2 sm:gap-2.5 text-[10.5px] sm:text-[11px] font-semibold text-white max-w-[200px]"
            style={{
              background: 'var(--brand)',
              boxShadow: '0 16px 36px -12px var(--brand-glow)',
              transform: 'rotate(4deg)',
            }}
          >
            <span className="font-display font-extrabold text-lg sm:text-xl leading-none">∞</span>
            <span className="leading-tight opacity-95">Endless queue<br />tuned to your taste</span>
          </div>
        </div>
      </div>
    </div>
  );
}

function colorToHue(color: string | null): number | null {
  if (!color) return null;
  const m = color.match(/^#?([\da-fA-F]{6})$/);
  if (!m || !m[1]) return null;
  const hex = m[1];
  const r = parseInt(hex.slice(0, 2), 16) / 255;
  const g = parseInt(hex.slice(2, 4), 16) / 255;
  const b = parseInt(hex.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  if (max === min) return 0;
  const d = max - min;
  let h = 0;
  if (max === r) h = ((g - b) / d) % 6;
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  h = h * 60;
  if (h < 0) h += 360;
  return Math.round(h);
}
